package gov.dlf.presentation;


import gov.dlf.facade.*;
import gov.dlf.external.*;
import gov.dlf.logic.*;

import java.util.Date;


import net.maintrend.appmanager.*;
import net.maintrend.datamanager.*;
import net.maintrend.interfaces.*;
import net.maintrend.interlink.*;
import net.maintrend.jdatapanel.*;
import net.maintrend.jdatapanel.edit.*;
import net.maintrend.jdatapanel.commands.*;
import net.maintrend.mdi.*;
import net.maintrend.rallyengine.*;
import net.maintrend.util.*;



/**
 * __Comment
 *
 * Generated by Rally-to-Java Convertor. MainTrend Ltd.
 */
public class NOTIFICACIONES_FAM_FR
     extends Form
{
  // -------------------------------------------------------------------
  // ----------   Instance Attributes   --------------------------------

  /**  */
  public SAIC_DMQ_ORA_Application app;



  // -------------------------------------------------------------------
  // ----------   Constructors and supporting methods   ----------------

  /**
   *
   */
  public NOTIFICACIONES_FAM_FR ( )
  {
    super ( );
    this.setName ( "NOTIFICACIONES_FAM_FR" );

    Debug.println ( Debug.TRACE, "NOTIFICACIONES_FAM_FR - constructor" );

    this.setDefinitionPath ( "gov/dlf/presentation/NOTIFICACIONES_FAM_FR.jdp" );
    String definition = ResourceUtil.getResourceText ( this.definitionPath );
    this.setDefinition     ( definition );

    this.setHighLightSelected   ( false );
    this.compressFieldLocations ( false, true );  // Compresses only Y-locations
  }
  
  
  /**
   * Overrides ancestor's script
   *
   * @param __app
   */
  public void setApplication ( Application __app )
  {
    this.app = ( SAIC_DMQ_ORA_Application ) __app;
    if ( this.app != null )
    {
      this.setDataManager ( this.app.getDataManager ( ) );
    }

    ICalculator           calculator;
    IBooleanValueProvider txtVisible;
    IBooleanValueProvider groupVisible;
    IObjectValueProvider  valueProvider;
    JDataPanelField       field;
    JDataPanelTextGroup   txtGroup;
    JDataPanelGroup       visGroup;

    this.setArguments ( "SERV_JEFE_FAM_INFO_GP", new NOTIFICACIONES_FAM_FR_SERV_JEFE_FAM_INFO_GP_Arguments ( this ) );
    this.setArguments ( "SERV_SERV_ASOC_FAM_GP", new NOTIFICACIONES_FAM_FR_SERV_SERV_ASOC_FAM_GP_Arguments ( this ) );
    
    this.setObjectEvents ( );
        
  }


  /**
   * Overrides ancestor's method
   * 
   * @return
   */
  public RallyApplication getApplication ( )
  {
    return this.app;
  }



  // -------------------------------------------------------------------
  // ----------   Action Sites   ---------------------------------------

  /**
   *
   */
  public void setObjectEvents ( )
  {
    this.registerListener ( "FAM_PARK", JDataPanelListener.BEFOREENTER, new JDataPanelListener ( )
    {
      public boolean eventFired ( String eventName )
      {
        app.errorFlag = true; NOTIFICACIONES_CHK_SERVICIOS_ADL.exec ( app ); return app.errorFlag;
      }
    } );
    this.registerListener ( "FAM_PARK", JDataPanelListener.BEFORELEAVE, new JDataPanelListener ( )
    {
      public boolean eventFired ( String eventName )
      {
        app.errorFlag = true; SERV_CHECK_NUM_SERVICIOS_AF_ADL.exec ( app ); return app.errorFlag;
      }
    } );
    this.registerListener ( "PARK_SERV", JDataPanelListener.BEFOREENTER, new JDataPanelListener ( )
    {
      public boolean eventFired ( String eventName )
      {
        app.errorFlag = true; FLECHITA_ADL.exec ( app ); return app.errorFlag;
      }
    } );
    this.registerListener ( "PARK_SERV", JDataPanelListener.BEFORELEAVE, new JDataPanelListener ( )
    {
      public boolean eventFired ( String eventName )
      {
        app.errorFlag = true; FLECHITA_ADL.exec ( app ); return app.errorFlag;
      }
    } );
    this.registerListener ( "SERV_SERV_ASOC_FAM_GP", JDataPanelListener.HOTKEYPRESS, new JDataPanelListener ( )
    {
      public boolean eventFired ( String eventName )
      {
        app.errorFlag = true; NOTIFICACIONES_INFORMES_ADL.exec ( app ); return app.errorFlag;
      }
    } );
  }
}





/**
 *
 */
class NOTIFICACIONES_FAM_FR_SERV_JEFE_FAM_INFO_GP_Arguments extends JDataPanelGroupArguments
{
  /**  */
  protected Form model;
  /**  */
  protected SAIC_DMQ_ORA_Application app = null;

  /**  */
  public NOTIFICACIONES_FAM_FR_SERV_JEFE_FAM_INFO_GP_Arguments ( Form form )
  {
    this.model = form;

    this.setArgName ( "SSN_JEFE_PAR" );
  }

  /**  */
  public Object getArgValue ( String argName )
  {
    if ( this.app == null ) this.app = ( SAIC_DMQ_ORA_Application ) this.model.getApplication ( );
    if ( argName == null )
    {
      return null;
    }
    else if ( argName.equals ( "SSN_JEFE_PAR" ) )
    {
      return this.app.getSSN_JEFE_FAM_GBL ( ); // Global Variable
    }
    return null;
  }
}



/**
 *
 */
class NOTIFICACIONES_FAM_FR_SERV_SERV_ASOC_FAM_GP_Arguments extends JDataPanelGroupArguments
{
  /**  */
  protected Form model;
  /**  */
  protected SAIC_DMQ_ORA_Application app = null;

  /**  */
  public NOTIFICACIONES_FAM_FR_SERV_SERV_ASOC_FAM_GP_Arguments ( Form form )
  {
    this.model = form;

    this.setArgName ( "SSN_JEFE_PAR" );
  }

  /**  */
  public Object getArgValue ( String argName )
  {
    if ( this.app == null ) this.app = ( SAIC_DMQ_ORA_Application ) this.model.getApplication ( );
    if ( argName == null )
    {
      return null;
    }
    else if ( argName.equals ( "SSN_JEFE_PAR" ) )
    {
      return this.app.getSSN_JEFE_FAM_GBL ( ); // Global Variable
    }
    return null;
  }
}






