package gov.dlf.logic;


import gov.dlf.external.*;
import gov.dlf.facade.*;
import gov.dlf.presentation.*;


import java.util.*;

import net.maintrend.appmanager.*;
import net.maintrend.datamanager.*;
import net.maintrend.interfaces.*;
import net.maintrend.interlink.*;
import net.maintrend.mdi.*;
import net.maintrend.rallyengine.*;
import net.maintrend.util.*;
import net.maintrend.util.format.*;



/**
 * __Comment
 *
 * Generated by Rally-to-Java Convertor. MainTrend Ltd.
 */
public class PANE_NUM_MESES_ADL
     extends ADL
{
  // -------------------------------------------------------------------
  // ----------   Class Attributes   -----------------------------------

  /**  */
  public static boolean staticCall = false;



  // -------------------------------------------------------------------
  // ----------   Instance Attributes   --------------------------------

  /**  */
  public SAIC_DMQ_ORA_Application app;
  /**  */
  public RallyDataManager dm = null;



  // -------------------------------------------------------------------
  // ----------   Instance Condition Attributes   ----------------------
 
  public boolean _condition0 = false;

 

  // -------------------------------------------------------------------
  // ----------   Instance Export Attributes   -------------------------

  public double OPEN_ID = 0;

  public double STATUS_ID = 0;

  public double OPEN2_ID = 0;

  public double STATUS2_ID = 0;





  // -------------------------------------------------------------------
  // ----------   Instance Attributes' Access Methods   ----------------

  
  /**  */
  public static void setOPEN_ID  ( RallyApplication __app, Parameter value )
  {
    ( ( PANE_NUM_MESES_ADL ) __app.getADL ( PANE_NUM_MESES_ADL.class ) ).OPEN_ID = value.getDouble ( );
  }  

  
  /**  */
  public static void setSTATUS_ID  ( RallyApplication __app, Parameter value )
  {
    ( ( PANE_NUM_MESES_ADL ) __app.getADL ( PANE_NUM_MESES_ADL.class ) ).STATUS_ID = value.getDouble ( );
  }  

  
  /**  */
  public static void setOPEN2_ID  ( RallyApplication __app, Parameter value )
  {
    ( ( PANE_NUM_MESES_ADL ) __app.getADL ( PANE_NUM_MESES_ADL.class ) ).OPEN2_ID = value.getDouble ( );
  }  

  
  /**  */
  public static void setSTATUS2_ID  ( RallyApplication __app, Parameter value )
  {
    ( ( PANE_NUM_MESES_ADL ) __app.getADL ( PANE_NUM_MESES_ADL.class ) ).STATUS2_ID = value.getDouble ( );
  }  
    



  /**  */
  public static double getOPEN_ID  ( RallyApplication __app )
  {
    return ( ( PANE_NUM_MESES_ADL ) __app.getADL ( PANE_NUM_MESES_ADL.class ) ).OPEN_ID;
  }


  /**  */
  public static Double getOPEN_IDDouble ( RallyApplication __app )
  {
    return new Double ( ( ( PANE_NUM_MESES_ADL ) __app.getADL ( PANE_NUM_MESES_ADL.class ) ).OPEN_ID );
  }


  /**  */
  public static void setOPEN_ID  ( RallyApplication __app, double value )
  {
    ( ( PANE_NUM_MESES_ADL ) __app.getADL ( PANE_NUM_MESES_ADL.class ) ).OPEN_ID = value;
  }


  /**  */
  public static void setOPEN_ID  ( RallyApplication __app, Object value )
  {
    ( ( PANE_NUM_MESES_ADL ) __app.getADL ( PANE_NUM_MESES_ADL.class ) ).OPEN_ID = ( ( Double ) value ).doubleValue ( );
  }


  /**  */
  public static double getSTATUS_ID  ( RallyApplication __app )
  {
    return ( ( PANE_NUM_MESES_ADL ) __app.getADL ( PANE_NUM_MESES_ADL.class ) ).STATUS_ID;
  }


  /**  */
  public static Double getSTATUS_IDDouble ( RallyApplication __app )
  {
    return new Double ( ( ( PANE_NUM_MESES_ADL ) __app.getADL ( PANE_NUM_MESES_ADL.class ) ).STATUS_ID );
  }


  /**  */
  public static void setSTATUS_ID  ( RallyApplication __app, double value )
  {
    ( ( PANE_NUM_MESES_ADL ) __app.getADL ( PANE_NUM_MESES_ADL.class ) ).STATUS_ID = value;
  }


  /**  */
  public static void setSTATUS_ID  ( RallyApplication __app, Object value )
  {
    ( ( PANE_NUM_MESES_ADL ) __app.getADL ( PANE_NUM_MESES_ADL.class ) ).STATUS_ID = ( ( Double ) value ).doubleValue ( );
  }


  /**  */
  public static double getOPEN2_ID  ( RallyApplication __app )
  {
    return ( ( PANE_NUM_MESES_ADL ) __app.getADL ( PANE_NUM_MESES_ADL.class ) ).OPEN2_ID;
  }


  /**  */
  public static Double getOPEN2_IDDouble ( RallyApplication __app )
  {
    return new Double ( ( ( PANE_NUM_MESES_ADL ) __app.getADL ( PANE_NUM_MESES_ADL.class ) ).OPEN2_ID );
  }


  /**  */
  public static void setOPEN2_ID  ( RallyApplication __app, double value )
  {
    ( ( PANE_NUM_MESES_ADL ) __app.getADL ( PANE_NUM_MESES_ADL.class ) ).OPEN2_ID = value;
  }


  /**  */
  public static void setOPEN2_ID  ( RallyApplication __app, Object value )
  {
    ( ( PANE_NUM_MESES_ADL ) __app.getADL ( PANE_NUM_MESES_ADL.class ) ).OPEN2_ID = ( ( Double ) value ).doubleValue ( );
  }


  /**  */
  public static double getSTATUS2_ID  ( RallyApplication __app )
  {
    return ( ( PANE_NUM_MESES_ADL ) __app.getADL ( PANE_NUM_MESES_ADL.class ) ).STATUS2_ID;
  }


  /**  */
  public static Double getSTATUS2_IDDouble ( RallyApplication __app )
  {
    return new Double ( ( ( PANE_NUM_MESES_ADL ) __app.getADL ( PANE_NUM_MESES_ADL.class ) ).STATUS2_ID );
  }


  /**  */
  public static void setSTATUS2_ID  ( RallyApplication __app, double value )
  {
    ( ( PANE_NUM_MESES_ADL ) __app.getADL ( PANE_NUM_MESES_ADL.class ) ).STATUS2_ID = value;
  }


  /**  */
  public static void setSTATUS2_ID  ( RallyApplication __app, Object value )
  {
    ( ( PANE_NUM_MESES_ADL ) __app.getADL ( PANE_NUM_MESES_ADL.class ) ).STATUS2_ID = ( ( Double ) value ).doubleValue ( );
  }



  // -------------------------------------------------------------------
  // ----------   Methods   --------------------------------------------

  /**
   * 
   * @param __app
   * @return
   */
  public static PANE_NUM_MESES_ADL get ( RallyApplication __app )
  {
    PANE_NUM_MESES_ADL adl = new PANE_NUM_MESES_ADL ( );
    __app.register ( adl, "PANE_NUM_MESES_ADL" );
    __app.setADL ( PANE_NUM_MESES_ADL.class, adl ); 
    adl.setApplication ( __app );
    return adl;
  }


  /**
   *
   * @param __app
   * @param ps
   *
   * @return
   */
  public static void exec ( RallyApplication __app, ParameterSet ps )
  {
    PANE_NUM_MESES_ADL.get ( __app ).process ( ps );
  }


  /**
   *
   * @param __app
   *
   * @return
   */
  public static void exec ( RallyApplication __app )
  {
    ParameterSet ps = null;
    PANE_NUM_MESES_ADL.exec ( __app, ps );
  }


  /**
   * Overrides the ancestor's method
   * 
   * @param __app
   */
  public void setApplication ( RallyApplication __app )
  {
    this.app = ( SAIC_DMQ_ORA_Application ) __app;
    if ( this.app != null )
    {
      this.dm = ( RallyDataManager ) this.app.getDataManager ( );
    }
  }


  /**
   * Overrides the ancestor's method
   * 
   * @param parms
   */
  public void execute ( ParameterSet parms )
  {
    this.process ( parms );
  }




  /**
   *
   */
  protected void doReturn ( )
  {
    this.unregister ( );
  }


  /**
   *
   */
  public void unregister ( )
  {
    this.app.unregister ( this );
    IRegisteredObject rObj = this.app.get ( "PANE_NUM_MESES_ADL" );
    if ( rObj != null && rObj instanceof PANE_NUM_MESES_ADL )
    {
      this.app.setADL ( PANE_NUM_MESES_ADL.class, ( PANE_NUM_MESES_ADL ) rObj );
    }
  }


  /**
   * Overrides the ancestor's method
   * 
   * @param ps
   */
  protected void process ( ParameterSet ps )
  {
    Debug.println ( Debug.TRACE, "PANE_NUM_MESES_ADL Step " + this.currentStep );
    super.process ( ps );
    switch ( this.currentStep ) 
    {
      case 0:  { this.currentStep ++; this.step0 ( this.keyParms ); break; }
      case 1:  { this.currentStep ++; this.step1 ( this.keyParms ); break; }
      default: 
      { 
        this.currentStep = 0;
        Debug.println ( Debug.TRACE, "PANE_NUM_MESES_ADL ended" );
        this.unregister ( );
        break;
      }
    }
    if ( this.currentStep > 0 ) this.app.goOn ( );
  }



  /**
   *
   */
  protected void step0 ( ParameterSet ps )
  {

    if ( Compare.equals ( this.app.MANT_ACCION_SERV_GBL, "IS" ) ) 
    {
      this.doReturn ( );
      return;
    }
    if ( ( Compare.equals ( this.app.COD_SERV_GBL, "AE-C" ) ) || ( Compare.equals ( this.app.COD_SERV_GBL, "AE-D" ) ) ) 
    {
      this._condition0 = true;
    }
    else
    {
      this._condition0 = false;
    }
    if ( this._condition0 )
    {
      CHECK_PRESUNTIVO.exec ( this.app );
      return;
    }

  }


  /**
   *
   */
  protected void step1 ( ParameterSet ps )
  {
    if ( ( Compare.equals ( this.app.COD_SERV_GBL, "AE-C" ) ) && ( Compare.gt ( this.app.form ( "FECHAS_SERVICIO_FRM" ).getDoubleItem ( "NUM_MESES" ), 6 ) )  ) 
    {
      this.app.setError ( 0, 2762 );
      this.app.errorFlag = false;
    }
    if ( ( Compare.equals ( this.app.COD_SERV_GBL, "AE-D" ) ) && ( Compare.gt ( this.app.form ( "FECHAS_SERVICIO_FRM" ).getDoubleItem ( "NUM_MESES" ), 12 ) )  ) 
    {
      this.app.setError ( 1, 2771 );
      this.app.errorFlag = false;
    }

  }
}



/* ---------------------------------------------------------------------


     
PROCEDURE PANE_NUM_MESES_ADL;
VAR
OPEN_ID : NUMBER;
STATUS_ID : NUMBER;
OPEN2_ID : NUMBER;
STATUS2_ID : NUMBER;


BEGIN
SET_TRACE();

IF MANT_ACCION_SERV_GBL ='IS'
   THEN RETURN;

{SE COMENTA LA RUTINA YA QUE A VECES SE QUEDA EJECUTANDO AL CERTIFICAR Y}
{ OTRAS VECES FUNCIONA   ISP   26-OCT-2005}

{IF SUBSTR(COD_SERV_GBL,0,4)='PANE'
        THEN BEGIN
                FECHAS_SERVICIO_FRM.NUM_MESES := 1;
             END;}



IF (COD_SERV_GBL = 'AE-C') OR (COD_SERV_GBL = 'AE-D')
        THEN
            CALL CHECK_PRESUNTIVO;


IF (COD_SERV_GBL = 'AE-C') AND (FECHAS_SERVICIO_FRM.NUM_MESES > 6)
        THEN
            BEGIN
                ERROR(2762);
                SET_FAILURE();
            END;

IF (COD_SERV_GBL = 'AE-D') AND (FECHAS_SERVICIO_FRM.NUM_MESES > 12)
        THEN
            BEGIN
                ERROR(2771);
                SET_FAILURE();
            END;

SET_NOTRACE();
END;
    



--------------------------------------------------------------------- */
