package gov.dlf.presentation;


import gov.dlf.facade.*;
import gov.dlf.external.*;
import gov.dlf.logic.*;

import java.util.Date;


import net.maintrend.appmanager.*;
import net.maintrend.datamanager.*;
import net.maintrend.interfaces.*;
import net.maintrend.interlink.*;
import net.maintrend.jdatapanel.*;
import net.maintrend.jdatapanel.edit.*;
import net.maintrend.jdatapanel.commands.*;
import net.maintrend.mdi.*;
import net.maintrend.rallyengine.*;
import net.maintrend.util.*;



/**
 * __Comment
 *
 * Generated by Rally-to-Java Convertor. MainTrend Ltd.
 */
public class RETRO_PAEX_FR
     extends Form
{
  // -------------------------------------------------------------------
  // ----------   Instance Attributes   --------------------------------

  /**  */
  public SAIC_DMQ_ORA_Application app;



  // -------------------------------------------------------------------
  // ----------   Constructors and supporting methods   ----------------

  /**
   *
   */
  public RETRO_PAEX_FR ( )
  {
    super ( );
    this.setName ( "RETRO_PAEX_FR" );

    Debug.println ( Debug.TRACE, "RETRO_PAEX_FR - constructor" );

    this.setDefinitionPath ( "gov/dlf/presentation/RETRO_PAEX_FR.jdp" );
    String definition = ResourceUtil.getResourceText ( this.definitionPath );
    this.setDefinition     ( definition );

    this.setHighLightSelected   ( false );
    this.compressFieldLocations ( false, true );  // Compresses only Y-locations
  }


  /**
   * Overrides ancestor's script
   *
   * @param __app
   */
  public void setApplication ( Application __app )
  {
    this.app = ( SAIC_DMQ_ORA_Application ) __app;
    if ( this.app != null )
    {
      this.setDataManager ( this.app.getDataManager ( ) );
    }

    ICalculator           calculator;
    IBooleanValueProvider txtVisible;
    IBooleanValueProvider groupVisible;
    IObjectValueProvider  valueProvider;
    JDataPanelField       field;
    JDataPanelTextGroup   txtGroup;
    JDataPanelGroup       visGroup;

    this.setArguments ( "G1", new RETRO_PAEX_FR_G1_Arguments ( this ) );

    this.setObjectEvents ( );



  }


  /**
   * Overrides ancestor's method
   *
   * @return
   */
  public RallyApplication getApplication ( )
  {
    return this.app;
  }



  // -------------------------------------------------------------------
  // ----------   Action Sites   ---------------------------------------

  /**
   *
   */
  public void setObjectEvents ( )
  {
    this.registerListener ( "CS", JDataPanelListener.BEFORELEAVE, new JDataPanelListener ( )
    {
      public boolean eventFired ( String eventName )
      {
        app.errorFlag = true; BUSCAR_SERV_REFERIR_RETRO_ADL.exec ( app ); return app.errorFlag;
      }
    } );
    this.registerListener ( "CARE2", JDataPanelListener.BEFORELEAVE, new JDataPanelListener ( )
    {
      public boolean eventFired ( String eventName )
      {
        app.errorFlag = true; COMPUTE_CANT_OTOR_ADL.exec ( app ); return app.errorFlag;
      }
    } );
    this.registerListener ( "PK", JDataPanelListener.BEFOREENTER, new JDataPanelListener ( )
    {
      public boolean eventFired ( String eventName )
      {
        app.errorFlag = true; AUTORIZAR_PAEX_MENU.exec ( app, null ); return app.errorFlag;
      }
    } );
  }
}





/**
 *
 */
class RETRO_PAEX_FR_G1_Arguments extends JDataPanelGroupArguments
{
  /**  */
  protected Form model;
  /**  */
  protected SAIC_DMQ_ORA_Application app = null;

  /**  */
  public RETRO_PAEX_FR_G1_Arguments ( Form form )
  {
    this.model = form;

    this.setArgName ( "PCS" );
    this.setArgName ( "PSSJF" );
    this.setArgName ( "PSSJS" );
    this.setArgName ( "PACCION" );
    this.setArgName ( "PFID" );
  }

  /**  */
  public Object getArgValue ( String argName )
  {
    if ( this.app == null ) this.app = ( SAIC_DMQ_ORA_Application ) this.model.getApplication ( );
    if ( argName == null )
    {
      return null;
    }
    else if ( argName.equals ( "PCS" ) )
    {

    // Mod. by MAC - KPG, Inc. on 4/6/2010
    //Before was this.app.getCOD_SERVICIO_GBL ( ).
    //This was preventing the form from being drawn on the browser due to incorrect
    //parameter value.

      return this.app.getCOD_SERV_GBL ( ); // Global Variable
    }
    else if ( argName.equals ( "PSSJF" ) )
    {
      return this.app.getSS_JEFE_FAMILIA_GBL ( ); // Global Variable
    }
    else if ( argName.equals ( "PSSJS" ) )
    {
      return this.app.getSS_JEFE_SERVICIO_GBL ( ); // Global Variable
    }
    else if ( argName.equals ( "PACCION" ) )
    {
      return this.app.getACCION_GBL ( ); // Global Variable
    }
    else if ( argName.equals ( "PFID" ) )
    {
      return this.app.getFECHA_IDENTIFICADO_GBL ( ); // Global Variable
    }
    return null;
  }
}






