package gov.dlf.logic;


import gov.dlf.external.*;
import gov.dlf.facade.*;
import gov.dlf.presentation.*;


import java.util.*;

//import com.sun.xml.internal.messaging.saaj.soap.impl.DetailImpl;

import net.maintrend.appmanager.*;
import net.maintrend.datamanager.*;
import net.maintrend.interfaces.*;
import net.maintrend.interlink.*;
import net.maintrend.mdi.*;
import net.maintrend.rallyengine.*;
import net.maintrend.util.*;
import net.maintrend.util.format.*;



/**
 * __Comment
 *
 * Generated by Rally-to-Java Convertor. MainTrend Ltd.
 */
public class PSE_2_ADL
     extends ADL
{
  // -------------------------------------------------------------------
  // ----------   Class Attributes   -----------------------------------

  /**  */
  public static boolean staticCall = false;



  // -------------------------------------------------------------------
  // ----------   Instance Attributes   --------------------------------

  /**  */
  public SAIC_DMQ_ORA_Application app;
  /**  */
  public RallyDataManager dm = null;



  // -------------------------------------------------------------------
  // ----------   Instance Condition Attributes   ----------------------

 

  // -------------------------------------------------------------------
  // ----------   Instance Export Attributes   -------------------------

  public double SEGSOC = 0;

  public double NUMSOL = 0;

  public double DIAS = 0;

  public double OPEN_ID = 0;

  public double STATUS_ID = 0;

  public double OPEN2_ID = 0;

  public double STATUS2_ID = 0;

  public double OPEN4_ID = 0;

  public double STATUS4_ID = 0;

  public double OPEN5_ID = 0;

  public double STATUS5_ID = 0;

  public double ZP = 0;

  public double ZP4 = 0;



  public String NOMBRE = null;

  public String OFICINA = null;

  public String DIRECCION = null;

  public String SUB = null;

  public String CRI = null;

  public String ELEG = null;

  public String INELEG = null;

  public String SUB2 = null;

  public String CRI2 = null;

  public String RAZON1 = null;

  public String DIRECTOR = null;

  public Date FECHA = null;

  public String REGION = null;

  public String MUNI = null;

  public String TIPO = null;

  public String DIR1 = null;

  public String DIR2 = null;

  public String CIUDAD = null;

  public String PAIS = null;

  public double PRESUPUESTO_LOC = 0;

  public double PRESUPUESTO_LOC_STAT = 0;

  public DataStore PRESUPUESTO_LOC_DSD = null;

  public DataStore RMO_RO_DSD = null;

  public DataStore CLIENTES2_RO_DSD = null;

  public DataStore SERVICIOS2_DSD = null;



  // -------------------------------------------------------------------
  // ----------   Instance Attributes' Access Methods   ----------------

  
  /**  */
  public static void setNOMBRE  ( RallyApplication __app, Parameter value )
  {
    ( ( PSE_2_ADL ) __app.getADL ( PSE_2_ADL.class ) ).NOMBRE = value.getString ( );
  }  

  
  /**  */
  public static void setSEGSOC  ( RallyApplication __app, Parameter value )
  {
    ( ( PSE_2_ADL ) __app.getADL ( PSE_2_ADL.class ) ).SEGSOC = value.getDouble ( );
  }  

  
  /**  */
  public static void setOFICINA  ( RallyApplication __app, Parameter value )
  {
    ( ( PSE_2_ADL ) __app.getADL ( PSE_2_ADL.class ) ).OFICINA = value.getString ( );
  }  

  
  /**  */
  public static void setDIRECCION  ( RallyApplication __app, Parameter value )
  {
    ( ( PSE_2_ADL ) __app.getADL ( PSE_2_ADL.class ) ).DIRECCION = value.getString ( );
  }  

  
  /**  */
  public static void setNUMSOL  ( RallyApplication __app, Parameter value )
  {
    ( ( PSE_2_ADL ) __app.getADL ( PSE_2_ADL.class ) ).NUMSOL = value.getDouble ( );
  }  

  
  /**  */
  public static void setSUB  ( RallyApplication __app, Parameter value )
  {
    ( ( PSE_2_ADL ) __app.getADL ( PSE_2_ADL.class ) ).SUB = value.getString ( );
  }  

  
  /**  */
  public static void setCRI  ( RallyApplication __app, Parameter value )
  {
    ( ( PSE_2_ADL ) __app.getADL ( PSE_2_ADL.class ) ).CRI = value.getString ( );
  }  

  
  /**  */
  public static void setELEG  ( RallyApplication __app, Parameter value )
  {
    ( ( PSE_2_ADL ) __app.getADL ( PSE_2_ADL.class ) ).ELEG = value.getString ( );
  }  

  
  /**  */
  public static void setINELEG  ( RallyApplication __app, Parameter value )
  {
    ( ( PSE_2_ADL ) __app.getADL ( PSE_2_ADL.class ) ).INELEG = value.getString ( );
  }  

  
  /**  */
  public static void setSUB2  ( RallyApplication __app, Parameter value )
  {
    ( ( PSE_2_ADL ) __app.getADL ( PSE_2_ADL.class ) ).SUB2 = value.getString ( );
  }  

  
  /**  */
  public static void setCRI2  ( RallyApplication __app, Parameter value )
  {
    ( ( PSE_2_ADL ) __app.getADL ( PSE_2_ADL.class ) ).CRI2 = value.getString ( );
  }  

  
  /**  */
  public static void setRAZON1  ( RallyApplication __app, Parameter value )
  {
    ( ( PSE_2_ADL ) __app.getADL ( PSE_2_ADL.class ) ).RAZON1 = value.getString ( );
  }  

  /**  */
  public static void setDIRECTOR  ( RallyApplication __app, Parameter value )
  {
    ( ( PSE_2_ADL ) __app.getADL ( PSE_2_ADL.class ) ).DIRECTOR = value.getString ( );
  }  

  
  /**  */
  public static void setDIAS  ( RallyApplication __app, Parameter value )
  {
    ( ( PSE_2_ADL ) __app.getADL ( PSE_2_ADL.class ) ).DIAS = value.getDouble ( );
  }  

  
  /**  */
  public static void setFECHA  ( RallyApplication __app, Parameter value )
  {
    ( ( PSE_2_ADL ) __app.getADL ( PSE_2_ADL.class ) ).FECHA = value.getDate ( );
  }  

  
  /**  */
  public static void setOPEN_ID  ( RallyApplication __app, Parameter value )
  {
    ( ( PSE_2_ADL ) __app.getADL ( PSE_2_ADL.class ) ).OPEN_ID = value.getDouble ( );
  }  

  
  /**  */
  public static void setSTATUS_ID  ( RallyApplication __app, Parameter value )
  {
    ( ( PSE_2_ADL ) __app.getADL ( PSE_2_ADL.class ) ).STATUS_ID = value.getDouble ( );
  }  

  
  /**  */
  public static void setOPEN2_ID  ( RallyApplication __app, Parameter value )
  {
    ( ( PSE_2_ADL ) __app.getADL ( PSE_2_ADL.class ) ).OPEN2_ID = value.getDouble ( );
  }  

  
  /**  */
  public static void setSTATUS2_ID  ( RallyApplication __app, Parameter value )
  {
    ( ( PSE_2_ADL ) __app.getADL ( PSE_2_ADL.class ) ).STATUS2_ID = value.getDouble ( );
  }  

  
  /**  */
  public static void setOPEN4_ID  ( RallyApplication __app, Parameter value )
  {
    ( ( PSE_2_ADL ) __app.getADL ( PSE_2_ADL.class ) ).OPEN4_ID = value.getDouble ( );
  }  

  
  /**  */
  public static void setSTATUS4_ID  ( RallyApplication __app, Parameter value )
  {
    ( ( PSE_2_ADL ) __app.getADL ( PSE_2_ADL.class ) ).STATUS4_ID = value.getDouble ( );
  }  

  
  /**  */
  public static void setOPEN5_ID  ( RallyApplication __app, Parameter value )
  {
    ( ( PSE_2_ADL ) __app.getADL ( PSE_2_ADL.class ) ).OPEN5_ID = value.getDouble ( );
  }  

  
  /**  */
  public static void setSTATUS5_ID  ( RallyApplication __app, Parameter value )
  {
    ( ( PSE_2_ADL ) __app.getADL ( PSE_2_ADL.class ) ).STATUS5_ID = value.getDouble ( );
  }  

  
  /**  */
  public static void setREGION  ( RallyApplication __app, Parameter value )
  {
    ( ( PSE_2_ADL ) __app.getADL ( PSE_2_ADL.class ) ).REGION = value.getString ( );
  }  

  
  /**  */
  public static void setMUNI  ( RallyApplication __app, Parameter value )
  {
    ( ( PSE_2_ADL ) __app.getADL ( PSE_2_ADL.class ) ).MUNI = value.getString ( );
  }  

  
  /**  */
  public static void setTIPO  ( RallyApplication __app, Parameter value )
  {
    ( ( PSE_2_ADL ) __app.getADL ( PSE_2_ADL.class ) ).TIPO = value.getString ( );
  }  

  
  /**  */
  public static void setDIR1  ( RallyApplication __app, Parameter value )
  {
    ( ( PSE_2_ADL ) __app.getADL ( PSE_2_ADL.class ) ).DIR1 = value.getString ( );
  }  

  
  /**  */
  public static void setDIR2  ( RallyApplication __app, Parameter value )
  {
    ( ( PSE_2_ADL ) __app.getADL ( PSE_2_ADL.class ) ).DIR2 = value.getString ( );
  }  

  
  /**  */
  public static void setZP  ( RallyApplication __app, Parameter value )
  {
    ( ( PSE_2_ADL ) __app.getADL ( PSE_2_ADL.class ) ).ZP = value.getDouble ( );
  }  

  
  /**  */
  public static void setZP4  ( RallyApplication __app, Parameter value )
  {
    ( ( PSE_2_ADL ) __app.getADL ( PSE_2_ADL.class ) ).ZP4 = value.getDouble ( );
  }  

  
  /**  */
  public static void setCIUDAD  ( RallyApplication __app, Parameter value )
  {
    ( ( PSE_2_ADL ) __app.getADL ( PSE_2_ADL.class ) ).CIUDAD = value.getString ( );
  }  

  
  /**  */
  public static void setPAIS  ( RallyApplication __app, Parameter value )
  {
    ( ( PSE_2_ADL ) __app.getADL ( PSE_2_ADL.class ) ).PAIS = value.getString ( );
  }  
    


  /**  */
  public static String getNOMBRE  ( RallyApplication __app )
  {
    return ( ( PSE_2_ADL ) __app.getADL ( PSE_2_ADL.class ) ).NOMBRE;
  }


  /**  */
  public static void setNOMBRE  ( RallyApplication __app, String value )
  {
    ( ( PSE_2_ADL ) __app.getADL ( PSE_2_ADL.class ) ).NOMBRE = value;
  }


  /**  */
  public static void setNOMBRE  ( RallyApplication __app, Object value )
  {
    ( ( PSE_2_ADL ) __app.getADL ( PSE_2_ADL.class ) ).NOMBRE = ( String ) value;
  }



  /**  */
  public static String getOFICINA  ( RallyApplication __app )
  {
    return ( ( PSE_2_ADL ) __app.getADL ( PSE_2_ADL.class ) ).OFICINA;
  }


  /**  */
  public static void setOFICINA  ( RallyApplication __app, String value )
  {
    ( ( PSE_2_ADL ) __app.getADL ( PSE_2_ADL.class ) ).OFICINA = value;
  }


  /**  */
  public static void setOFICINA  ( RallyApplication __app, Object value )
  {
    ( ( PSE_2_ADL ) __app.getADL ( PSE_2_ADL.class ) ).OFICINA = ( String ) value;
  }



  /**  */
  public static String getDIRECCION  ( RallyApplication __app )
  {
    return ( ( PSE_2_ADL ) __app.getADL ( PSE_2_ADL.class ) ).DIRECCION;
  }


  /**  */
  public static void setDIRECCION  ( RallyApplication __app, String value )
  {
    ( ( PSE_2_ADL ) __app.getADL ( PSE_2_ADL.class ) ).DIRECCION = value;
  }


  /**  */
  public static void setDIRECCION  ( RallyApplication __app, Object value )
  {
    ( ( PSE_2_ADL ) __app.getADL ( PSE_2_ADL.class ) ).DIRECCION = ( String ) value;
  }



  /**  */
  public static String getSUB  ( RallyApplication __app )
  {
    return ( ( PSE_2_ADL ) __app.getADL ( PSE_2_ADL.class ) ).SUB;
  }


  /**  */
  public static void setSUB  ( RallyApplication __app, String value )
  {
    ( ( PSE_2_ADL ) __app.getADL ( PSE_2_ADL.class ) ).SUB = value;
  }


  /**  */
  public static void setSUB  ( RallyApplication __app, Object value )
  {
    ( ( PSE_2_ADL ) __app.getADL ( PSE_2_ADL.class ) ).SUB = ( String ) value;
  }



  /**  */
  public static String getCRI  ( RallyApplication __app )
  {
    return ( ( PSE_2_ADL ) __app.getADL ( PSE_2_ADL.class ) ).CRI;
  }


  /**  */
  public static void setCRI  ( RallyApplication __app, String value )
  {
    ( ( PSE_2_ADL ) __app.getADL ( PSE_2_ADL.class ) ).CRI = value;
  }


  /**  */
  public static void setCRI  ( RallyApplication __app, Object value )
  {
    ( ( PSE_2_ADL ) __app.getADL ( PSE_2_ADL.class ) ).CRI = ( String ) value;
  }



  /**  */
  public static String getELEG  ( RallyApplication __app )
  {
    return ( ( PSE_2_ADL ) __app.getADL ( PSE_2_ADL.class ) ).ELEG;
  }


  /**  */
  public static void setELEG  ( RallyApplication __app, String value )
  {
    ( ( PSE_2_ADL ) __app.getADL ( PSE_2_ADL.class ) ).ELEG = value;
  }


  /**  */
  public static void setELEG  ( RallyApplication __app, Object value )
  {
    ( ( PSE_2_ADL ) __app.getADL ( PSE_2_ADL.class ) ).ELEG = ( String ) value;
  }



  /**  */
  public static String getINELEG  ( RallyApplication __app )
  {
    return ( ( PSE_2_ADL ) __app.getADL ( PSE_2_ADL.class ) ).INELEG;
  }


  /**  */
  public static void setINELEG  ( RallyApplication __app, String value )
  {
    ( ( PSE_2_ADL ) __app.getADL ( PSE_2_ADL.class ) ).INELEG = value;
  }


  /**  */
  public static void setINELEG  ( RallyApplication __app, Object value )
  {
    ( ( PSE_2_ADL ) __app.getADL ( PSE_2_ADL.class ) ).INELEG = ( String ) value;
  }



  /**  */
  public static String getSUB2  ( RallyApplication __app )
  {
    return ( ( PSE_2_ADL ) __app.getADL ( PSE_2_ADL.class ) ).SUB2;
  }


  /**  */
  public static void setSUB2  ( RallyApplication __app, String value )
  {
    ( ( PSE_2_ADL ) __app.getADL ( PSE_2_ADL.class ) ).SUB2 = value;
  }


  /**  */
  public static void setSUB2  ( RallyApplication __app, Object value )
  {
    ( ( PSE_2_ADL ) __app.getADL ( PSE_2_ADL.class ) ).SUB2 = ( String ) value;
  }



  /**  */
  public static String getCRI2  ( RallyApplication __app )
  {
    return ( ( PSE_2_ADL ) __app.getADL ( PSE_2_ADL.class ) ).CRI2;
  }


  /**  */
  public static void setCRI2  ( RallyApplication __app, String value )
  {
    ( ( PSE_2_ADL ) __app.getADL ( PSE_2_ADL.class ) ).CRI2 = value;
  }


  /**  */
  public static void setCRI2  ( RallyApplication __app, Object value )
  {
    ( ( PSE_2_ADL ) __app.getADL ( PSE_2_ADL.class ) ).CRI2 = ( String ) value;
  }



  /**  */
  public static String getRAZON1  ( RallyApplication __app )
  {
    return ( ( PSE_2_ADL ) __app.getADL ( PSE_2_ADL.class ) ).RAZON1;
  }


  /**  */
  public static void setRAZON1  ( RallyApplication __app, String value )
  {
    ( ( PSE_2_ADL ) __app.getADL ( PSE_2_ADL.class ) ).RAZON1 = value;
  }


  /**  */
  public static void setRAZON1  ( RallyApplication __app, Object value )
  {
    ( ( PSE_2_ADL ) __app.getADL ( PSE_2_ADL.class ) ).RAZON1 = ( String ) value;
  }

  /**  */
  public static String getDIRECTOR  ( RallyApplication __app )
  {
    return ( ( PSE_2_ADL ) __app.getADL ( PSE_2_ADL.class ) ).DIRECTOR;
  }


  /**  */
  public static void setDIRECTOR  ( RallyApplication __app, String value )
  {
    ( ( PSE_2_ADL ) __app.getADL ( PSE_2_ADL.class ) ).DIRECTOR = value;
  }


  /**  */
  public static void setDIRECTOR  ( RallyApplication __app, Object value )
  {
    ( ( PSE_2_ADL ) __app.getADL ( PSE_2_ADL.class ) ).DIRECTOR = ( String ) value;
  }



  /**  */
  public static Date getFECHA  ( RallyApplication __app )
  {
    return ( ( PSE_2_ADL ) __app.getADL ( PSE_2_ADL.class ) ).FECHA;
  }


  /**  */
  public static void setFECHA  ( RallyApplication __app, Date value )
  {
    ( ( PSE_2_ADL ) __app.getADL ( PSE_2_ADL.class ) ).FECHA = value;
  }


  /**  */
  public static void setFECHA  ( RallyApplication __app, Object value )
  {
    ( ( PSE_2_ADL ) __app.getADL ( PSE_2_ADL.class ) ).FECHA = ( Date ) value;
  }



  /**  */
  public static String getREGION  ( RallyApplication __app )
  {
    return ( ( PSE_2_ADL ) __app.getADL ( PSE_2_ADL.class ) ).REGION;
  }


  /**  */
  public static void setREGION  ( RallyApplication __app, String value )
  {
    ( ( PSE_2_ADL ) __app.getADL ( PSE_2_ADL.class ) ).REGION = value;
  }


  /**  */
  public static void setREGION  ( RallyApplication __app, Object value )
  {
    ( ( PSE_2_ADL ) __app.getADL ( PSE_2_ADL.class ) ).REGION = ( String ) value;
  }



  /**  */
  public static String getMUNI  ( RallyApplication __app )
  {
    return ( ( PSE_2_ADL ) __app.getADL ( PSE_2_ADL.class ) ).MUNI;
  }


  /**  */
  public static void setMUNI  ( RallyApplication __app, String value )
  {
    ( ( PSE_2_ADL ) __app.getADL ( PSE_2_ADL.class ) ).MUNI = value;
  }


  /**  */
  public static void setMUNI  ( RallyApplication __app, Object value )
  {
    ( ( PSE_2_ADL ) __app.getADL ( PSE_2_ADL.class ) ).MUNI = ( String ) value;
  }



  /**  */
  public static String getTIPO  ( RallyApplication __app )
  {
    return ( ( PSE_2_ADL ) __app.getADL ( PSE_2_ADL.class ) ).TIPO;
  }


  /**  */
  public static void setTIPO  ( RallyApplication __app, String value )
  {
    ( ( PSE_2_ADL ) __app.getADL ( PSE_2_ADL.class ) ).TIPO = value;
  }


  /**  */
  public static void setTIPO  ( RallyApplication __app, Object value )
  {
    ( ( PSE_2_ADL ) __app.getADL ( PSE_2_ADL.class ) ).TIPO = ( String ) value;
  }



  /**  */
  public static String getDIR1  ( RallyApplication __app )
  {
    return ( ( PSE_2_ADL ) __app.getADL ( PSE_2_ADL.class ) ).DIR1;
  }


  /**  */
  public static void setDIR1  ( RallyApplication __app, String value )
  {
    ( ( PSE_2_ADL ) __app.getADL ( PSE_2_ADL.class ) ).DIR1 = value;
  }


  /**  */
  public static void setDIR1  ( RallyApplication __app, Object value )
  {
    ( ( PSE_2_ADL ) __app.getADL ( PSE_2_ADL.class ) ).DIR1 = ( String ) value;
  }



  /**  */
  public static String getDIR2  ( RallyApplication __app )
  {
    return ( ( PSE_2_ADL ) __app.getADL ( PSE_2_ADL.class ) ).DIR2;
  }


  /**  */
  public static void setDIR2  ( RallyApplication __app, String value )
  {
    ( ( PSE_2_ADL ) __app.getADL ( PSE_2_ADL.class ) ).DIR2 = value;
  }


  /**  */
  public static void setDIR2  ( RallyApplication __app, Object value )
  {
    ( ( PSE_2_ADL ) __app.getADL ( PSE_2_ADL.class ) ).DIR2 = ( String ) value;
  }



  /**  */
  public static String getCIUDAD  ( RallyApplication __app )
  {
    return ( ( PSE_2_ADL ) __app.getADL ( PSE_2_ADL.class ) ).CIUDAD;
  }


  /**  */
  public static void setCIUDAD  ( RallyApplication __app, String value )
  {
    ( ( PSE_2_ADL ) __app.getADL ( PSE_2_ADL.class ) ).CIUDAD = value;
  }


  /**  */
  public static void setCIUDAD  ( RallyApplication __app, Object value )
  {
    ( ( PSE_2_ADL ) __app.getADL ( PSE_2_ADL.class ) ).CIUDAD = ( String ) value;
  }



  /**  */
  public static String getPAIS  ( RallyApplication __app )
  {
    return ( ( PSE_2_ADL ) __app.getADL ( PSE_2_ADL.class ) ).PAIS;
  }


  /**  */
  public static void setPAIS  ( RallyApplication __app, String value )
  {
    ( ( PSE_2_ADL ) __app.getADL ( PSE_2_ADL.class ) ).PAIS = value;
  }


  /**  */
  public static void setPAIS  ( RallyApplication __app, Object value )
  {
    ( ( PSE_2_ADL ) __app.getADL ( PSE_2_ADL.class ) ).PAIS = ( String ) value;
  }



  /**  */
  public static DataStore getRMO_RO_DSD  ( RallyApplication __app )
  {
    return ( ( PSE_2_ADL ) __app.getADL ( PSE_2_ADL.class ) ).RMO_RO_DSD;
  }


  /**  */
  public static void setRMO_RO_DSD  ( RallyApplication __app, DataStore value )
  {
    ( ( PSE_2_ADL ) __app.getADL ( PSE_2_ADL.class ) ).RMO_RO_DSD = value;
  }


  /**  */
  public static void setRMO_RO_DSD  ( RallyApplication __app, Object value )
  {
    ( ( PSE_2_ADL ) __app.getADL ( PSE_2_ADL.class ) ).RMO_RO_DSD = ( DataStore ) value;
  }



  /**  */
  public static DataStore getCLIENTES2_RO_DSD  ( RallyApplication __app )
  {
    return ( ( PSE_2_ADL ) __app.getADL ( PSE_2_ADL.class ) ).CLIENTES2_RO_DSD;
  }


  /**  */
  public static void setCLIENTES2_RO_DSD  ( RallyApplication __app, DataStore value )
  {
    ( ( PSE_2_ADL ) __app.getADL ( PSE_2_ADL.class ) ).CLIENTES2_RO_DSD = value;
  }


  /**  */
  public static void setCLIENTES2_RO_DSD  ( RallyApplication __app, Object value )
  {
    ( ( PSE_2_ADL ) __app.getADL ( PSE_2_ADL.class ) ).CLIENTES2_RO_DSD = ( DataStore ) value;
  }



  /**  */
  public static DataStore getSERVICIOS2_DSD  ( RallyApplication __app )
  {
    return ( ( PSE_2_ADL ) __app.getADL ( PSE_2_ADL.class ) ).SERVICIOS2_DSD;
  }


  /**  */
  public static void setSERVICIOS2_DSD  ( RallyApplication __app, DataStore value )
  {
    ( ( PSE_2_ADL ) __app.getADL ( PSE_2_ADL.class ) ).SERVICIOS2_DSD = value;
  }


  /**  */
  public static void setSERVICIOS2_DSD  ( RallyApplication __app, Object value )
  {
    ( ( PSE_2_ADL ) __app.getADL ( PSE_2_ADL.class ) ).SERVICIOS2_DSD = ( DataStore ) value;
  }




  /**  */
  public static double getSEGSOC  ( RallyApplication __app )
  {
    return ( ( PSE_2_ADL ) __app.getADL ( PSE_2_ADL.class ) ).SEGSOC;
  }


  /**  */
  public static Double getSEGSOCDouble ( RallyApplication __app )
  {
    return new Double ( ( ( PSE_2_ADL ) __app.getADL ( PSE_2_ADL.class ) ).SEGSOC );
  }


  /**  */
  public static void setSEGSOC  ( RallyApplication __app, double value )
  {
    ( ( PSE_2_ADL ) __app.getADL ( PSE_2_ADL.class ) ).SEGSOC = value;
  }


  /**  */
  public static void setSEGSOC  ( RallyApplication __app, Object value )
  {
    ( ( PSE_2_ADL ) __app.getADL ( PSE_2_ADL.class ) ).SEGSOC = ( ( Double ) value ).doubleValue ( );
  }


  /**  */
  public static double getNUMSOL  ( RallyApplication __app )
  {
    return ( ( PSE_2_ADL ) __app.getADL ( PSE_2_ADL.class ) ).NUMSOL;
  }


  /**  */
  public static Double getNUMSOLDouble ( RallyApplication __app )
  {
    return new Double ( ( ( PSE_2_ADL ) __app.getADL ( PSE_2_ADL.class ) ).NUMSOL );
  }


  /**  */
  public static void setNUMSOL  ( RallyApplication __app, double value )
  {
    ( ( PSE_2_ADL ) __app.getADL ( PSE_2_ADL.class ) ).NUMSOL = value;
  }


  /**  */
  public static void setNUMSOL  ( RallyApplication __app, Object value )
  {
    ( ( PSE_2_ADL ) __app.getADL ( PSE_2_ADL.class ) ).NUMSOL = ( ( Double ) value ).doubleValue ( );
  }


  /**  */
  public static double getDIAS  ( RallyApplication __app )
  {
    return ( ( PSE_2_ADL ) __app.getADL ( PSE_2_ADL.class ) ).DIAS;
  }


  /**  */
  public static Double getDIASDouble ( RallyApplication __app )
  {
    return new Double ( ( ( PSE_2_ADL ) __app.getADL ( PSE_2_ADL.class ) ).DIAS );
  }


  /**  */
  public static void setDIAS  ( RallyApplication __app, double value )
  {
    ( ( PSE_2_ADL ) __app.getADL ( PSE_2_ADL.class ) ).DIAS = value;
  }


  /**  */
  public static void setDIAS  ( RallyApplication __app, Object value )
  {
    ( ( PSE_2_ADL ) __app.getADL ( PSE_2_ADL.class ) ).DIAS = ( ( Double ) value ).doubleValue ( );
  }


  /**  */
  public static double getOPEN_ID  ( RallyApplication __app )
  {
    return ( ( PSE_2_ADL ) __app.getADL ( PSE_2_ADL.class ) ).OPEN_ID;
  }


  /**  */
  public static Double getOPEN_IDDouble ( RallyApplication __app )
  {
    return new Double ( ( ( PSE_2_ADL ) __app.getADL ( PSE_2_ADL.class ) ).OPEN_ID );
  }


  /**  */
  public static void setOPEN_ID  ( RallyApplication __app, double value )
  {
    ( ( PSE_2_ADL ) __app.getADL ( PSE_2_ADL.class ) ).OPEN_ID = value;
  }


  /**  */
  public static void setOPEN_ID  ( RallyApplication __app, Object value )
  {
    ( ( PSE_2_ADL ) __app.getADL ( PSE_2_ADL.class ) ).OPEN_ID = ( ( Double ) value ).doubleValue ( );
  }


  /**  */
  public static double getSTATUS_ID  ( RallyApplication __app )
  {
    return ( ( PSE_2_ADL ) __app.getADL ( PSE_2_ADL.class ) ).STATUS_ID;
  }


  /**  */
  public static Double getSTATUS_IDDouble ( RallyApplication __app )
  {
    return new Double ( ( ( PSE_2_ADL ) __app.getADL ( PSE_2_ADL.class ) ).STATUS_ID );
  }


  /**  */
  public static void setSTATUS_ID  ( RallyApplication __app, double value )
  {
    ( ( PSE_2_ADL ) __app.getADL ( PSE_2_ADL.class ) ).STATUS_ID = value;
  }


  /**  */
  public static void setSTATUS_ID  ( RallyApplication __app, Object value )
  {
    ( ( PSE_2_ADL ) __app.getADL ( PSE_2_ADL.class ) ).STATUS_ID = ( ( Double ) value ).doubleValue ( );
  }


  /**  */
  public static double getOPEN2_ID  ( RallyApplication __app )
  {
    return ( ( PSE_2_ADL ) __app.getADL ( PSE_2_ADL.class ) ).OPEN2_ID;
  }


  /**  */
  public static Double getOPEN2_IDDouble ( RallyApplication __app )
  {
    return new Double ( ( ( PSE_2_ADL ) __app.getADL ( PSE_2_ADL.class ) ).OPEN2_ID );
  }


  /**  */
  public static void setOPEN2_ID  ( RallyApplication __app, double value )
  {
    ( ( PSE_2_ADL ) __app.getADL ( PSE_2_ADL.class ) ).OPEN2_ID = value;
  }


  /**  */
  public static void setOPEN2_ID  ( RallyApplication __app, Object value )
  {
    ( ( PSE_2_ADL ) __app.getADL ( PSE_2_ADL.class ) ).OPEN2_ID = ( ( Double ) value ).doubleValue ( );
  }


  /**  */
  public static double getSTATUS2_ID  ( RallyApplication __app )
  {
    return ( ( PSE_2_ADL ) __app.getADL ( PSE_2_ADL.class ) ).STATUS2_ID;
  }


  /**  */
  public static Double getSTATUS2_IDDouble ( RallyApplication __app )
  {
    return new Double ( ( ( PSE_2_ADL ) __app.getADL ( PSE_2_ADL.class ) ).STATUS2_ID );
  }


  /**  */
  public static void setSTATUS2_ID  ( RallyApplication __app, double value )
  {
    ( ( PSE_2_ADL ) __app.getADL ( PSE_2_ADL.class ) ).STATUS2_ID = value;
  }


  /**  */
  public static void setSTATUS2_ID  ( RallyApplication __app, Object value )
  {
    ( ( PSE_2_ADL ) __app.getADL ( PSE_2_ADL.class ) ).STATUS2_ID = ( ( Double ) value ).doubleValue ( );
  }


  /**  */
  public static double getOPEN4_ID  ( RallyApplication __app )
  {
    return ( ( PSE_2_ADL ) __app.getADL ( PSE_2_ADL.class ) ).OPEN4_ID;
  }


  /**  */
  public static Double getOPEN4_IDDouble ( RallyApplication __app )
  {
    return new Double ( ( ( PSE_2_ADL ) __app.getADL ( PSE_2_ADL.class ) ).OPEN4_ID );
  }


  /**  */
  public static void setOPEN4_ID  ( RallyApplication __app, double value )
  {
    ( ( PSE_2_ADL ) __app.getADL ( PSE_2_ADL.class ) ).OPEN4_ID = value;
  }


  /**  */
  public static void setOPEN4_ID  ( RallyApplication __app, Object value )
  {
    ( ( PSE_2_ADL ) __app.getADL ( PSE_2_ADL.class ) ).OPEN4_ID = ( ( Double ) value ).doubleValue ( );
  }


  /**  */
  public static double getSTATUS4_ID  ( RallyApplication __app )
  {
    return ( ( PSE_2_ADL ) __app.getADL ( PSE_2_ADL.class ) ).STATUS4_ID;
  }


  /**  */
  public static Double getSTATUS4_IDDouble ( RallyApplication __app )
  {
    return new Double ( ( ( PSE_2_ADL ) __app.getADL ( PSE_2_ADL.class ) ).STATUS4_ID );
  }


  /**  */
  public static void setSTATUS4_ID  ( RallyApplication __app, double value )
  {
    ( ( PSE_2_ADL ) __app.getADL ( PSE_2_ADL.class ) ).STATUS4_ID = value;
  }


  /**  */
  public static void setSTATUS4_ID  ( RallyApplication __app, Object value )
  {
    ( ( PSE_2_ADL ) __app.getADL ( PSE_2_ADL.class ) ).STATUS4_ID = ( ( Double ) value ).doubleValue ( );
  }


  /**  */
  public static double getOPEN5_ID  ( RallyApplication __app )
  {
    return ( ( PSE_2_ADL ) __app.getADL ( PSE_2_ADL.class ) ).OPEN5_ID;
  }


  /**  */
  public static Double getOPEN5_IDDouble ( RallyApplication __app )
  {
    return new Double ( ( ( PSE_2_ADL ) __app.getADL ( PSE_2_ADL.class ) ).OPEN5_ID );
  }


  /**  */
  public static void setOPEN5_ID  ( RallyApplication __app, double value )
  {
    ( ( PSE_2_ADL ) __app.getADL ( PSE_2_ADL.class ) ).OPEN5_ID = value;
  }


  /**  */
  public static void setOPEN5_ID  ( RallyApplication __app, Object value )
  {
    ( ( PSE_2_ADL ) __app.getADL ( PSE_2_ADL.class ) ).OPEN5_ID = ( ( Double ) value ).doubleValue ( );
  }


  /**  */
  public static double getSTATUS5_ID  ( RallyApplication __app )
  {
    return ( ( PSE_2_ADL ) __app.getADL ( PSE_2_ADL.class ) ).STATUS5_ID;
  }


  /**  */
  public static Double getSTATUS5_IDDouble ( RallyApplication __app )
  {
    return new Double ( ( ( PSE_2_ADL ) __app.getADL ( PSE_2_ADL.class ) ).STATUS5_ID );
  }


  /**  */
  public static void setSTATUS5_ID  ( RallyApplication __app, double value )
  {
    ( ( PSE_2_ADL ) __app.getADL ( PSE_2_ADL.class ) ).STATUS5_ID = value;
  }


  /**  */
  public static void setSTATUS5_ID  ( RallyApplication __app, Object value )
  {
    ( ( PSE_2_ADL ) __app.getADL ( PSE_2_ADL.class ) ).STATUS5_ID = ( ( Double ) value ).doubleValue ( );
  }


  /**  */
  public static double getZP  ( RallyApplication __app )
  {
    return ( ( PSE_2_ADL ) __app.getADL ( PSE_2_ADL.class ) ).ZP;
  }


  /**  */
  public static Double getZPDouble ( RallyApplication __app )
  {
    return new Double ( ( ( PSE_2_ADL ) __app.getADL ( PSE_2_ADL.class ) ).ZP );
  }


  /**  */
  public static void setZP  ( RallyApplication __app, double value )
  {
    ( ( PSE_2_ADL ) __app.getADL ( PSE_2_ADL.class ) ).ZP = value;
  }


  /**  */
  public static void setZP  ( RallyApplication __app, Object value )
  {
    ( ( PSE_2_ADL ) __app.getADL ( PSE_2_ADL.class ) ).ZP = ( ( Double ) value ).doubleValue ( );
  }


  /**  */
  public static double getZP4  ( RallyApplication __app )
  {
    return ( ( PSE_2_ADL ) __app.getADL ( PSE_2_ADL.class ) ).ZP4;
  }


  /**  */
  public static Double getZP4Double ( RallyApplication __app )
  {
    return new Double ( ( ( PSE_2_ADL ) __app.getADL ( PSE_2_ADL.class ) ).ZP4 );
  }


  /**  */
  public static void setZP4  ( RallyApplication __app, double value )
  {
    ( ( PSE_2_ADL ) __app.getADL ( PSE_2_ADL.class ) ).ZP4 = value;
  }


  /**  */
  public static void setZP4  ( RallyApplication __app, Object value )
  {
    ( ( PSE_2_ADL ) __app.getADL ( PSE_2_ADL.class ) ).ZP4 = ( ( Double ) value ).doubleValue ( );
  }



  // -------------------------------------------------------------------
  // ----------   Methods   --------------------------------------------

  /**
   * 
   * @param __app
   * @return
   */
  public static PSE_2_ADL get ( RallyApplication __app )
  {
    PSE_2_ADL adl = new PSE_2_ADL ( );
    __app.register ( adl, "PSE_2_ADL" );
    __app.setADL ( PSE_2_ADL.class, adl ); 
    adl.setApplication ( __app );
    return adl;
  }


  /**
   *
   * @param __app
   * @param ps
   *
   * @return
   */
  public static void exec ( RallyApplication __app, ParameterSet ps )
  {
    PSE_2_ADL.get ( __app ).process ( ps );
  }


  /**
   *
   * @param __app
   *
   * @return
   */
  public static void exec ( RallyApplication __app )
  {
    ParameterSet ps = null;
    PSE_2_ADL.exec ( __app, ps );
  }


  /**
   * Overrides the ancestor's method
   * 
   * @param __app
   */
  public void setApplication ( RallyApplication __app )
  {
    this.app = ( SAIC_DMQ_ORA_Application ) __app;
    if ( this.app != null )
    {
      this.dm = ( RallyDataManager ) this.app.getDataManager ( );
    }
  }


  /**
   * Overrides the ancestor's method
   * 
   * @param parms
   */
  public void execute ( ParameterSet parms )
  {
    this.process ( parms );
  }




  /**
   *
   */
  protected void doReturn ( )
  {
    this.unregister ( );
  }


  /**
   *
   */
  public void unregister ( )
  {
    this.app.unregister ( this );
    IRegisteredObject rObj = this.app.get ( "PSE_2_ADL" );
    if ( rObj != null && rObj instanceof PSE_2_ADL )
    {
      this.app.setADL ( PSE_2_ADL.class, ( PSE_2_ADL ) rObj );
    }
  }


  /**
   * Overrides the ancestor's method
   * 
   * @param ps
   */
  protected void process ( ParameterSet ps )
  {
    Debug.println ( Debug.TRACE, "PSE_2_ADL Step " + this.currentStep );
    super.process ( ps );
    switch ( this.currentStep ) 
    {
      case 0:  { this.currentStep ++; this.step0 ( this.keyParms ); break; }
      case 1:  { this.currentStep ++; this.step1 ( this.keyParms ); break; }
      case 2:  { this.currentStep ++; this.step2 ( this.keyParms ); break; }
      case 3:  { this.currentStep ++; this.step3 ( this.keyParms ); break; }
      default: 
      { 
        this.currentStep = 0;
        Debug.println ( Debug.TRACE, "PSE_2_ADL ended" );
        this.unregister ( );
        break;
      }
    }
    if ( this.currentStep > 0 ) this.app.goOn ( );
  }



  /**
   *
   */
  protected void step0 ( ParameterSet ps )
  {

    this.app.form ( "PSE_2_FR" ).setItem ( "SUB", " "  );
    this.app.form ( "PSE_2_FR" ).setItem ( "SUB2", " "  );
    this.app.form ( "PSE_2_FR" ).setItem ( "CRI", " "  );
    this.app.form ( "PSE_2_FR" ).setItem ( "CRI2", " "  );
    this.app.form ( "PSE_2_FR" ).setItem ( "OFICINA"," ");
    this.app.form ( "PSE_2_FR" ).setItem ( "RAZON1", " "  );
    this.app.form ( "PSE_2_FR" ).setItem ( "DIRECCION", " "  );
    this.app.form ( "PSE_2_FR" ).setItem ( "ELEG", " "  );
    this.app.form ( "PSE_2_FR" ).setItem ( "INELEG", " "  );
    this.app.form ( "PSE_2_FR" ).setItem ( "NOMBRE", " "  );
    this.app.SSN_GBL = this.app.SS_JEFE_GBL;
    this.app.form ( "PSE_2_FR" ).setItem ( "SEGSOC", this.app.SSN_GBL  );
    this.app.form ( "PSE_2_FR" ).setItem ( "PSE_SS", this.app.SSN_GBL  );
    RMO_RO_DSD = this.dm.create ( "RMO_RO_DSD" );
    OPEN5_ID = RMO_RO_DSD.getId ( );
    STATUS5_ID = RallyDataStoreException.getDefault ( );
    CLIENTES2_RO_DSD = this.dm.create ( "CLIENTES2_RO_DSD" );
    OPEN_ID = CLIENTES2_RO_DSD.getId ( );
    STATUS_ID = RallyDataStoreException.getDefault ( );

    STATUS_ID  = this.dm.reset ( OPEN_ID );

    this.dm.setField ( this.dm.get ( "CLIENTES2_RO_DSD" ), "SEGURO_SOCIAL_CLIENTE", this.app.SS_JEFE_GBL );
    this.dm.setField ( this.dm.get ( "CLIENTES2_RO_DSD" ), "RMO_OFICINA", this.app.RMO_GBL );

    STATUS_ID  = this.dm.limitQueryFromBuffer ( OPEN_ID );
    STATUS_ID  = this.dm.retrieve ( OPEN_ID );

    if ( ! Compare.equals ( STATUS_ID, 0 ) ) 
    {
      this.app.setError ( 0, STATUS_ID );
      this.doReturn ( );
      return; 
    }

    STATUS_ID  = this.dm.firstRow ( OPEN_ID );

    if ( ! Compare.equals ( STATUS_ID, 0 ) ) 
    {
      this.app.setError ( 1, STATUS_ID );
      this.doReturn ( );
      return; 
    }
    
//    STATUS5_ID = this.dm.reset ( OPEN5_ID );
//    
//    this.dm.setField ( this.dm.get ( "RMO_RO_DSD" ), "RMO_OFICINA", this.app.RMO_GBL );
//   
//    STATUS5_ID  = this.dm.limitQueryFromBuffer ( OPEN5_ID );  
//    STATUS5_ID  = this.dm.retrieve ( OPEN5_ID );
//    
//    if ( ! Compare.equals ( STATUS5_ID, 0 ) ) 
//    {
//      this.app.setError ( 0, STATUS5_ID );
//      this.doReturn ( );
//      return; 
//    }
//    
//    STATUS5_ID  = this.dm.firstRow ( OPEN5_ID );
    
   // this.app.form ( "PSE_2_FR" ).setItem ( "OFICINA",  this.dm.getFieldString(  this.dm.get ( "RMO_RO_DSD" ), "DSC_OFICINA" )  );
    
    this.callParms.clear ( );
    this.callParms.set ( this.dm.getFieldDouble ( this.dm.get ( "CLIENTES2_RO_DSD" ), "RMO_OFICINA" )  );
    this.callParms.set ( REGION  );
    this.callParms.set ( MUNI  );
    this.callParms.set ( OFICINA  );
    GET_RMO_INFO_ADL.exec ( this.app, this.callParms );
    return;

  }


  /**
   *
   */
  protected void step1 ( ParameterSet ps )
  {
    this.callParms.reset ( );
    this.dm.setField ( this.dm.get ( "CLIENTES2_RO_DSD" ), "RMO_OFICINA", this.callParms.getDouble ( ) );
    REGION  = this.callParms.getString ( );
    MUNI  = this.callParms.getString ( );
    OFICINA  = this.callParms.getString ( );

    this.app.form ( "PSE_2_FR" ).setItem ( "OFICINA", OFICINA  );
    this.app.form ( "PSE_2_FR" ).setItem ( "NOMBRE", this.dm.getFieldString ( this.dm.get ( "CLIENTES2_RO_DSD" ), "DSC_NOMBRE" ) + " " + this.dm.getFieldString ( this.dm.get ( "CLIENTES2_RO_DSD" ), "DSC_INICIAL" ) + " " + this.dm.getFieldString ( this.dm.get ( "CLIENTES2_RO_DSD" ), "DSC_APELLIDO_PATERNO" ) + " " + this.dm.getFieldString ( this.dm.get ( "CLIENTES2_RO_DSD" ), "DSC_APELLIDO_MATERNO" )  );
    STATUS_ID  = this.dm.dbClose ( OPEN_ID );

    SERVICIOS2_DSD = this.dm.create ( "SERVICIOS2_DSD" );
    OPEN2_ID = SERVICIOS2_DSD.getId ( );
    STATUS2_ID = RallyDataStoreException.getDefault ( );

    STATUS2_ID  = this.dm.reset ( OPEN2_ID );

    this.dm.setField ( this.dm.get ( "SERVICIOS2_DSD" ), "SEGURO_SOCIAL_JEFE_FAM", this.app.SS_JEFE_GBL );
    this.dm.setField ( this.dm.get ( "SERVICIOS2_DSD" ), "SEGURO_SOCIAL_JEFE_SERV", this.app.SS_SERV_GBL );
    this.dm.setField ( this.dm.get ( "SERVICIOS2_DSD" ), "COD_SERVICIO", this.app.COD_SERV_GBL );
    this.dm.setField ( this.dm.get ( "SERVICIOS2_DSD" ), "RMO_OFICINA", this.app.RMO_GBL );

    STATUS2_ID  = this.dm.limitQueryFromBuffer ( OPEN2_ID );
    STATUS2_ID  = this.dm.retrieve ( OPEN2_ID );

    if ( ! Compare.equals ( STATUS2_ID, 0 ) ) 
    {
      this.app.setError ( 2, STATUS2_ID );
      this.doReturn ( );
      return; 
    }

    STATUS2_ID  = this.dm.firstRow ( OPEN2_ID );

    if ( ! Compare.equals ( STATUS2_ID, 0 ) ) 
    {
      this.app.setError ( 3, STATUS_ID );
      this.doReturn ( );
      return; 
    }
    String status = DETERMINAR_ELEGIBILIDAD_LIHEAP.getSERVICIO_STATUS(this.app);
    if (Compare.equals(status, "PENDREVI") || Compare.equals(status, "PENDCERT"))
    {
      this.app.form ( "PSE_2_FR" ).setItem ( "ELEG", "X"  );
      this.app.form ( "PSE_2_FR" ).setItem ( "INELEG", " "  );
      this.app.form ( "PSE_2_FR" ).setItem ( "RAZON1", " "  );
    }
    else
    {
      this.app.form ( "PSE_2_FR" ).setItem ( "ELEG", " "  );
      this.app.form ( "PSE_2_FR" ).setItem ( "INELEG", "X"  );
      this.app.form ( "PSE_2_FR" ).setItem ( "RAZON1",DETERMINAR_ELEGIBILIDAD_LIHEAP.getRAZON(this.app ) );
    }
    if ( Compare.equals ( this.app.COD_SERV_GBL, "ATSE" ) ) 
    {
      this.app.form ( "PSE_2_FR" ).setItem ( "SUB", "X"  );
      if (Compare.equals(status, "PENDREVI") || Compare.equals(status, "PENDCERT"))
      {
        this.app.form ( "PSE_2_FR" ).setItem ( "SUB2", "X"  );
      }
    }
    if ( Compare.equals ( this.app.COD_SERV_GBL, "ATCR" ) ) 
    {
      this.app.form ( "PSE_2_FR" ).setItem ( "CRI", "X"  );
      if (Compare.equals(status, "PENDREVI") || Compare.equals(status, "PENDCERT"))
      {
        this.app.form ( "PSE_2_FR" ).setItem ( "CRI2", "X"  );
      }
    }
    this.dm.setField ( this.dm.get ( "SERVICIOS2_DSD" ), "FCH_DECISION", TruncService.trunc ( this.app.SYSTEM_DATE, "DDD" )  );
    this.dm.setField ( this.dm.get ( "SERVICIOS2_DSD" ), "FCH_TRANS", TruncService.trunc ( this.app.SYSTEM_DATE, "DDD" )  );
    this.dm.setField ( this.dm.get ( "SERVICIOS2_DSD" ), "ID_TECNICO_DETER_ELEGIBILIDAD", this.app.ID_TECNICO_GBL );
    this.dm.setField ( this.dm.get ( "SERVICIOS2_DSD" ), "COD_STATUS_SERVICIO",DETERMINAR_ELEGIBILIDAD_LIHEAP.getSERVICIO_STATUS(this.app));
    
    STATUS2_ID = this.dm.update(OPEN2_ID);
    STATUS2_ID  = this.dm.dbClose ( OPEN2_ID );

    TIPO = "POST";

    this.callParms.clear ( );
    this.callParms.set ( this.app.SS_JEFE_GBL  );
    this.callParms.set ( TIPO  );
    this.callParms.set ( DIR1  );
    this.callParms.set ( DIR2  );
    this.callParms.set ( ZP  );
    this.callParms.set ( ZP4  );
    this.callParms.set ( CIUDAD  );
    this.callParms.set ( PAIS  );
    DIRECCION_ADL.exec ( this.app, this.callParms );
    return;

  }


  /**
   *
   */
  protected void step2 ( ParameterSet ps )
  {
    this.callParms.reset ( );
    this.app.SS_JEFE_GBL  = this.callParms.getDouble ( );
    TIPO  = this.callParms.getString ( );
    DIR1  = this.callParms.getString ( );
    DIR2  = this.callParms.getString ( );
    ZP  = this.callParms.getDouble ( );
    ZP4  = this.callParms.getDouble ( );
    CIUDAD  = this.callParms.getString ( );
    PAIS  = this.callParms.getString ( );

    this.app.form ( "PSE_2_FR" ).setItem ( "DIRECCION", DIR1 + "  " + DIR2 + "  " + "00" + StringService.toStringValue  ( ZP ) + "-" + StringService.toStringValue  ( ZP4 )  );

  }
  protected void step3 (ParameterSet ps)
  {
	  if ( Compare.equals ( this.app.DETERMINACION_FINAL_GBL, "S" ) ) 
	    {
	      PRESUPUESTO_LOC_DSD = this.dm.create ( "PRESUPUESTO_LOC_DSD" );
	      PRESUPUESTO_LOC = PRESUPUESTO_LOC_DSD.getId ( );
	      PRESUPUESTO_LOC_STAT = RallyDataStoreException.getDefault ( );

	      PRESUPUESTO_LOC_STAT  = this.dm.reset ( PRESUPUESTO_LOC );

	      this.dm.setField ( this.dm.get ( "PRESUPUESTO_LOC_DSD" ), "SEGURO_SOCIAL_JEFE_SERV", this.app.SS_SERV_GBL );
	      this.dm.setField ( this.dm.get ( "PRESUPUESTO_LOC_DSD" ), "COD_SERVICIO", this.app.COD_SERV_GBL );

	      PRESUPUESTO_LOC_STAT  = this.dm.limitQueryFromBuffer ( PRESUPUESTO_LOC );
	      PRESUPUESTO_LOC_STAT  = this.dm.retrieve ( PRESUPUESTO_LOC );

	      PRESUPUESTO_LOC_STAT  = this.dm.firstRow ( PRESUPUESTO_LOC );

	      boolean tempBool = this.dm.getLogEnabled ( );
	      
	      if ( Compare.equals ( PRESUPUESTO_LOC_STAT, 0 ) ) 
	      {
	        this.dm.setField ( this.dm.get ( "PRESUPUESTO_LOC_DSD" ), "MAYORES_60", DETERMINAR_ELEGIBILIDAD_LIHEAP.getANCIANO_COUNT ( this.app ) );
	        this.dm.setField ( this.dm.get ( "PRESUPUESTO_LOC_DSD" ), "INCAPACITADOS", DETERMINAR_ELEGIBILIDAD_LIHEAP.getINCAPACITADO_COUNT ( this.app ) );
	        this.dm.setField ( this.dm.get ( "PRESUPUESTO_LOC_DSD" ), "MIEMBROS", DETERMINAR_ELEGIBILIDAD_LIHEAP.getMIEMBROS_FAMILIA_COUNT( ( this.app ) ));
	        this.dm.setField ( this.dm.get ( "PRESUPUESTO_LOC_DSD" ), "RECURSOS", MathService.plus ( DETERMINAR_ELEGIBILIDAD_LIHEAP.getRECURSOS_ACUM ( this.app ), DETERMINAR_ELEGIBILIDAD_LIHEAP.getRECURSOS_LIQUIDOS ( this.app )  ) );
	        this.dm.setField ( this.dm.get ( "PRESUPUESTO_LOC_DSD" ), "RMO_OFICINA", this.app.RMO_GBL );
	        this.dm.setField ( this.dm.get ( "PRESUPUESTO_LOC_DSD" ), "SEGURO_SOCIAL_JEFE_FAM", this.app.SS_JEFE_GBL );
	        this.dm.setField ( this.dm.get ( "PRESUPUESTO_LOC_DSD" ), "RMO_OFICINA", this.app.RMO_GBL );
	        this.dm.setField ( this.dm.get ( "PRESUPUESTO_LOC_DSD" ), "MENORES", DETERMINAR_ELEGIBILIDAD_LIHEAP.getMENOR_COUNT ( this.app ) );

	        this.dm.setLogEnabled ( false );
	        PRESUPUESTO_LOC_STAT  = this.dm.update ( PRESUPUESTO_LOC );
	        this.dm.setLogEnabled ( tempBool );
	      }
	      else
	      {
	        this.dm.setField ( this.dm.get ( "PRESUPUESTO_LOC_DSD" ), "SEGURO_SOCIAL_JEFE_FAM", this.app.SS_JEFE_GBL );
	        this.dm.setField ( this.dm.get ( "PRESUPUESTO_LOC_DSD" ), "SEGURO_SOCIAL_JEFE_SERV", this.app.SS_SERV_GBL );
	        this.dm.setField ( this.dm.get ( "PRESUPUESTO_LOC_DSD" ), "COD_SERVICIO", this.app.COD_SERV_GBL );
	        this.dm.setField ( this.dm.get ( "PRESUPUESTO_LOC_DSD" ), "RMO_OFICINA", this.app.RMO_GBL );
	        this.dm.setField ( this.dm.get ( "PRESUPUESTO_LOC_DSD" ), "MAYORES_60", DETERMINAR_ELEGIBILIDAD_LIHEAP.getANCIANO_COUNT ( this.app ) );
	        this.dm.setField ( this.dm.get ( "PRESUPUESTO_LOC_DSD" ), "INCAPACITADOS", DETERMINAR_ELEGIBILIDAD_LIHEAP.getINCAPACITADO_COUNT ( this.app ) );
	        this.dm.setField ( this.dm.get ( "PRESUPUESTO_LOC_DSD" ), "MIEMBROS", DETERMINAR_ELEGIBILIDAD_LIHEAP.getMIEMBROS_FAMILIA_COUNT( ( this.app ) ));
	        this.dm.setField ( this.dm.get ( "PRESUPUESTO_LOC_DSD" ), "RECURSOS", MathService.plus ( DETERMINAR_ELEGIBILIDAD_LIHEAP.getRECURSOS_ACUM ( this.app ), DETERMINAR_ELEGIBILIDAD_LIHEAP.getRECURSOS_LIQUIDOS ( this.app )  ) );
	        this.dm.setField ( this.dm.get ( "PRESUPUESTO_LOC_DSD" ), "MENORES", DETERMINAR_ELEGIBILIDAD_LIHEAP.getMENOR_COUNT ( this.app ) );
	        
	        this.dm.setLogEnabled ( false );
	        PRESUPUESTO_LOC_STAT  = this.dm.insertRow ( PRESUPUESTO_LOC );
	        this.dm.setLogEnabled ( tempBool );
	      }
	      if ( ! Compare.equals ( PRESUPUESTO_LOC_STAT, 0 ) ) 
	      {
	        this.app.setError ( 0, PRESUPUESTO_LOC_STAT );
	      }

	      PRESUPUESTO_LOC_STAT  = this.dm.dbCommit ( );
	      PRESUPUESTO_LOC_STAT  = this.dm.dbClose ( PRESUPUESTO_LOC );

	    }
	  return;
  }
}



/* ---------------------------------------------------------------------


     
procedure pSE_2_ADL;
{ Las variables que se definen a continuacion estan conforme a las columnas}
{ presentadas en la forma }
VAR     NOMBRE          :       char export;
        SEGSOC          :       number export;
        OFICINA         :       char export;
        DIRECCION       :       char   export;
        NUMSOL          :       number export;
        SUB             :       char   export;
        CRI             :       char   export;
        ELEG            :       char   export;
        INELEG          :       char   export;
        SUB2            :       char   export;
        CRI2            :       char   export;
        RAZON1          :       char   export;
        RAZON2          :       char   export;
        RAZON3          :       char   export;
        DIRECTOR        :       char   export;
        DIAS            :       number export;
        FECHA           :       date   export;
        open_id         :       number(9,0);
        status_id       :       number(9,0);
        open2_id        :       number(9,0);
        status2_id      :       number(9,0);
        open4_id        :       number(9,0) EXPORT;
        status4_id      :       number(9,0) EXPORT;
        open5_id        :       number(9,0) EXPORT;
        status5_id      :       number(9,0) EXPORT;
        region          :       char(1);
        muni            :       char(1);
        tipo            :       char(4);
        dir1            :       char(25);
        dir2            :       char(25);
        zp              :       number;
        zp4             :       number;
        ciudad          :       char(20);
        pais            :       char(20);
begin
SET_TRACE();
PSE_2_FR.SUB := ' ';
PSE_2_FR.SUB2 := ' ';
PSE_2_FR.CRI :=' ';
PSE_2_FR.CRI2 := ' ';
pse_2_fr.razon1:= ' ';
pse_2_fr.razon2:=' ';
pse_2_fr.razon3:=' ';
pse_2_fr.direccion:=' ';
pse_2_fr.oficina:=' ';
PSE_2_FR.ELEG:=' ';
PSE_2_FR.INELEG:=' ';
PSE_2_FR.NOMBRE:=' ';
{}
{Es necesario inicializar las siguientes variables globales}
{para el cual se desea imprimir este reporte: }
{       ssn_gbl = cliente deseado}
{       cod_servicio_gbl = servicio deseado}
ssn_gbl := ss_jefe_gbl;
pse_2_fr.segsoc := ssn_gbl;
PSE_2_FR.PSE_SS := SSN_GBL;
DB_OPEN(RMO_RO_DSD,OPEN5_ID,STATUS5_ID);
db_open(CLIENTES2_RO_DSD,open_id,status_id);
db_reset(open_id,status_id);
CLIENTES2_RO_DSD.seguro_social_cliente := ss_jefe_gbl;
CLIENTES2_RO_DSD.RMO_OFICINA:=RMO_GBL;
db_query(open_id,status_id);
IF status_id <>0 THEN
begin
        ERROR(STATUS_ID);
        RETURN;
END;
{ENDIF}

        db_get_first(open_id,status_id);
        IF status_id <>0 THEN
        begin
                ERROR(STATUS_ID);
                RETURN;
        END;
        {ENDIF}

        call get_rmo_info_adl(CLIENTES2_RO_DSD.rmo_cod,region,muni,oficina);
                pse_2_fr.oficina:=oficina;
                pse_2_fr.nombre:=CLIENTES2_RO_DSD.dsc_nombre || ' ' ||
                           CLIENTES2_RO_DSD.dsc_inicial || ' ' ||
                           CLIENTES2_RO_DSD.dsc_apellido_paterno || ' ' ||
                           CLIENTES2_RO_DSD.dsc_apellido_materno;
                db_close(open_id,status_id);
{ahora, buscaremos el servicio}
                db_open(SERVICIOS2_DSD,open2_id,status2_id);
                db_reset(open2_id,status2_id);
                SERVICIOS2_DSD.seguro_social_jefe_fam := ss_jefe_gbl;
                SERVICIOS2_DSD.seguro_social_jefe_serv := ss_serv_gbl;
                SERVICIOS2_DSD.cod_servicio := cod_serv_gbl;
                SERVICIOS2_DSD.RMO_OFICINA:=RMO_GBL;
                db_query(open2_id,status2_id);
                IF status2_id <>0 THEN
                begin
                        ERROR(STATUS2_ID);
                        RETURN;
                END;
                {ENDIF}

                db_get_first(open2_id,status2_id);
                IF status2_id <>0 THEN
                Begin
                        ERROR(STATUS_ID);
                        RETURN;
                END;
                {ENDIF}
                
                        if SERVICIOS2_DSD.accion_tomada_auto <> '' then
                                begin
                                        pse_2_fr.eleg := 'X';
                                        pse_2_fr.ineleg := ' ';                 
        
                                                pse_2_fr.razon1:= ' ';
                                                pse_2_fr.razon2:=' ';
                                                pse_2_fr.razon3:=' ';
                                        end;
                                else
                                        begin
                                                pse_2_fr.eleg := ' ';
                                                pse_2_fr.ineleg:= 'X';
                                                pse_2_fr.razon1:= ' ';
                                                pse_2_fr.razon2:=' ';
                                                pse_2_fr.razon3:=' ';
                                        end;
                                {endif}
                                if (cod_serv_gbl = 'ATSE')
                                THEN BEGIN
                                       PSE_2_FR.SUB := 'X';
                                       IF (SERVICIOS2_DSD.accion_tomada_auto <> 
'')
                                       THEN     
                                           PSE_2_FR.SUB2 := 'X';
                                     END;
                                if (cod_serv_gbl = 'ATCR')
                                THEN BEGIN
                                       PSE_2_FR.CRI := 'X';
                                       IF (SERVICIOS2_DSD.accion_tomada_auto <> 
'')
                                       THEN PSE_2_FR.CRI2 := 'X';
                                     END;
                        db_close(open2_id,status2_id);
tipo := 'POST';
call direccion_adl(ss_jefe_gbl,tipo,dir1,dir2,zp,zp4,ciudad,pais);
{concatenar la direccion aqui}
pse_2_fr.direccion := dir1 || '  ' || dir2 ||'  '||'00'|| to_char(zp) || '-' || 
to_char(zp4);


SET_NOTRACE();
end;
    



--------------------------------------------------------------------- */
