
package gov.dlf.webservice;

import java.math.BigDecimal;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.4-b01-
 * Generated source version: 2.1
 * 
 */
@WebService(name = "ACSISecuritySoap", targetNamespace = "http://acsi.familia.pr/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ACSISecuritySoap {


    /**
     * Get the web server version number.
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "WebServiceVersion", action = "http://acsi.familia.pr/WebServiceVersion")
    @WebResult(name = "WebServiceVersionResult", targetNamespace = "http://acsi.familia.pr/")
    @RequestWrapper(localName = "WebServiceVersion", targetNamespace = "http://acsi.familia.pr/", className = "gov.dlf.webservice.WebServiceVersion")
    @ResponseWrapper(localName = "WebServiceVersionResponse", targetNamespace = "http://acsi.familia.pr/", className = "gov.dlf.webservice.WebServiceVersionResponse")
    public String webServiceVersion();

    /**
     * Validate the user and token combination. Returns true or false.
     * 
     * @param strUser
     * @param strToken
     * @return
     *     returns boolean
     */
    @WebMethod(operationName = "ValidateTokenUser", action = "http://acsi.familia.pr/ValidateTokenUser")
    @WebResult(name = "ValidateTokenUserResult", targetNamespace = "http://acsi.familia.pr/")
    @RequestWrapper(localName = "ValidateTokenUser", targetNamespace = "http://acsi.familia.pr/", className = "gov.dlf.webservice.ValidateTokenUser")
    @ResponseWrapper(localName = "ValidateTokenUserResponse", targetNamespace = "http://acsi.familia.pr/", className = "gov.dlf.webservice.ValidateTokenUserResponse")
    public boolean validateTokenUser(
        @WebParam(name = "strUser", targetNamespace = "http://acsi.familia.pr/")
        String strUser,
        @WebParam(name = "strToken", targetNamespace = "http://acsi.familia.pr/")
        String strToken);

    /**
     * Generate a User new User token
     * 
     * @param strCodigoUsuario
     * @param intUsuarioID
     * @param strNombreAplicacion
     * @param intAplicacionID
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "GenerateTokenUser", action = "http://acsi.familia.pr/GenerateTokenUser")
    @WebResult(name = "GenerateTokenUserResult", targetNamespace = "http://acsi.familia.pr/")
    @RequestWrapper(localName = "GenerateTokenUser", targetNamespace = "http://acsi.familia.pr/", className = "gov.dlf.webservice.GenerateTokenUser")
    @ResponseWrapper(localName = "GenerateTokenUserResponse", targetNamespace = "http://acsi.familia.pr/", className = "gov.dlf.webservice.GenerateTokenUserResponse")
    public String generateTokenUser(
        @WebParam(name = "strNombreAplicacion", targetNamespace = "http://acsi.familia.pr/")
        String strNombreAplicacion,
        @WebParam(name = "strCodigoUsuario", targetNamespace = "http://acsi.familia.pr/")
        String strCodigoUsuario,
        @WebParam(name = "intUsuarioID", targetNamespace = "http://acsi.familia.pr/")
        BigDecimal intUsuarioID,
        @WebParam(name = "intAplicacionID", targetNamespace = "http://acsi.familia.pr/")
        BigDecimal intAplicacionID);

}
