package gov.dlf.logic;


import gov.dlf.facade.*;
import net.maintrend.appmanager.*;
import net.maintrend.interlink.*;
import net.maintrend.interfaces.*;
import net.maintrend.rallyengine.*;
import net.maintrend.util.*;



/**
 * 
 *
 * Generated by Rally-to-Java Convertor. MainTrend Ltd.
 */
public class CITAS_PPKT0 
  implements IRegisteredObject 
{
  // -------------------------------------------------------------------
  // ----------   Instance Attributes   --------------------------------

  /**  */
  public ParameterSet parms;
  /**  */
  public SAIC_DMQ_ORA_Application app;



  // -------------------------------------------------------------------
  // ----------   Constructor   ----------------------------------------

  /**
   *
   */
  public CITAS_PPKT0 ( )
  {
    this.parms = new ParameterSet ( );
  }



  // -------------------------------------------------------------------
  // ----------   Class Methods   --------------------------------------

  /**
   *
   */
  public static CITAS_PPKT0 get ( RallyApplication __app )
  {
    CITAS_PPKT0 pp = ( CITAS_PPKT0 ) __app.getNewInstance ( "CITAS_PPKT0" );
    return pp;
  }


  /**
   * 
   * @param __app
   * @return
   */
  public static boolean exec ( RallyApplication __app )
  {
    CITAS_PPKT0 pp = ( CITAS_PPKT0 ) __app.getNewInstance ( "CITAS_PPKT0" );
    pp.execute ( __app, null );
    return true;
  }


  /**
   * 
   * @param __app
   * @return
   */
  public static boolean exec ( RallyApplication __app, ParameterSet ps )
  {
    return CITAS_PPKT0.exec ( __app );
  }



  // -------------------------------------------------------------------
  // ----------   IRegisteredObject implementation   -------------------

  /**
   * 
   * @param rApp
   */
  @Override
public void setApplication ( Application rApp )
  {
    if ( rApp != null ) this.app = ( SAIC_DMQ_ORA_Application ) rApp;
  }


  /**
   * 
   * @return
   */
  @Override
public boolean isSelfClosing ( )
  {
    return true;
  }


  /**
   *
   */
  @Override
public ParameterSet getParameters ( )
  {
    return this.parms;
  }


  /**
   *
   */
  @Override
public void setParameters ( ParameterSet value )
  {
    this.parms = value;
  }


  /**
   *
   */
  @Override
public void execute ( ParameterSet ps )
  {
    Debug.println ( Debug.TRACE, "CITAS_PPKT0" );
    this.prepareParms ( );
    HASTA_ADL.exec ( this.app, this.parms );
    this.returnParms  ( );
    this.app.unregister ( this, false );
  }


  /**
   * Occurs just after removing this object from the application registry
   */
  @Override
public void halt ( )
  {
  }



  // -------------------------------------------------------------------
  // ----------   Methods   --------------------------------------------

  /**
   *
   */
  protected void returnParms ( )
  {
    this.app.form ( "CALENDARIO_LF_FR" ).setValue ( "FCH_ACTIVIDAD_HORA_MIN_CONTAC0", this.parms.getDate ( 0 ) );
    this.app.form ( "CALENDARIO_LF_FR" ).setValue ( "DURACION_HORA_MIN_CONTACTO", this.parms.getDate ( 1 ) );
    this.app.form ( "CALENDARIO_LF_FR" ).setValue ( "DUMMY1", this.parms.getDate ( 2 ) );
    this.app.form ( "CALENDARIO_LF_FR" ).setValue ( "HASTA", this.parms.getDate ( 3 ) );
    this.app.form ( "CALENDARIO_LF_FR" ).setValue ( "DUMMY2", this.parms.getDate ( 4 ) );
  }


  /**
   *
   */
  protected void prepareParms ( )
  {
    this.parms.reset ( );
    this.parms.set ( this.app.form ( "CALENDARIO_LF_FR" ).getValue ( "FCH_ACTIVIDAD_HORA_MIN_CONTAC0" ) );
    this.parms.set ( this.app.form ( "CALENDARIO_LF_FR" ).getValue ( "DURACION_HORA_MIN_CONTACTO" ) );
    this.parms.set ( this.app.form ( "CALENDARIO_LF_FR" ).getValue ( "DUMMY1" ) );
    this.parms.set ( this.app.form ( "CALENDARIO_LF_FR" ).getValue ( "HASTA" ) );
    this.parms.set ( this.app.form ( "CALENDARIO_LF_FR" ).getValue ( "DUMMY2" ) );
  }


  /**
   *
   */
  public void execute ( RallyApplication __app, ParameterSet ps )
  {
    this.app = ( SAIC_DMQ_ORA_Application ) __app;
    this.execute ( ps );
  }
}
