package gov.dlf.presentation;


import gov.dlf.facade.*;
import gov.dlf.external.*;
import gov.dlf.logic.*;

import java.util.Date;


import net.maintrend.appmanager.*;
import net.maintrend.datamanager.*;
import net.maintrend.interfaces.*;
import net.maintrend.interlink.*;
import net.maintrend.jdatapanel.*;
import net.maintrend.jdatapanel.edit.*;
import net.maintrend.jdatapanel.commands.*;
import net.maintrend.mdi.*;
import net.maintrend.rallyengine.*;
import net.maintrend.util.*;



/**
 * __Comment
 *
 * Generated by Rally-to-Java Convertor. MainTrend Ltd.
 */
public class CALENDARIO_LF_FR
     extends Form
{
  // -------------------------------------------------------------------
  // ----------   Instance Attributes   --------------------------------

  /**  */
  public SAIC_DMQ_ORA_Application app;



  // -------------------------------------------------------------------
  // ----------   Constructors and supporting methods   ----------------

  /**
   *
   */
  public CALENDARIO_LF_FR ( )
  {
    super ( );
    this.setName ( "CALENDARIO_LF_FR" );

    Debug.println ( Debug.TRACE, "CALENDARIO_LF_FR - constructor" );

    this.setDefinitionPath ( "gov/dlf/presentation/CALENDARIO_LF_FR.jdp" );
    String definition = ResourceUtil.getResourceText ( this.definitionPath );
    this.setDefinition     ( definition );

    this.setHighLightSelected   ( false );
    this.compressFieldLocations ( false, true );  // Compresses only Y-locations
  }
  
  
  /**
   * Overrides ancestor's script
   *
   * @param __app
   */
  public void setApplication ( Application __app )
  {
    this.app = ( SAIC_DMQ_ORA_Application ) __app;
    if ( this.app != null )
    {
      this.setDataManager ( this.app.getDataManager ( ) );
    }

    ICalculator           calculator;
    IBooleanValueProvider txtVisible;
    IBooleanValueProvider groupVisible;
    IObjectValueProvider  valueProvider;
    JDataPanelField       field;
    JDataPanelTextGroup   txtGroup;
    JDataPanelGroup       visGroup;

    this.setArguments ( "CITAS", new CALENDARIO_LF_FR_CITAS_Arguments ( this ) );

    this.setObjectEvents ( );
    field = ( JDataPanelField ) this.getInDepth ( "FECHA" );
    field.setValueProvider ( new CALENDARIO_LF_FR_FECHAProvider ( this ) );
    field = ( JDataPanelField ) this.getInDepth ( "ID_TECNICO_COPY" );
    field.setValueProvider ( new CALENDARIO_LF_FR_ID_TECNICO_COPYProvider ( this ) );



    calculator = new CALENDARIO_LF_FR_HASTACalculator ( this );
    field = ( JDataPanelField ) this.getInDepth ( "HASTA" );
    field.setValueCalculator ( calculator );
  }


  /**
   * Overrides ancestor's method
   * 
   * @return
   */
  public RallyApplication getApplication ( )
  {
    return this.app;
  }



  // -------------------------------------------------------------------
  // ----------   Action Sites   ---------------------------------------

  /**
   *
   */
  public void setObjectEvents ( )
  {
    this.registerListener ( "FLECHITAS", JDataPanelListener.BEFOREENTER, new JDataPanelListener ( )
    {
      public boolean eventFired ( String eventName )
      {
        app.errorFlag = true; FLECHITA4_PPKT.exec ( app, null ); return app.errorFlag;
      }
    } );
    this.registerListener ( "FLECHITAS", JDataPanelListener.BEFORELEAVE, new JDataPanelListener ( )
    {
      public boolean eventFired ( String eventName )
      {
        app.errorFlag = true; FLECHITA4_PPKT.exec ( app, null ); return app.errorFlag;
      }
    } );
    this.registerListener ( "FLECHITAS", JDataPanelListener.HOTKEYPRESS, new JDataPanelListener ( )
    {
      public boolean eventFired ( String eventName )
      {
        app.errorFlag = true; DESEA_COMPLETAR_ADL.exec ( app ); return app.errorFlag;
      }
    } );
    this.registerListener ( "CITAS", JDataPanelListener.HOTKEYPRESS, new JDataPanelListener ( )
    {
      public boolean eventFired ( String eventName )
      {
        app.errorFlag = true; REPORT_9_10_PKT.exec ( app, null ); return app.errorFlag;
      }
    } );
  }
}





/**
 *
 */
class CALENDARIO_LF_FR_CITAS_Arguments extends JDataPanelGroupArguments
{
  /**  */
  protected Form model;
  /**  */
  protected SAIC_DMQ_ORA_Application app = null;

  /**  */
  public CALENDARIO_LF_FR_CITAS_Arguments ( Form form )
  {
    this.model = form;

    this.setArgName ( "FECHA1" );
    this.setArgName ( "FECHA2" );
    this.setArgName ( "ID_TECNICO_PAR" );
    this.setArgName ( "RMO_PAR" );
  }

  /**  */
  public Object getArgValue ( String argName )
  {
    if ( this.app == null ) this.app = ( SAIC_DMQ_ORA_Application ) this.model.getApplication ( );
    if ( argName == null )
    {
      return null;
    }
    else if ( argName.equals ( "FECHA1" ) )
    {
      return FECHA_COPY_ADL.getFECHA1 ( this.app ); // ADL Exported Field
    }
    else if ( argName.equals ( "FECHA2" ) )
    {
      return FECHA_COPY_ADL.getFECHA2 ( this.app ); // ADL Exported Field
    }
    else if ( argName.equals ( "ID_TECNICO_PAR" ) )
    {
      return this.app.getID_TECNICO_GBL ( ); // Global Variable
    }
    else if ( argName.equals ( "RMO_PAR" ) )
    {
      return this.app.getRMO_GBL ( ); // Global Variable
    }
    return null;
  }
}




/**
 *
 */
class CALENDARIO_LF_FR_FECHAProvider implements IObjectValueProvider
{
  /**  */
  protected Form model;
  /**  */
  protected SAIC_DMQ_ORA_Application app = null;

  /**  */
  public CALENDARIO_LF_FR_FECHAProvider ( Form form )
  {
    this.model = form;
  }

  /**  */
  public Object getValue ( )
  {
    if ( this.app == null ) this.app = ( SAIC_DMQ_ORA_Application ) this.model.getApplication ( );
    return FECHA_COPY_ADL.getFECHA3 ( this.app );
  }
}



/**
 *
 */
class CALENDARIO_LF_FR_ID_TECNICO_COPYProvider implements IObjectValueProvider
{
  /**  */
  protected Form model;
  /**  */
  protected SAIC_DMQ_ORA_Application app = null;

  /**  */
  public CALENDARIO_LF_FR_ID_TECNICO_COPYProvider ( Form form )
  {
    this.model = form;
  }

  /**  */
  public Object getValue ( )
  {
    if ( this.app == null ) this.app = ( SAIC_DMQ_ORA_Application ) this.model.getApplication ( );
    return this.app.form ( "CALENDARIO_MAIN_FR" ).getValue ( "ID_TECNICO" );
  }
}






/**
 *
 */
class CALENDARIO_LF_FR_HASTACalculator implements ICalculator
{
  /**  */
  protected Form model;
  /**  */
  protected SAIC_DMQ_ORA_Application app = null;

  /**  */
  public CALENDARIO_LF_FR_HASTACalculator ( Form form )
  {
    this.model = form;
  }

  /**  */
  public void calculate ( )
  {
    if ( this.app == null ) this.app = ( SAIC_DMQ_ORA_Application ) this.model.getApplication ( );
    this.app.exec ( "CITAS_PPKT0" );
  }
}


