package gov.dlf.logic;


import gov.dlf.external.*;
import gov.dlf.facade.*;
import gov.dlf.presentation.*;


import java.util.*;

import net.maintrend.appmanager.*;
import net.maintrend.datamanager.*;
import net.maintrend.interfaces.*;
import net.maintrend.interlink.*;
import net.maintrend.mdi.*;
import net.maintrend.rallyengine.*;
import net.maintrend.util.*;
import net.maintrend.util.format.*;



/**
 * __Comment
 *
 * Generated by Rally-to-Java Convertor. MainTrend Ltd.
 */
public class DETERMINACION_ELEGIBILIDAD_NO_UPD_ADL
     extends ADL
{
  // -------------------------------------------------------------------
  // ----------   Class Attributes   -----------------------------------

  /**  */
  public static boolean staticCall = false;



  // -------------------------------------------------------------------
  // ----------   Instance Attributes   --------------------------------

  /**  */
  public SAIC_DMQ_ORA_Application app;
  /**  */
  public RallyDataManager dm = null;



  // -------------------------------------------------------------------
  // ----------   Instance Condition Attributes   ----------------------
 
  public boolean _condition0 = false;
 
  public boolean _condition1 = false;
 
  public boolean _condition2 = false;
 
  public boolean _condition3 = false;
 
  public boolean _condition4 = false;
 
  public boolean _condition5 = false;

 

  // -------------------------------------------------------------------
  // ----------   Instance Export Attributes   -------------------------

  public double SERV_ID = 0;

  public double STAT_CODE = 0;

  public double OPEN_ID = 0;

  public double OPEN_ID2 = 0;

  public double OPEN_ID3 = 0;

  public double OPEN_ID4 = 0;

  public double OPEN_ID5 = 0;

  public double STATUS_CODE5 = 0;

  public double STATUS_CODE = 0;

  public double STATUS_CODE2 = 0;

  public double STATUS_CODE3 = 0;

  public double STATUS_CODE4 = 0;

  public double CNT_NUCLEO = 0;

  public double FLG_NCAL = 0;

  public double FLG_DESCALIFICADO = 0;

  public double SERVICIO_BENEFICIO = 0;



  public String SERVICIO_STATUS = null;

  public DataStore CLIENTES2_RO_DSD = null;

  public DataStore NUCLEO_READ_LOC_DSD = null;

  public DataStore SERVICIOS_LOC2_RO_DSD = null;

  public DataStore DESCALIFICADOS_READ_LOC_DSD = null;



  // -------------------------------------------------------------------
  // ----------   Instance Attributes' Access Methods   ----------------

  
  /**  */
  public static void setSERV_ID  ( RallyApplication __app, Parameter value )
  {
    ( ( DETERMINACION_ELEGIBILIDAD_NO_UPD_ADL ) __app.getADL ( DETERMINACION_ELEGIBILIDAD_NO_UPD_ADL.class ) ).SERV_ID = value.getDouble ( );
  }  

  
  /**  */
  public static void setSTAT_CODE  ( RallyApplication __app, Parameter value )
  {
    ( ( DETERMINACION_ELEGIBILIDAD_NO_UPD_ADL ) __app.getADL ( DETERMINACION_ELEGIBILIDAD_NO_UPD_ADL.class ) ).STAT_CODE = value.getDouble ( );
  }  

  
  /**  */
  public static void setOPEN_ID  ( RallyApplication __app, Parameter value )
  {
    ( ( DETERMINACION_ELEGIBILIDAD_NO_UPD_ADL ) __app.getADL ( DETERMINACION_ELEGIBILIDAD_NO_UPD_ADL.class ) ).OPEN_ID = value.getDouble ( );
  }  

  
  /**  */
  public static void setOPEN_ID2  ( RallyApplication __app, Parameter value )
  {
    ( ( DETERMINACION_ELEGIBILIDAD_NO_UPD_ADL ) __app.getADL ( DETERMINACION_ELEGIBILIDAD_NO_UPD_ADL.class ) ).OPEN_ID2 = value.getDouble ( );
  }  

  
  /**  */
  public static void setOPEN_ID3  ( RallyApplication __app, Parameter value )
  {
    ( ( DETERMINACION_ELEGIBILIDAD_NO_UPD_ADL ) __app.getADL ( DETERMINACION_ELEGIBILIDAD_NO_UPD_ADL.class ) ).OPEN_ID3 = value.getDouble ( );
  }  

  
  /**  */
  public static void setOPEN_ID4  ( RallyApplication __app, Parameter value )
  {
    ( ( DETERMINACION_ELEGIBILIDAD_NO_UPD_ADL ) __app.getADL ( DETERMINACION_ELEGIBILIDAD_NO_UPD_ADL.class ) ).OPEN_ID4 = value.getDouble ( );
  }  

  
  /**  */
  public static void setOPEN_ID5  ( RallyApplication __app, Parameter value )
  {
    ( ( DETERMINACION_ELEGIBILIDAD_NO_UPD_ADL ) __app.getADL ( DETERMINACION_ELEGIBILIDAD_NO_UPD_ADL.class ) ).OPEN_ID5 = value.getDouble ( );
  }  

  
  /**  */
  public static void setSTATUS_CODE5  ( RallyApplication __app, Parameter value )
  {
    ( ( DETERMINACION_ELEGIBILIDAD_NO_UPD_ADL ) __app.getADL ( DETERMINACION_ELEGIBILIDAD_NO_UPD_ADL.class ) ).STATUS_CODE5 = value.getDouble ( );
  }  

  
  /**  */
  public static void setSTATUS_CODE  ( RallyApplication __app, Parameter value )
  {
    ( ( DETERMINACION_ELEGIBILIDAD_NO_UPD_ADL ) __app.getADL ( DETERMINACION_ELEGIBILIDAD_NO_UPD_ADL.class ) ).STATUS_CODE = value.getDouble ( );
  }  

  
  /**  */
  public static void setSTATUS_CODE2  ( RallyApplication __app, Parameter value )
  {
    ( ( DETERMINACION_ELEGIBILIDAD_NO_UPD_ADL ) __app.getADL ( DETERMINACION_ELEGIBILIDAD_NO_UPD_ADL.class ) ).STATUS_CODE2 = value.getDouble ( );
  }  

  
  /**  */
  public static void setSTATUS_CODE3  ( RallyApplication __app, Parameter value )
  {
    ( ( DETERMINACION_ELEGIBILIDAD_NO_UPD_ADL ) __app.getADL ( DETERMINACION_ELEGIBILIDAD_NO_UPD_ADL.class ) ).STATUS_CODE3 = value.getDouble ( );
  }  

  
  /**  */
  public static void setSTATUS_CODE4  ( RallyApplication __app, Parameter value )
  {
    ( ( DETERMINACION_ELEGIBILIDAD_NO_UPD_ADL ) __app.getADL ( DETERMINACION_ELEGIBILIDAD_NO_UPD_ADL.class ) ).STATUS_CODE4 = value.getDouble ( );
  }  

  
  /**  */
  public static void setCNT_NUCLEO  ( RallyApplication __app, Parameter value )
  {
    ( ( DETERMINACION_ELEGIBILIDAD_NO_UPD_ADL ) __app.getADL ( DETERMINACION_ELEGIBILIDAD_NO_UPD_ADL.class ) ).CNT_NUCLEO = value.getDouble ( );
  }  

  
  /**  */
  public static void setFLG_NCAL  ( RallyApplication __app, Parameter value )
  {
    ( ( DETERMINACION_ELEGIBILIDAD_NO_UPD_ADL ) __app.getADL ( DETERMINACION_ELEGIBILIDAD_NO_UPD_ADL.class ) ).FLG_NCAL = value.getDouble ( );
  }  

  
  /**  */
  public static void setFLG_DESCALIFICADO  ( RallyApplication __app, Parameter value )
  {
    ( ( DETERMINACION_ELEGIBILIDAD_NO_UPD_ADL ) __app.getADL ( DETERMINACION_ELEGIBILIDAD_NO_UPD_ADL.class ) ).FLG_DESCALIFICADO = value.getDouble ( );
  }  

  
  /**  */
  public static void setSERVICIO_STATUS  ( RallyApplication __app, Parameter value )
  {
    ( ( DETERMINACION_ELEGIBILIDAD_NO_UPD_ADL ) __app.getADL ( DETERMINACION_ELEGIBILIDAD_NO_UPD_ADL.class ) ).SERVICIO_STATUS = value.getString ( );
  }  

  
  /**  */
  public static void setSERVICIO_BENEFICIO  ( RallyApplication __app, Parameter value )
  {
    ( ( DETERMINACION_ELEGIBILIDAD_NO_UPD_ADL ) __app.getADL ( DETERMINACION_ELEGIBILIDAD_NO_UPD_ADL.class ) ).SERVICIO_BENEFICIO = value.getDouble ( );
  }  
    


  /**  */
  public static String getSERVICIO_STATUS  ( RallyApplication __app )
  {
    return ( ( DETERMINACION_ELEGIBILIDAD_NO_UPD_ADL ) __app.getADL ( DETERMINACION_ELEGIBILIDAD_NO_UPD_ADL.class ) ).SERVICIO_STATUS;
  }


  /**  */
  public static void setSERVICIO_STATUS  ( RallyApplication __app, String value )
  {
    ( ( DETERMINACION_ELEGIBILIDAD_NO_UPD_ADL ) __app.getADL ( DETERMINACION_ELEGIBILIDAD_NO_UPD_ADL.class ) ).SERVICIO_STATUS = value;
  }


  /**  */
  public static void setSERVICIO_STATUS  ( RallyApplication __app, Object value )
  {
    ( ( DETERMINACION_ELEGIBILIDAD_NO_UPD_ADL ) __app.getADL ( DETERMINACION_ELEGIBILIDAD_NO_UPD_ADL.class ) ).SERVICIO_STATUS = ( String ) value;
  }



  /**  */
  public static DataStore getCLIENTES2_RO_DSD  ( RallyApplication __app )
  {
    return ( ( DETERMINACION_ELEGIBILIDAD_NO_UPD_ADL ) __app.getADL ( DETERMINACION_ELEGIBILIDAD_NO_UPD_ADL.class ) ).CLIENTES2_RO_DSD;
  }


  /**  */
  public static void setCLIENTES2_RO_DSD  ( RallyApplication __app, DataStore value )
  {
    ( ( DETERMINACION_ELEGIBILIDAD_NO_UPD_ADL ) __app.getADL ( DETERMINACION_ELEGIBILIDAD_NO_UPD_ADL.class ) ).CLIENTES2_RO_DSD = value;
  }


  /**  */
  public static void setCLIENTES2_RO_DSD  ( RallyApplication __app, Object value )
  {
    ( ( DETERMINACION_ELEGIBILIDAD_NO_UPD_ADL ) __app.getADL ( DETERMINACION_ELEGIBILIDAD_NO_UPD_ADL.class ) ).CLIENTES2_RO_DSD = ( DataStore ) value;
  }



  /**  */
  public static DataStore getNUCLEO_READ_LOC_DSD  ( RallyApplication __app )
  {
    return ( ( DETERMINACION_ELEGIBILIDAD_NO_UPD_ADL ) __app.getADL ( DETERMINACION_ELEGIBILIDAD_NO_UPD_ADL.class ) ).NUCLEO_READ_LOC_DSD;
  }


  /**  */
  public static void setNUCLEO_READ_LOC_DSD  ( RallyApplication __app, DataStore value )
  {
    ( ( DETERMINACION_ELEGIBILIDAD_NO_UPD_ADL ) __app.getADL ( DETERMINACION_ELEGIBILIDAD_NO_UPD_ADL.class ) ).NUCLEO_READ_LOC_DSD = value;
  }


  /**  */
  public static void setNUCLEO_READ_LOC_DSD  ( RallyApplication __app, Object value )
  {
    ( ( DETERMINACION_ELEGIBILIDAD_NO_UPD_ADL ) __app.getADL ( DETERMINACION_ELEGIBILIDAD_NO_UPD_ADL.class ) ).NUCLEO_READ_LOC_DSD = ( DataStore ) value;
  }



  /**  */
  public static DataStore getSERVICIOS_LOC2_RO_DSD  ( RallyApplication __app )
  {
    return ( ( DETERMINACION_ELEGIBILIDAD_NO_UPD_ADL ) __app.getADL ( DETERMINACION_ELEGIBILIDAD_NO_UPD_ADL.class ) ).SERVICIOS_LOC2_RO_DSD;
  }


  /**  */
  public static void setSERVICIOS_LOC2_RO_DSD  ( RallyApplication __app, DataStore value )
  {
    ( ( DETERMINACION_ELEGIBILIDAD_NO_UPD_ADL ) __app.getADL ( DETERMINACION_ELEGIBILIDAD_NO_UPD_ADL.class ) ).SERVICIOS_LOC2_RO_DSD = value;
  }


  /**  */
  public static void setSERVICIOS_LOC2_RO_DSD  ( RallyApplication __app, Object value )
  {
    ( ( DETERMINACION_ELEGIBILIDAD_NO_UPD_ADL ) __app.getADL ( DETERMINACION_ELEGIBILIDAD_NO_UPD_ADL.class ) ).SERVICIOS_LOC2_RO_DSD = ( DataStore ) value;
  }



  /**  */
  public static DataStore getDESCALIFICADOS_READ_LOC_DSD  ( RallyApplication __app )
  {
    return ( ( DETERMINACION_ELEGIBILIDAD_NO_UPD_ADL ) __app.getADL ( DETERMINACION_ELEGIBILIDAD_NO_UPD_ADL.class ) ).DESCALIFICADOS_READ_LOC_DSD;
  }


  /**  */
  public static void setDESCALIFICADOS_READ_LOC_DSD  ( RallyApplication __app, DataStore value )
  {
    ( ( DETERMINACION_ELEGIBILIDAD_NO_UPD_ADL ) __app.getADL ( DETERMINACION_ELEGIBILIDAD_NO_UPD_ADL.class ) ).DESCALIFICADOS_READ_LOC_DSD = value;
  }


  /**  */
  public static void setDESCALIFICADOS_READ_LOC_DSD  ( RallyApplication __app, Object value )
  {
    ( ( DETERMINACION_ELEGIBILIDAD_NO_UPD_ADL ) __app.getADL ( DETERMINACION_ELEGIBILIDAD_NO_UPD_ADL.class ) ).DESCALIFICADOS_READ_LOC_DSD = ( DataStore ) value;
  }




  /**  */
  public static double getSERV_ID  ( RallyApplication __app )
  {
    return ( ( DETERMINACION_ELEGIBILIDAD_NO_UPD_ADL ) __app.getADL ( DETERMINACION_ELEGIBILIDAD_NO_UPD_ADL.class ) ).SERV_ID;
  }


  /**  */
  public static Double getSERV_IDDouble ( RallyApplication __app )
  {
    return new Double ( ( ( DETERMINACION_ELEGIBILIDAD_NO_UPD_ADL ) __app.getADL ( DETERMINACION_ELEGIBILIDAD_NO_UPD_ADL.class ) ).SERV_ID );
  }


  /**  */
  public static void setSERV_ID  ( RallyApplication __app, double value )
  {
    ( ( DETERMINACION_ELEGIBILIDAD_NO_UPD_ADL ) __app.getADL ( DETERMINACION_ELEGIBILIDAD_NO_UPD_ADL.class ) ).SERV_ID = value;
  }


  /**  */
  public static void setSERV_ID  ( RallyApplication __app, Object value )
  {
    ( ( DETERMINACION_ELEGIBILIDAD_NO_UPD_ADL ) __app.getADL ( DETERMINACION_ELEGIBILIDAD_NO_UPD_ADL.class ) ).SERV_ID = ( ( Double ) value ).doubleValue ( );
  }


  /**  */
  public static double getSTAT_CODE  ( RallyApplication __app )
  {
    return ( ( DETERMINACION_ELEGIBILIDAD_NO_UPD_ADL ) __app.getADL ( DETERMINACION_ELEGIBILIDAD_NO_UPD_ADL.class ) ).STAT_CODE;
  }


  /**  */
  public static Double getSTAT_CODEDouble ( RallyApplication __app )
  {
    return new Double ( ( ( DETERMINACION_ELEGIBILIDAD_NO_UPD_ADL ) __app.getADL ( DETERMINACION_ELEGIBILIDAD_NO_UPD_ADL.class ) ).STAT_CODE );
  }


  /**  */
  public static void setSTAT_CODE  ( RallyApplication __app, double value )
  {
    ( ( DETERMINACION_ELEGIBILIDAD_NO_UPD_ADL ) __app.getADL ( DETERMINACION_ELEGIBILIDAD_NO_UPD_ADL.class ) ).STAT_CODE = value;
  }


  /**  */
  public static void setSTAT_CODE  ( RallyApplication __app, Object value )
  {
    ( ( DETERMINACION_ELEGIBILIDAD_NO_UPD_ADL ) __app.getADL ( DETERMINACION_ELEGIBILIDAD_NO_UPD_ADL.class ) ).STAT_CODE = ( ( Double ) value ).doubleValue ( );
  }


  /**  */
  public static double getOPEN_ID  ( RallyApplication __app )
  {
    return ( ( DETERMINACION_ELEGIBILIDAD_NO_UPD_ADL ) __app.getADL ( DETERMINACION_ELEGIBILIDAD_NO_UPD_ADL.class ) ).OPEN_ID;
  }


  /**  */
  public static Double getOPEN_IDDouble ( RallyApplication __app )
  {
    return new Double ( ( ( DETERMINACION_ELEGIBILIDAD_NO_UPD_ADL ) __app.getADL ( DETERMINACION_ELEGIBILIDAD_NO_UPD_ADL.class ) ).OPEN_ID );
  }


  /**  */
  public static void setOPEN_ID  ( RallyApplication __app, double value )
  {
    ( ( DETERMINACION_ELEGIBILIDAD_NO_UPD_ADL ) __app.getADL ( DETERMINACION_ELEGIBILIDAD_NO_UPD_ADL.class ) ).OPEN_ID = value;
  }


  /**  */
  public static void setOPEN_ID  ( RallyApplication __app, Object value )
  {
    ( ( DETERMINACION_ELEGIBILIDAD_NO_UPD_ADL ) __app.getADL ( DETERMINACION_ELEGIBILIDAD_NO_UPD_ADL.class ) ).OPEN_ID = ( ( Double ) value ).doubleValue ( );
  }


  /**  */
  public static double getOPEN_ID2  ( RallyApplication __app )
  {
    return ( ( DETERMINACION_ELEGIBILIDAD_NO_UPD_ADL ) __app.getADL ( DETERMINACION_ELEGIBILIDAD_NO_UPD_ADL.class ) ).OPEN_ID2;
  }


  /**  */
  public static Double getOPEN_ID2Double ( RallyApplication __app )
  {
    return new Double ( ( ( DETERMINACION_ELEGIBILIDAD_NO_UPD_ADL ) __app.getADL ( DETERMINACION_ELEGIBILIDAD_NO_UPD_ADL.class ) ).OPEN_ID2 );
  }


  /**  */
  public static void setOPEN_ID2  ( RallyApplication __app, double value )
  {
    ( ( DETERMINACION_ELEGIBILIDAD_NO_UPD_ADL ) __app.getADL ( DETERMINACION_ELEGIBILIDAD_NO_UPD_ADL.class ) ).OPEN_ID2 = value;
  }


  /**  */
  public static void setOPEN_ID2  ( RallyApplication __app, Object value )
  {
    ( ( DETERMINACION_ELEGIBILIDAD_NO_UPD_ADL ) __app.getADL ( DETERMINACION_ELEGIBILIDAD_NO_UPD_ADL.class ) ).OPEN_ID2 = ( ( Double ) value ).doubleValue ( );
  }


  /**  */
  public static double getOPEN_ID3  ( RallyApplication __app )
  {
    return ( ( DETERMINACION_ELEGIBILIDAD_NO_UPD_ADL ) __app.getADL ( DETERMINACION_ELEGIBILIDAD_NO_UPD_ADL.class ) ).OPEN_ID3;
  }


  /**  */
  public static Double getOPEN_ID3Double ( RallyApplication __app )
  {
    return new Double ( ( ( DETERMINACION_ELEGIBILIDAD_NO_UPD_ADL ) __app.getADL ( DETERMINACION_ELEGIBILIDAD_NO_UPD_ADL.class ) ).OPEN_ID3 );
  }


  /**  */
  public static void setOPEN_ID3  ( RallyApplication __app, double value )
  {
    ( ( DETERMINACION_ELEGIBILIDAD_NO_UPD_ADL ) __app.getADL ( DETERMINACION_ELEGIBILIDAD_NO_UPD_ADL.class ) ).OPEN_ID3 = value;
  }


  /**  */
  public static void setOPEN_ID3  ( RallyApplication __app, Object value )
  {
    ( ( DETERMINACION_ELEGIBILIDAD_NO_UPD_ADL ) __app.getADL ( DETERMINACION_ELEGIBILIDAD_NO_UPD_ADL.class ) ).OPEN_ID3 = ( ( Double ) value ).doubleValue ( );
  }


  /**  */
  public static double getOPEN_ID4  ( RallyApplication __app )
  {
    return ( ( DETERMINACION_ELEGIBILIDAD_NO_UPD_ADL ) __app.getADL ( DETERMINACION_ELEGIBILIDAD_NO_UPD_ADL.class ) ).OPEN_ID4;
  }


  /**  */
  public static Double getOPEN_ID4Double ( RallyApplication __app )
  {
    return new Double ( ( ( DETERMINACION_ELEGIBILIDAD_NO_UPD_ADL ) __app.getADL ( DETERMINACION_ELEGIBILIDAD_NO_UPD_ADL.class ) ).OPEN_ID4 );
  }


  /**  */
  public static void setOPEN_ID4  ( RallyApplication __app, double value )
  {
    ( ( DETERMINACION_ELEGIBILIDAD_NO_UPD_ADL ) __app.getADL ( DETERMINACION_ELEGIBILIDAD_NO_UPD_ADL.class ) ).OPEN_ID4 = value;
  }


  /**  */
  public static void setOPEN_ID4  ( RallyApplication __app, Object value )
  {
    ( ( DETERMINACION_ELEGIBILIDAD_NO_UPD_ADL ) __app.getADL ( DETERMINACION_ELEGIBILIDAD_NO_UPD_ADL.class ) ).OPEN_ID4 = ( ( Double ) value ).doubleValue ( );
  }


  /**  */
  public static double getOPEN_ID5  ( RallyApplication __app )
  {
    return ( ( DETERMINACION_ELEGIBILIDAD_NO_UPD_ADL ) __app.getADL ( DETERMINACION_ELEGIBILIDAD_NO_UPD_ADL.class ) ).OPEN_ID5;
  }


  /**  */
  public static Double getOPEN_ID5Double ( RallyApplication __app )
  {
    return new Double ( ( ( DETERMINACION_ELEGIBILIDAD_NO_UPD_ADL ) __app.getADL ( DETERMINACION_ELEGIBILIDAD_NO_UPD_ADL.class ) ).OPEN_ID5 );
  }


  /**  */
  public static void setOPEN_ID5  ( RallyApplication __app, double value )
  {
    ( ( DETERMINACION_ELEGIBILIDAD_NO_UPD_ADL ) __app.getADL ( DETERMINACION_ELEGIBILIDAD_NO_UPD_ADL.class ) ).OPEN_ID5 = value;
  }


  /**  */
  public static void setOPEN_ID5  ( RallyApplication __app, Object value )
  {
    ( ( DETERMINACION_ELEGIBILIDAD_NO_UPD_ADL ) __app.getADL ( DETERMINACION_ELEGIBILIDAD_NO_UPD_ADL.class ) ).OPEN_ID5 = ( ( Double ) value ).doubleValue ( );
  }


  /**  */
  public static double getSTATUS_CODE5  ( RallyApplication __app )
  {
    return ( ( DETERMINACION_ELEGIBILIDAD_NO_UPD_ADL ) __app.getADL ( DETERMINACION_ELEGIBILIDAD_NO_UPD_ADL.class ) ).STATUS_CODE5;
  }


  /**  */
  public static Double getSTATUS_CODE5Double ( RallyApplication __app )
  {
    return new Double ( ( ( DETERMINACION_ELEGIBILIDAD_NO_UPD_ADL ) __app.getADL ( DETERMINACION_ELEGIBILIDAD_NO_UPD_ADL.class ) ).STATUS_CODE5 );
  }


  /**  */
  public static void setSTATUS_CODE5  ( RallyApplication __app, double value )
  {
    ( ( DETERMINACION_ELEGIBILIDAD_NO_UPD_ADL ) __app.getADL ( DETERMINACION_ELEGIBILIDAD_NO_UPD_ADL.class ) ).STATUS_CODE5 = value;
  }


  /**  */
  public static void setSTATUS_CODE5  ( RallyApplication __app, Object value )
  {
    ( ( DETERMINACION_ELEGIBILIDAD_NO_UPD_ADL ) __app.getADL ( DETERMINACION_ELEGIBILIDAD_NO_UPD_ADL.class ) ).STATUS_CODE5 = ( ( Double ) value ).doubleValue ( );
  }


  /**  */
  public static double getSTATUS_CODE  ( RallyApplication __app )
  {
    return ( ( DETERMINACION_ELEGIBILIDAD_NO_UPD_ADL ) __app.getADL ( DETERMINACION_ELEGIBILIDAD_NO_UPD_ADL.class ) ).STATUS_CODE;
  }


  /**  */
  public static Double getSTATUS_CODEDouble ( RallyApplication __app )
  {
    return new Double ( ( ( DETERMINACION_ELEGIBILIDAD_NO_UPD_ADL ) __app.getADL ( DETERMINACION_ELEGIBILIDAD_NO_UPD_ADL.class ) ).STATUS_CODE );
  }


  /**  */
  public static void setSTATUS_CODE  ( RallyApplication __app, double value )
  {
    ( ( DETERMINACION_ELEGIBILIDAD_NO_UPD_ADL ) __app.getADL ( DETERMINACION_ELEGIBILIDAD_NO_UPD_ADL.class ) ).STATUS_CODE = value;
  }


  /**  */
  public static void setSTATUS_CODE  ( RallyApplication __app, Object value )
  {
    ( ( DETERMINACION_ELEGIBILIDAD_NO_UPD_ADL ) __app.getADL ( DETERMINACION_ELEGIBILIDAD_NO_UPD_ADL.class ) ).STATUS_CODE = ( ( Double ) value ).doubleValue ( );
  }


  /**  */
  public static double getSTATUS_CODE2  ( RallyApplication __app )
  {
    return ( ( DETERMINACION_ELEGIBILIDAD_NO_UPD_ADL ) __app.getADL ( DETERMINACION_ELEGIBILIDAD_NO_UPD_ADL.class ) ).STATUS_CODE2;
  }


  /**  */
  public static Double getSTATUS_CODE2Double ( RallyApplication __app )
  {
    return new Double ( ( ( DETERMINACION_ELEGIBILIDAD_NO_UPD_ADL ) __app.getADL ( DETERMINACION_ELEGIBILIDAD_NO_UPD_ADL.class ) ).STATUS_CODE2 );
  }


  /**  */
  public static void setSTATUS_CODE2  ( RallyApplication __app, double value )
  {
    ( ( DETERMINACION_ELEGIBILIDAD_NO_UPD_ADL ) __app.getADL ( DETERMINACION_ELEGIBILIDAD_NO_UPD_ADL.class ) ).STATUS_CODE2 = value;
  }


  /**  */
  public static void setSTATUS_CODE2  ( RallyApplication __app, Object value )
  {
    ( ( DETERMINACION_ELEGIBILIDAD_NO_UPD_ADL ) __app.getADL ( DETERMINACION_ELEGIBILIDAD_NO_UPD_ADL.class ) ).STATUS_CODE2 = ( ( Double ) value ).doubleValue ( );
  }


  /**  */
  public static double getSTATUS_CODE3  ( RallyApplication __app )
  {
    return ( ( DETERMINACION_ELEGIBILIDAD_NO_UPD_ADL ) __app.getADL ( DETERMINACION_ELEGIBILIDAD_NO_UPD_ADL.class ) ).STATUS_CODE3;
  }


  /**  */
  public static Double getSTATUS_CODE3Double ( RallyApplication __app )
  {
    return new Double ( ( ( DETERMINACION_ELEGIBILIDAD_NO_UPD_ADL ) __app.getADL ( DETERMINACION_ELEGIBILIDAD_NO_UPD_ADL.class ) ).STATUS_CODE3 );
  }


  /**  */
  public static void setSTATUS_CODE3  ( RallyApplication __app, double value )
  {
    ( ( DETERMINACION_ELEGIBILIDAD_NO_UPD_ADL ) __app.getADL ( DETERMINACION_ELEGIBILIDAD_NO_UPD_ADL.class ) ).STATUS_CODE3 = value;
  }


  /**  */
  public static void setSTATUS_CODE3  ( RallyApplication __app, Object value )
  {
    ( ( DETERMINACION_ELEGIBILIDAD_NO_UPD_ADL ) __app.getADL ( DETERMINACION_ELEGIBILIDAD_NO_UPD_ADL.class ) ).STATUS_CODE3 = ( ( Double ) value ).doubleValue ( );
  }


  /**  */
  public static double getSTATUS_CODE4  ( RallyApplication __app )
  {
    return ( ( DETERMINACION_ELEGIBILIDAD_NO_UPD_ADL ) __app.getADL ( DETERMINACION_ELEGIBILIDAD_NO_UPD_ADL.class ) ).STATUS_CODE4;
  }


  /**  */
  public static Double getSTATUS_CODE4Double ( RallyApplication __app )
  {
    return new Double ( ( ( DETERMINACION_ELEGIBILIDAD_NO_UPD_ADL ) __app.getADL ( DETERMINACION_ELEGIBILIDAD_NO_UPD_ADL.class ) ).STATUS_CODE4 );
  }


  /**  */
  public static void setSTATUS_CODE4  ( RallyApplication __app, double value )
  {
    ( ( DETERMINACION_ELEGIBILIDAD_NO_UPD_ADL ) __app.getADL ( DETERMINACION_ELEGIBILIDAD_NO_UPD_ADL.class ) ).STATUS_CODE4 = value;
  }


  /**  */
  public static void setSTATUS_CODE4  ( RallyApplication __app, Object value )
  {
    ( ( DETERMINACION_ELEGIBILIDAD_NO_UPD_ADL ) __app.getADL ( DETERMINACION_ELEGIBILIDAD_NO_UPD_ADL.class ) ).STATUS_CODE4 = ( ( Double ) value ).doubleValue ( );
  }


  /**  */
  public static double getCNT_NUCLEO  ( RallyApplication __app )
  {
    return ( ( DETERMINACION_ELEGIBILIDAD_NO_UPD_ADL ) __app.getADL ( DETERMINACION_ELEGIBILIDAD_NO_UPD_ADL.class ) ).CNT_NUCLEO;
  }


  /**  */
  public static Double getCNT_NUCLEODouble ( RallyApplication __app )
  {
    return new Double ( ( ( DETERMINACION_ELEGIBILIDAD_NO_UPD_ADL ) __app.getADL ( DETERMINACION_ELEGIBILIDAD_NO_UPD_ADL.class ) ).CNT_NUCLEO );
  }


  /**  */
  public static void setCNT_NUCLEO  ( RallyApplication __app, double value )
  {
    ( ( DETERMINACION_ELEGIBILIDAD_NO_UPD_ADL ) __app.getADL ( DETERMINACION_ELEGIBILIDAD_NO_UPD_ADL.class ) ).CNT_NUCLEO = value;
  }


  /**  */
  public static void setCNT_NUCLEO  ( RallyApplication __app, Object value )
  {
    ( ( DETERMINACION_ELEGIBILIDAD_NO_UPD_ADL ) __app.getADL ( DETERMINACION_ELEGIBILIDAD_NO_UPD_ADL.class ) ).CNT_NUCLEO = ( ( Double ) value ).doubleValue ( );
  }


  /**  */
  public static double getFLG_NCAL  ( RallyApplication __app )
  {
    return ( ( DETERMINACION_ELEGIBILIDAD_NO_UPD_ADL ) __app.getADL ( DETERMINACION_ELEGIBILIDAD_NO_UPD_ADL.class ) ).FLG_NCAL;
  }


  /**  */
  public static Double getFLG_NCALDouble ( RallyApplication __app )
  {
    return new Double ( ( ( DETERMINACION_ELEGIBILIDAD_NO_UPD_ADL ) __app.getADL ( DETERMINACION_ELEGIBILIDAD_NO_UPD_ADL.class ) ).FLG_NCAL );
  }


  /**  */
  public static void setFLG_NCAL  ( RallyApplication __app, double value )
  {
    ( ( DETERMINACION_ELEGIBILIDAD_NO_UPD_ADL ) __app.getADL ( DETERMINACION_ELEGIBILIDAD_NO_UPD_ADL.class ) ).FLG_NCAL = value;
  }


  /**  */
  public static void setFLG_NCAL  ( RallyApplication __app, Object value )
  {
    ( ( DETERMINACION_ELEGIBILIDAD_NO_UPD_ADL ) __app.getADL ( DETERMINACION_ELEGIBILIDAD_NO_UPD_ADL.class ) ).FLG_NCAL = ( ( Double ) value ).doubleValue ( );
  }


  /**  */
  public static double getFLG_DESCALIFICADO  ( RallyApplication __app )
  {
    return ( ( DETERMINACION_ELEGIBILIDAD_NO_UPD_ADL ) __app.getADL ( DETERMINACION_ELEGIBILIDAD_NO_UPD_ADL.class ) ).FLG_DESCALIFICADO;
  }


  /**  */
  public static Double getFLG_DESCALIFICADODouble ( RallyApplication __app )
  {
    return new Double ( ( ( DETERMINACION_ELEGIBILIDAD_NO_UPD_ADL ) __app.getADL ( DETERMINACION_ELEGIBILIDAD_NO_UPD_ADL.class ) ).FLG_DESCALIFICADO );
  }


  /**  */
  public static void setFLG_DESCALIFICADO  ( RallyApplication __app, double value )
  {
    ( ( DETERMINACION_ELEGIBILIDAD_NO_UPD_ADL ) __app.getADL ( DETERMINACION_ELEGIBILIDAD_NO_UPD_ADL.class ) ).FLG_DESCALIFICADO = value;
  }


  /**  */
  public static void setFLG_DESCALIFICADO  ( RallyApplication __app, Object value )
  {
    ( ( DETERMINACION_ELEGIBILIDAD_NO_UPD_ADL ) __app.getADL ( DETERMINACION_ELEGIBILIDAD_NO_UPD_ADL.class ) ).FLG_DESCALIFICADO = ( ( Double ) value ).doubleValue ( );
  }


  /**  */
  public static double getSERVICIO_BENEFICIO  ( RallyApplication __app )
  {
    return ( ( DETERMINACION_ELEGIBILIDAD_NO_UPD_ADL ) __app.getADL ( DETERMINACION_ELEGIBILIDAD_NO_UPD_ADL.class ) ).SERVICIO_BENEFICIO;
  }


  /**  */
  public static Double getSERVICIO_BENEFICIODouble ( RallyApplication __app )
  {
    return new Double ( ( ( DETERMINACION_ELEGIBILIDAD_NO_UPD_ADL ) __app.getADL ( DETERMINACION_ELEGIBILIDAD_NO_UPD_ADL.class ) ).SERVICIO_BENEFICIO );
  }


  /**  */
  public static void setSERVICIO_BENEFICIO  ( RallyApplication __app, double value )
  {
    ( ( DETERMINACION_ELEGIBILIDAD_NO_UPD_ADL ) __app.getADL ( DETERMINACION_ELEGIBILIDAD_NO_UPD_ADL.class ) ).SERVICIO_BENEFICIO = value;
  }


  /**  */
  public static void setSERVICIO_BENEFICIO  ( RallyApplication __app, Object value )
  {
    ( ( DETERMINACION_ELEGIBILIDAD_NO_UPD_ADL ) __app.getADL ( DETERMINACION_ELEGIBILIDAD_NO_UPD_ADL.class ) ).SERVICIO_BENEFICIO = ( ( Double ) value ).doubleValue ( );
  }



  // -------------------------------------------------------------------
  // ----------   Methods   --------------------------------------------

  /**
   * 
   * @param __app
   * @return
   */
  public static DETERMINACION_ELEGIBILIDAD_NO_UPD_ADL get ( RallyApplication __app )
  {
    DETERMINACION_ELEGIBILIDAD_NO_UPD_ADL adl = new DETERMINACION_ELEGIBILIDAD_NO_UPD_ADL ( );
    __app.register ( adl, "DETERMINACION_ELEGIBILIDAD_NO_UPD_ADL" );
    __app.setADL ( DETERMINACION_ELEGIBILIDAD_NO_UPD_ADL.class, adl ); 
    adl.setApplication ( __app );
    return adl;
  }


  /**
   *
   * @param __app
   * @param ps
   *
   * @return
   */
  public static void exec ( RallyApplication __app, ParameterSet ps )
  {
    DETERMINACION_ELEGIBILIDAD_NO_UPD_ADL.get ( __app ).process ( ps );
  }


  /**
   *
   * @param __app
   *
   * @return
   */
  public static void exec ( RallyApplication __app )
  {
    ParameterSet ps = null;
    DETERMINACION_ELEGIBILIDAD_NO_UPD_ADL.exec ( __app, ps );
  }


  /**
   * Overrides the ancestor's method
   * 
   * @param __app
   */
  public void setApplication ( RallyApplication __app )
  {
    this.app = ( SAIC_DMQ_ORA_Application ) __app;
    if ( this.app != null )
    {
      this.dm = ( RallyDataManager ) this.app.getDataManager ( );
    }
  }


  /**
   * Overrides the ancestor's method
   * 
   * @param parms
   */
  public void execute ( ParameterSet parms )
  {
    this.process ( parms );
  }




  /**
   *
   */
  protected void doReturn ( )
  {
    this.unregister ( );
  }


  /**
   *
   */
  public void unregister ( )
  {
    this.app.unregister ( this );
    IRegisteredObject rObj = this.app.get ( "DETERMINACION_ELEGIBILIDAD_NO_UPD_ADL" );
    if ( rObj != null && rObj instanceof DETERMINACION_ELEGIBILIDAD_NO_UPD_ADL )
    {
      this.app.setADL ( DETERMINACION_ELEGIBILIDAD_NO_UPD_ADL.class, ( DETERMINACION_ELEGIBILIDAD_NO_UPD_ADL ) rObj );
    }
  }


  /**
   * Overrides the ancestor's method
   * 
   * @param ps
   */
  protected void process ( ParameterSet ps )
  {
    Debug.println ( Debug.TRACE, "DETERMINACION_ELEGIBILIDAD_NO_UPD_ADL Step " + this.currentStep );
    super.process ( ps );
    switch ( this.currentStep ) 
    {
      case 0:  { this.currentStep ++; this.step0 ( this.keyParms ); break; }
      case 1:  { this.currentStep ++; this.step1 ( this.keyParms ); break; }
      case 2:  { this.currentStep ++; this.step2 ( this.keyParms ); break; }
      case 3:  { this.currentStep ++; this.step3 ( this.keyParms ); break; }
      case 4:  { this.currentStep ++; this.step4 ( this.keyParms ); break; }
      case 5:  { this.currentStep ++; this.step5 ( this.keyParms ); break; }
      default: 
      { 
        this.currentStep = 0;
        Debug.println ( Debug.TRACE, "DETERMINACION_ELEGIBILIDAD_NO_UPD_ADL ended" );
        this.unregister ( );
        break;
      }
    }
    if ( this.currentStep > 0 ) this.app.goOn ( );
  }



  /**
   *
   */
  protected void step0 ( ParameterSet ps )
  {

    this.app.FLAG_UPD_GBL = "N";
    this.app.ANSWER_GBL = "N";
    this.app.SS_JEFE_GBL = this.app.form ( "DETERMINAR_RECLAMACION_FR" ).getDoubleItem ( "SEGURO_SOCIAL_JEFE_FAM" );
    this.app.SS_SERV_GBL = this.app.form ( "DETERMINAR_RECLAMACION_FR" ).getDoubleItem ( "SEGURO_SOCIAL_JEFE_SERV" );
    this.app.COD_SERV_GBL = this.app.form ( "DETERMINAR_RECLAMACION_FR" ).getStringItem ( "COD_SERVICIO" );
    CLIENTES2_RO_DSD = this.dm.create ( "CLIENTES2_RO_DSD" );
    OPEN_ID = CLIENTES2_RO_DSD.getId ( );
    STATUS_CODE = RallyDataStoreException.getDefault ( );
    NUCLEO_READ_LOC_DSD = this.dm.create ( "NUCLEO_READ_LOC_DSD" );
    OPEN_ID2 = NUCLEO_READ_LOC_DSD.getId ( );
    STATUS_CODE2 = RallyDataStoreException.getDefault ( );
    SERVICIOS_LOC2_RO_DSD = this.dm.create ( "SERVICIOS_LOC2_RO_DSD" );
    OPEN_ID3 = SERVICIOS_LOC2_RO_DSD.getId ( );
    STATUS_CODE3 = RallyDataStoreException.getDefault ( );
    DESCALIFICADOS_READ_LOC_DSD = this.dm.create ( "DESCALIFICADOS_READ_LOC_DSD" );
    OPEN_ID5 = DESCALIFICADOS_READ_LOC_DSD.getId ( );
    STATUS_CODE5 = RallyDataStoreException.getDefault ( );
    CNT_NUCLEO = 0;
    FLG_NCAL = 0;

    STATUS_CODE2  = this.dm.reset ( OPEN_ID2 );

    this.dm.setField ( this.dm.get ( "NUCLEO_READ_LOC_DSD" ), "SEGURO_SOCIAL_JEFE_FAM", this.app.SS_JEFE_GBL );
    this.dm.setField ( this.dm.get ( "NUCLEO_READ_LOC_DSD" ), "SEGURO_SOCIAL_JEFE_SERV", this.app.SS_SERV_GBL );
    this.dm.setField ( this.dm.get ( "NUCLEO_READ_LOC_DSD" ), "COD_SERVICIO", this.app.COD_SERV_GBL );
    this.dm.setField ( this.dm.get ( "NUCLEO_READ_LOC_DSD" ), "RMO_OFICINA", this.app.RMO_GBL );
    this.dm.setField ( this.dm.get ( "NUCLEO_READ_LOC_DSD" ), "RMO_OFICINA2", this.app.RMO_GBL );

    STATUS_CODE2  = this.dm.limitQueryFromBuffer ( OPEN_ID2 );
    STATUS_CODE2  = this.dm.retrieve ( OPEN_ID2 );

    STATUS_CODE2  = this.dm.firstRow ( OPEN_ID2 );

    while ( Compare.equals ( STATUS_CODE2, 0 )  )
    {
      CNT_NUCLEO = MathService.plus ( CNT_NUCLEO, 1  );
      if ( ( Compare.equals ( this.dm.getFieldString ( this.dm.get ( "NUCLEO_READ_LOC_DSD" ), "COD_PARENTESCO_RELACION_SERV" ), "NCAL" ) ) && ( Compare.equals ( CNT_NUCLEO, 1 ) )  ) 
      {
        FLG_NCAL = 1;
      }

      STATUS_CODE2  = this.dm.nextRow ( OPEN_ID2 );

    }
    if ( ( Compare.equals ( CNT_NUCLEO, 1 ) ) && ( Compare.equals ( FLG_NCAL, 1 ) )  ) 
    {
      SERVICIO_STATUS = "CERRAD12";
      SERVICIO_BENEFICIO = 0;
      this.app.form ( "DETERMINAR_RECLAMACION_FR" ).setItem ( "BENEFICIO_CALCULADO", 0  );
      this.app.form ( "DETERMINAR_RECLAMACION_FR" ).setItem ( "BENEFICIOS_CORRECTOS", 0  );
      this.app.form ( "DETERMINAR_RECLAMACION_FR" ).setItem ( "AJUSTE_PAN", 0  );
      this.app.setError ( 0, 2063 );
      this.app.errorFlag = false;
      this.doReturn ( );
      return; 
    }
    if ( Compare.equals ( RallyStringService.subString ( this.app.COD_SERV_GBL, 0, 2 ), "PA" ) ) 
    {
      STATUS_CODE2  = this.dm.reset ( OPEN_ID2 );

      this.dm.setField ( this.dm.get ( "NUCLEO_READ_LOC_DSD" ), "SEGURO_SOCIAL_JEFE_FAM", this.app.SS_JEFE_GBL );
      this.dm.setField ( this.dm.get ( "NUCLEO_READ_LOC_DSD" ), "SEGURO_SOCIAL_JEFE_SERV", this.app.SS_SERV_GBL );
      this.dm.setField ( this.dm.get ( "NUCLEO_READ_LOC_DSD" ), "COD_SERVICIO", this.app.COD_SERV_GBL );
      this.dm.setField ( this.dm.get ( "NUCLEO_READ_LOC_DSD" ), "RMO_OFICINA", this.app.RMO_GBL );
      this.dm.setField ( this.dm.get ( "NUCLEO_READ_LOC_DSD" ), "RMO_OFICINA2", this.app.RMO_GBL );

      STATUS_CODE2  = this.dm.limitQueryFromBuffer ( OPEN_ID2 );
      STATUS_CODE2  = this.dm.retrieve ( OPEN_ID2 );

      STATUS_CODE2  = this.dm.firstRow ( OPEN_ID2 );

      while ( Compare.equals ( STATUS_CODE2, 0 )  )
      {
        STATUS_CODE  = this.dm.reset ( OPEN_ID );

        this.dm.setField ( this.dm.get ( "CLIENTES2_RO_DSD" ), "SEGURO_SOCIAL_CLIENTE", this.dm.getFieldDouble ( this.dm.get ( "NUCLEO_READ_LOC_DSD" ), "SEGURO_SOCIAL_BENEFICIARIO" ) );
        this.dm.setField ( this.dm.get ( "CLIENTES2_RO_DSD" ), "RMO_OFICINA", this.app.RMO_GBL );

        STATUS_CODE  = this.dm.limitQueryFromBuffer ( OPEN_ID );
        STATUS_CODE  = this.dm.retrieve ( OPEN_ID );

        STATUS_CODE  = this.dm.firstRow ( OPEN_ID );

        if ( ( ( Compare.equals ( this.dm.getFieldString ( this.dm.get ( "CLIENTES2_RO_DSD" ), "TIPO_REGISTRO" ), "DISP" ) ) || ( Compare.equals ( this.dm.getFieldString ( this.dm.get ( "CLIENTES2_RO_DSD" ), "TIPO_REGISTRO" ), "HABL" ) ) || ( Compare.equals ( this.dm.getFieldString ( this.dm.get ( "CLIENTES2_RO_DSD" ), "TIPO_REGISTRO" ), "" ) ) ) && ( ! Compare.equals ( this.dm.getFieldString ( this.dm.get ( "CLIENTES2_RO_DSD" ), "ACEPTA_REGISTRO_EMPLEO" ), "S" ) )  && ( Compare.equals ( STATUS_CODE, 0 ) )  ) 
        {
          STATUS_CODE5  = this.dm.reset ( OPEN_ID5 );

          this.dm.setField ( this.dm.get ( "DESCALIFICADOS_READ_LOC_DSD" ), "SEGURO_SOCIAL_CLIENTE", this.dm.getFieldDouble ( this.dm.get ( "NUCLEO_READ_LOC_DSD" ), "SEGURO_SOCIAL_BENEFICIARIO" ) );
          this.dm.setField ( this.dm.get ( "DESCALIFICADOS_READ_LOC_DSD" ), "COD_SERVICIO", this.app.COD_SERV_GBL );
          this.dm.setField ( this.dm.get ( "DESCALIFICADOS_READ_LOC_DSD" ), "RMO_OFICINA", this.app.RMO_GBL );

          STATUS_CODE5  = this.dm.limitQueryFromBuffer ( OPEN_ID5 );
          STATUS_CODE5  = this.dm.retrieve ( OPEN_ID5 );

          STATUS_CODE5  = this.dm.firstRow ( OPEN_ID5 );

          FLG_DESCALIFICADO = 0;
          while ( ( Compare.equals ( FLG_DESCALIFICADO, 0 ) ) && ( Compare.equals ( STATUS_CODE5, 0 ) )   )
          {
            if ( Compare.ge ( this.dm.getFieldDate ( this.dm.get ( "DESCALIFICADOS_READ_LOC_DSD" ), "FCH_VENCIMIENTO" ), this.app.SYSTEM_DATE ) ) 
            {
              FLG_DESCALIFICADO = 1;
            }

            STATUS_CODE5  = this.dm.nextRow ( OPEN_ID5 );

          }
          if ( Compare.equals ( FLG_DESCALIFICADO, 0 ) ) 
          {
            if ( Compare.equals ( this.dm.getFieldString ( this.dm.get ( "CLIENTES2_RO_DSD" ), "TIPO_REGISTRO" ), "" ) ) 
            {
              this.app.setError ( 1, 6120 );
              this.doReturn ( );
              return; 
            }
            if ( ( Compare.equals ( this.dm.getFieldString ( this.dm.get ( "CLIENTES2_RO_DSD" ), "COD_PARENTESCO_FAM" ), "JEFE" ) ) || ( Compare.equals ( this.dm.getFieldString ( this.dm.get ( "CLIENTES2_RO_DSD" ), "COD_PARENTESCO_FAM" ), "CONY" ) ) ) 
            {
              STATUS_CODE3  = this.dm.reset ( OPEN_ID3 );

              this.dm.setField ( this.dm.get ( "SERVICIOS_LOC2_RO_DSD" ), "SEGURO_SOCIAL_JEFE_FAM", this.app.SS_JEFE_GBL );
              this.dm.setField ( this.dm.get ( "SERVICIOS_LOC2_RO_DSD" ), "SEGURO_SOCIAL_JEFE_SERV", this.app.SS_SERV_GBL );
              this.dm.setField ( this.dm.get ( "SERVICIOS_LOC2_RO_DSD" ), "COD_SERVICIO", this.app.COD_SERV_GBL );
              this.dm.setField ( this.dm.get ( "SERVICIOS_LOC2_RO_DSD" ), "RMO_OFICINA", this.app.RMO_GBL );

              STATUS_CODE3  = this.dm.limitQueryFromBuffer ( OPEN_ID3 );
              STATUS_CODE3  = this.dm.retrieve ( OPEN_ID3 );

              STATUS_CODE3  = this.dm.firstRow ( OPEN_ID3 );

              if ( Compare.equals ( STATUS_CODE3, 0 ) ) 
              {
                if ( Compare.gt ( StringService.toStringValue  ( this.dm.getFieldDate ( this.dm.get ( "SERVICIOS_LOC2_RO_DSD" ), "FCH_AUTORIZACION" ) ), "" ) ) 
                {
                  SERVICIO_STATUS = "CERRAD02";
                  SERVICIO_BENEFICIO = 0;
                  this.app.form ( "DETERMINAR_RECLAMACION_FR" ).setItem ( "BENEFICIOS_CORRECTOS", 0  );
                  this.app.form ( "DETERMINAR_RECLAMACION_FR" ).setItem ( "AJUSTE_PAN", 0  );
                  this.app.form ( "DETERMINAR_RECLAMACION_FR" ).setItem ( "BENEFICIO_CALCULADO", 0  );
                }
              }
            }
            else
            {
              this.app.setError ( 2, 6120 );
              STATUS_CODE  = this.dm.dbClose ( OPEN_ID );

              STATUS_CODE2  = this.dm.dbClose ( OPEN_ID2 );

              STATUS_CODE3  = this.dm.dbClose ( OPEN_ID3 );

              STATUS_CODE5  = this.dm.dbClose ( OPEN_ID5 );

              this.doReturn ( );
              return; 
            }
          }
        }

        STATUS_CODE2  = this.dm.nextRow ( OPEN_ID2 );

      }
    }
    STATUS_CODE  = this.dm.dbClose ( OPEN_ID );

    STATUS_CODE2  = this.dm.dbClose ( OPEN_ID2 );

    STATUS_CODE3  = this.dm.dbClose ( OPEN_ID3 );

    STATUS_CODE5  = this.dm.dbClose ( OPEN_ID5 );

    if ( Compare.equals ( RallyStringService.subString ( this.app.COD_SERV_GBL, 0, 2 ), "PA" ) ) 
    {
      this._condition0 = true;
    }
    else
    {
      this._condition0 = false;
    }
    if ( this._condition0 )
    {
      //DETERMINAR_ELEGIBILIDAD_PAN_3_NOUPD_ADL.exec ( this.app );
    	DETERMINAR_ELEGIBILIDAD_PAN_2.exec(this.app);
      return;
    }

  }


  /**
   *
   */
  protected void step1 ( ParameterSet ps )
  {
    if ( Compare.equals ( RallyStringService.subString ( this.app.COD_SERV_GBL, 0, 2 ), "AE" ) ) 
    {
      this._condition1 = true;
    }
    else
    {
      this._condition1 = false;
    }
    if ( this._condition1 )
    {
      if ( ( Compare.equals ( RallyStringService.subString ( this.app.COD_SERV_GBL, 3, 1 ), "A" ) ) || ( Compare.equals ( RallyStringService.subString ( this.app.COD_SERV_GBL, 3, 1 ), "D" ) ) ) 
      {
        this._condition2 = true;
      }
      else
      {
        this._condition2 = false;
      }
      if ( this._condition2 )
      {
        //DETERMINAR_ELEGIBILIDAD_AE_A2_NOUPD_ADL.exec ( this.app );
    	  DETERMINAR_ELEGIBILIDAD_AE_A_ADL.exec(this.app);
        return;
      }
    }

  }


  /**
   *
   */
  protected void step2 ( ParameterSet ps )
  {
    if ( this._condition1 )    //    if ( Compare.equals ( RallyStringService.subString ( this.app.COD_SERV_GBL, 0, 2 ), "AE" ) ) 
    {
      if ( this._condition2 )    //      if ( ( Compare.equals ( RallyStringService.subString ( this.app.COD_SERV_GBL, 3, 1 ), "A" ) ) || ( Compare.equals ( RallyStringService.subString ( this.app.COD_SERV_GBL, 3, 1 ), "D" ) ) ) 
      {
      }
      if ( ( Compare.equals ( RallyStringService.subString ( this.app.COD_SERV_GBL, 3, 1 ), "B" ) ) || ( Compare.equals ( RallyStringService.subString ( this.app.COD_SERV_GBL, 3, 1 ), "G" ) ) ) 
      {
        this._condition3 = true;
      }
      else
      {
        this._condition3 = false;
      }
      if ( this._condition3 )
      {
        //DETERMINAR_ELEGIBILIDAD_AE_B2_NOUPD_ADL.exec ( this.app );
    	  DETERMINAR_ELEGIBILIDAD_AE_B_ADL.exec(this.app);
        return;
      }
    }

  }


  /**
   *
   */
  protected void step3 ( ParameterSet ps )
  {
    if ( this._condition1 )    //    if ( Compare.equals ( RallyStringService.subString ( this.app.COD_SERV_GBL, 0, 2 ), "AE" ) ) 
    {
      if ( this._condition3 )    //      if ( ( Compare.equals ( RallyStringService.subString ( this.app.COD_SERV_GBL, 3, 1 ), "B" ) ) || ( Compare.equals ( RallyStringService.subString ( this.app.COD_SERV_GBL, 3, 1 ), "G" ) ) ) 
      {
      }
      if ( Compare.equals ( RallyStringService.subString ( this.app.COD_SERV_GBL, 3, 1 ), "T" ) ) 
      {
        this._condition4 = true;
      }
      else
      {
        this._condition4 = false;
      }
      if ( this._condition4 )
      {
        //DETERMINAR_ELEGIBILIDAD_AE_T2_NOUPD_ADL.exec ( this.app );
    	  DETERMINAR_ELEGIBILIDAD_AE_T_ADL.exec(this.app);
        return;
      }
    }

  }


  /**
   *
   */
  protected void step4 ( ParameterSet ps )
  {
    if ( this._condition1 )    //    if ( Compare.equals ( RallyStringService.subString ( this.app.COD_SERV_GBL, 0, 2 ), "AE" ) ) 
    {
      if ( this._condition4 )    //      if ( Compare.equals ( RallyStringService.subString ( this.app.COD_SERV_GBL, 3, 1 ), "T" ) ) 
      {
      }
      if ( Compare.equals ( RallyStringService.subString ( this.app.COD_SERV_GBL, 3, 1 ), "C" ) ) 
      {
        this._condition5 = true;
      }
      else
      {
        this._condition5 = false;
      }
      if ( this._condition5 )
      {
        //DETER_ELEG_AE_C2_NO_UPDATE_ADL.exec ( this.app );
    	  DETERMINAR_ELEGIBILIDAD_AE_C1_ADL.exec(this.app);
        return;
      }
    }

  }


  /**
   *
   */
  protected void step5 ( ParameterSet ps )
  {
    CALCULAR_AJUSTE_BASE_ADL.exec ( this.app );
    return;

  }
}



/* ---------------------------------------------------------------------


     
PROCEDURE DETERMINACION_ELEGIBILIDAD_NO_UPD_ADL;


VAR
        SERV_ID         :       NUMBER;
        STAT_CODE       :       NUMBER;
        OPEN_ID :       NUMBER;
        OPEN_ID2        :       NUMBER;
        OPEN_ID3        :       NUMBER;
        OPEN_ID4        :       NUMBER;
        OPEN_ID5                :       NUMBER;
        STATUS_CODE5    :       NUMBER;
        STATUS_CODE     :       NUMBER;
        STATUS_CODE2    :       NUMBER;
        STATUS_CODE3    :       NUMBER;
        STATUS_CODE4    :       NUMBER;
        CNT_NUCLEO      :       NUMBER;
        FLG_NCAL        :       NUMBER;
        FLG_DESCALIFICADO :     NUMBER;
        SERVICIO_STATUS:        CHAR(8) EXPORT;
        SERVICIO_BENEFICIO:     NUMBER EXPORT;

BEGIN
SET_TRACE();

FLAG_UPD_GBL := 'N';
ANSWER_GBL := 'N';

{MODIFICACION PARA NO PERMITIR LA DETERMINACION DE ELEGIBILIDAD
 PARA SERVICIOS CON STATUS DE CERRADO}
{
IF (SUBSTR(DETERMINAR_RECLAMACION_FR.SERVICIOS_COD_STATUS_SERVICIO,0,4) ='CERR')
 OR
   (SUBSTR(DETERMINAR_RECLAMACION_FR.SERVICIOS_COD_STATUS_SERVICIO,0,4) ='RECH')
   THEN BEGIN
         ERROR(4001);
         RETURN;
        END;
}

SS_JEFE_GBL:=DETERMINAR_RECLAMACION_FR.SEGURO_SOCIAL_JEFE_FAM;
SS_SERV_GBL:=DETERMINAR_RECLAMACION_FR.SEGURO_SOCIAL_JEFE_SERV;
COD_SERV_GBL:=DETERMINAR_RECLAMACION_FR.COD_SERVICIO;
{FCH_SOLIC_SERV_GBL:= 
DETERMINAR_RECLAMACION_FR.SERVICIOS_FCH_SOLICITUD;}

DB_OPEN(CLIENTES2_RO_DSD,OPEN_ID,STATUS_CODE);
DB_OPEN(NUCLEO_READ_LOC_DSD,OPEN_ID2,STATUS_CODE2);
DB_OPEN(SERVICIOS_LOC2_RO_DSD,OPEN_ID3,STATUS_CODE3);
DB_OPEN(DESCALIFICADOS_READ_LOC_DSD,OPEN_ID5,STATUS_CODE5);

{VERIFICA SI EL UNICO MIEMBRO ESTA DESCALIFICADO}
CNT_NUCLEO := 0;
FLG_NCAL := 0;
DB_RESET(OPEN_ID2,STATUS_CODE2);
NUCLEO_READ_LOC_DSD.SEGURO_SOCIAL_JEFE_FAM := SS_JEFE_GBL;
NUCLEO_READ_LOC_DSD.SEGURO_SOCIAL_JEFE_SERV := SS_SERV_GBL;
NUCLEO_READ_LOC_DSD.COD_SERVICIO := COD_SERV_GBL;
NUCLEO_READ_LOC_DSD.RMO_OFICINA := RMO_GBL;
NUCLEO_READ_LOC_DSD.RMO_OFICINA2 := RMO_GBL;
DB_QUERY(OPEN_ID2,STATUS_CODE2);
DB_GET_FIRST(OPEN_ID2,STATUS_CODE2);
WHILE STATUS_CODE2 = 0 DO
BEGIN
        CNT_NUCLEO := CNT_NUCLEO+ 1;
        IF (NUCLEO_READ_LOC_DSD.COD_PARENTESCO_RELACION_SERV = 'NCAL') AND
           (CNT_NUCLEO = 1 ) THEN
        BEGIN
                FLG_NCAL := 1;
        END;
        DB_GET_NEXT(OPEN_ID2,STATUS_CODE2);
END;
IF (CNT_NUCLEO = 1) AND (FLG_NCAL = 1) THEN
BEGIN
        SERVICIO_STATUS := 'CERRAD12';
        SERVICIO_BENEFICIO:=0;
        DETERMINAR_RECLAMACION_FR.BENEFICIO_CALCULADO := 0;
        determinar_reclamacion_fr.beneficios_correctos := 0;
        DETERMINAR_RECLAMACION_FR.AJUSTE_PAN := 0;
        ERROR(2063);
        SET_FAILURE();
        RETURN;
END;
{ EXENCION DEL REGISTRO DE EMPLEO}
IF SUBSTR(COD_SERV_GBL,0,2)='PA' THEN
  BEGIN 
        DB_RESET(OPEN_ID2,STATUS_CODE2);
        NUCLEO_READ_LOC_DSD.SEGURO_SOCIAL_JEFE_FAM := SS_JEFE_GBL;
        NUCLEO_READ_LOC_DSD.SEGURO_SOCIAL_JEFE_SERV := SS_SERV_GBL;
        NUCLEO_READ_LOC_DSD.COD_SERVICIO := COD_SERV_GBL;
        NUCLEO_READ_LOC_DSD.RMO_OFICINA := RMO_GBL;
        NUCLEO_READ_LOC_DSD.RMO_OFICINA2 := RMO_GBL;
        DB_QUERY(OPEN_ID2,STATUS_CODE2);
        DB_GET_FIRST(OPEN_ID2,STATUS_CODE2);
        WHILE STATUS_CODE2 = 0 DO
        BEGIN
                DB_RESET(OPEN_ID,STATUS_CODE);
                CLIENTES2_RO_DSD.SEGURO_SOCIAL_CLIENTE := 
                                NUCLEO_READ_LOC_DSD.SEGURO_SOCIAL_BENEFICIARIO;
                CLIENTES2_RO_DSD.RMO_OFICINA := RMO_GBL;
                DB_QUERY(OPEN_ID,STATUS_CODE);
                DB_GET_FIRST(OPEN_ID,STATUS_CODE);
                IF ((CLIENTES2_RO_DSD.TIPO_REGISTRO = 'VOLU') OR
                    (CLIENTES2_RO_DSD.TIPO_REGISTRO = 'OBLI') OR
                    (CLIENTES2_RO_DSD.TIPO_REGISTRO = '')) AND
                   (CLIENTES2_RO_DSD.ACEPTA_REGISTRO_EMPLEO <> 'S') AND
                    (STATUS_CODE = 0)
                THEN BEGIN
{ VERIFICAR SI ESTA DESCALIFICADO EL CLIENTE }
                DB_RESET(OPEN_ID5,STATUS_CODE5);
                 DESCALIFICADOS_READ_LOC_DSD.SEGURO_SOCIAL_CLIENTE :=
                 NUCLEO_READ_LOC_DSD.SEGURO_SOCIAL_BENEFICIARIO;
                 DESCALIFICADOS_READ_LOC_DSD.COD_SERVICIO:=
                COD_SERV_GBL;   
                DESCALIFICADOS_READ_LOC_DSD.RMO_OFICINA:=RMO_GBL;
                DB_QUERY(OPEN_ID5,STATUS_CODE5);
                DB_GET_FIRST(OPEN_ID5,STATUS_CODE5);
                FLG_DESCALIFICADO := 0;
                WHILE  (FLG_DESCALIFICADO = 0) AND (STATUS_CODE5 = 0) DO
                BEGIN
                   IF DESCALIFICADOS_READ_LOC_DSD.FCH_VENCIMIENTO >= SYSTEM_DATE
 THEN 
                        FLG_DESCALIFICADO := 1;
                   DB_GET_NEXT(OPEN_ID5,STATUS_CODE5);
                END;
                IF FLG_DESCALIFICADO = 0
                   THEN
                  BEGIN
                   IF CLIENTES2_RO_DSD.TIPO_REGISTRO = '' THEN
                    BEGIN
                        error(6120);
                        RETURN;
                    END;
                    IF ((CLIENTES2_RO_DSD.COD_PARENTESCO_FAM = 'JEFE') OR
                       (CLIENTES2_RO_DSD.COD_PARENTESCO_FAM = 'CONY'))
                     THEN
                     BEGIN
                       DB_RESET(OPEN_ID3,STATUS_CODE3);
                       SERVICIOS_LOC2_RO_DSD.SEGURO_SOCIAL_JEFE_FAM := SS_JEFE_G
BL;
                       SERVICIOS_LOC2_RO_DSD.SEGURO_SOCIAL_JEFE_SERV := SS_SERV_
GBL;
                       SERVICIOS_LOC2_RO_DSD.COD_SERVICIO := COD_SERV_GBL;
                       SERVICIOS_LOC2_RO_DSD.RMO_OFICINA := RMO_GBL;
                       DB_QUERY(OPEN_ID3,STATUS_CODE3);
                       DB_GET_FIRST(OPEN_ID3,STATUS_CODE3);
                       IF  (STATUS_CODE3 = 0) THEN
                        BEGIN
                              IF TO_CHAR(SERVICIOS_LOC2_RO_DSD.FCH_AUTORIZACION)
 > '' THEN
                                BEGIN 
                                { error(6110);}

                                  SERVICIO_STATUS := 'CERRAD02';        
                                  SERVICIO_BENEFICIO:=0;        
                                  determinar_reclamacion_fr.beneficios_correctos
 := 0;
                                  DETERMINAR_RECLAMACION_FR.AJUSTE_PAN := 0;
                                  DETERMINAR_RECLAMACION_FR.BENEFICIO_CALCULADO 
:= 0;
                                END;
                        END;
                     END;
                     ELSE
                      BEGIN
                       error(6120);
                        DB_CLOSE(OPEN_ID,STATUS_CODE);
                        DB_CLOSE(OPEN_ID2,STATUS_CODE2);
                        DB_CLOSE(OPEN_ID3,STATUS_CODE3);
                        DB_CLOSE(OPEN_ID5,STATUS_CODE5);
                       RETURN;
                      END;
                     END;
                END;
                DB_GET_NEXT(OPEN_ID2,STATUS_CODE2);
        END;
  END;
DB_CLOSE(OPEN_ID,STATUS_CODE);
DB_CLOSE(OPEN_ID2,STATUS_CODE2);
DB_CLOSE(OPEN_ID3,STATUS_CODE3);
DB_CLOSE(OPEN_ID5,STATUS_CODE5);



IF SUBSTR(COD_SERV_GBL,0,2)='PA'
   THEN CALL DETERMINAR_ELEGIBILIDAD_PAN_3_NOUPD_ADL;

IF SUBSTR(COD_SERV_GBL,0,2)='AE'
   THEN BEGIN
          IF (SUBSTR(COD_SERV_GBL,3,1)='A') OR (SUBSTR(COD_SERV_GBL,3,1)='D')
              THEN
                BEGIN
                        CALL DETERMINAR_ELEGIBILIDAD_AE_A2_NOUPD_ADL;
                END;
          IF (SUBSTR(COD_SERV_GBL,3,1)='B') OR (SUBSTR(COD_SERV_GBL,3,1)='G')
              THEN
                BEGIN
                       CALL DETERMINAR_ELEGIBILIDAD_AE_B2_NOUPD_ADL;
                END;
          IF SUBSTR(COD_SERV_GBL,3,1)='T'
              THEN
                BEGIN
                        CALL DETERMINAR_ELEGIBILIDAD_AE_T2_NOUPD_ADL;
                END;

          IF SUBSTR(COD_SERV_GBL,3,1)='C'
              THEN
                BEGIN
                        CALL DETER_ELEG_AE_C2_NO_UPDATE_ADL;
                END;
        END;

        call CALCULAR_AJUSTE_BASE_ADL;

SET_NOTRACE();
END;

    



--------------------------------------------------------------------- */
