package gov.dlf.logic;


import gov.dlf.external.*;
import gov.dlf.facade.*;
import gov.dlf.presentation.*;


import java.util.*;

import net.maintrend.appmanager.*;
import net.maintrend.datamanager.*;
import net.maintrend.interfaces.*;
import net.maintrend.interlink.*;
import net.maintrend.mdi.*;
import net.maintrend.rallyengine.*;
import net.maintrend.util.*;
import net.maintrend.util.format.*;



/**
 * __Comment
 *
 * Generated by Rally-to-Java Convertor. MainTrend Ltd.
 */
public class TIENE_SERVICIOS_ADL
     extends ADL
{
  // -------------------------------------------------------------------
  // ----------   Class Attributes   -----------------------------------

  /**  */
  public static boolean staticCall = false;



  // -------------------------------------------------------------------
  // ----------   Instance Attributes   --------------------------------

  /**  */
  public SAIC_DMQ_ORA_Application app;
  /**  */
  public RallyDataManager dm = null;



  // -------------------------------------------------------------------
  // ----------   Instance Condition Attributes   ----------------------
 
  public boolean _condition0 = false;
 
  public boolean _condition1 = false;

 

  // -------------------------------------------------------------------
  // ----------   Instance Export Attributes   -------------------------

  public double NUCLEO = 0;

  public double STATUS2 = 0;

  public double COUNTER = 0;

  public double COUNTER2 = 0;

  public double RECLARETRO_OCI = 0;

  public double RECLARETRO_OCI_STAT = 0;



  public String ACTIVOS_FLG = null;

  public String ENCARGADO_FLG = null;

  public String RECLARETRO_FLG = null;

  public String CERRAD14_FLG = null;

  public String COD_STATUS_CLIENTE = null;

  public DataStore TIENE_SERVICIO_ADL_DSD = null;

  public DataStore RECLA_RETRO_RO_DSD = null;



  // -------------------------------------------------------------------
  // ----------   Instance Attributes' Access Methods   ----------------

  
  /**  */
  public static void setNUCLEO  ( RallyApplication __app, Parameter value )
  {
    ( ( TIENE_SERVICIOS_ADL ) __app.getADL ( TIENE_SERVICIOS_ADL.class ) ).NUCLEO = value.getDouble ( );
  }  

  
  /**  */
  public static void setSTATUS2  ( RallyApplication __app, Parameter value )
  {
    ( ( TIENE_SERVICIOS_ADL ) __app.getADL ( TIENE_SERVICIOS_ADL.class ) ).STATUS2 = value.getDouble ( );
  }  

  
  /**  */
  public static void setCOUNTER  ( RallyApplication __app, Parameter value )
  {
    ( ( TIENE_SERVICIOS_ADL ) __app.getADL ( TIENE_SERVICIOS_ADL.class ) ).COUNTER = value.getDouble ( );
  }  

  
  /**  */
  public static void setCOUNTER2  ( RallyApplication __app, Parameter value )
  {
    ( ( TIENE_SERVICIOS_ADL ) __app.getADL ( TIENE_SERVICIOS_ADL.class ) ).COUNTER2 = value.getDouble ( );
  }  

  
  /**  */
  public static void setACTIVOS_FLG  ( RallyApplication __app, Parameter value )
  {
    ( ( TIENE_SERVICIOS_ADL ) __app.getADL ( TIENE_SERVICIOS_ADL.class ) ).ACTIVOS_FLG = value.getString ( );
  }  

  
  /**  */
  public static void setENCARGADO_FLG  ( RallyApplication __app, Parameter value )
  {
    ( ( TIENE_SERVICIOS_ADL ) __app.getADL ( TIENE_SERVICIOS_ADL.class ) ).ENCARGADO_FLG = value.getString ( );
  }  

  
  /**  */
  public static void setRECLARETRO_OCI  ( RallyApplication __app, Parameter value )
  {
    ( ( TIENE_SERVICIOS_ADL ) __app.getADL ( TIENE_SERVICIOS_ADL.class ) ).RECLARETRO_OCI = value.getDouble ( );
  }  

  
  /**  */
  public static void setRECLARETRO_OCI_STAT  ( RallyApplication __app, Parameter value )
  {
    ( ( TIENE_SERVICIOS_ADL ) __app.getADL ( TIENE_SERVICIOS_ADL.class ) ).RECLARETRO_OCI_STAT = value.getDouble ( );
  }  

  
  /**  */
  public static void setRECLARETRO_FLG  ( RallyApplication __app, Parameter value )
  {
    ( ( TIENE_SERVICIOS_ADL ) __app.getADL ( TIENE_SERVICIOS_ADL.class ) ).RECLARETRO_FLG = value.getString ( );
  }  

  
  /**  */
  public static void setCERRAD14_FLG  ( RallyApplication __app, Parameter value )
  {
    ( ( TIENE_SERVICIOS_ADL ) __app.getADL ( TIENE_SERVICIOS_ADL.class ) ).CERRAD14_FLG = value.getString ( );
  }  

  
  /**  */
  public static void setCOD_STATUS_CLIENTE  ( RallyApplication __app, Parameter value )
  {
    ( ( TIENE_SERVICIOS_ADL ) __app.getADL ( TIENE_SERVICIOS_ADL.class ) ).COD_STATUS_CLIENTE = value.getString ( );
  }  
    


  /**  */
  public static String getACTIVOS_FLG  ( RallyApplication __app )
  {
    return ( ( TIENE_SERVICIOS_ADL ) __app.getADL ( TIENE_SERVICIOS_ADL.class ) ).ACTIVOS_FLG;
  }


  /**  */
  public static void setACTIVOS_FLG  ( RallyApplication __app, String value )
  {
    ( ( TIENE_SERVICIOS_ADL ) __app.getADL ( TIENE_SERVICIOS_ADL.class ) ).ACTIVOS_FLG = value;
  }


  /**  */
  public static void setACTIVOS_FLG  ( RallyApplication __app, Object value )
  {
    ( ( TIENE_SERVICIOS_ADL ) __app.getADL ( TIENE_SERVICIOS_ADL.class ) ).ACTIVOS_FLG = ( String ) value;
  }



  /**  */
  public static String getENCARGADO_FLG  ( RallyApplication __app )
  {
    return ( ( TIENE_SERVICIOS_ADL ) __app.getADL ( TIENE_SERVICIOS_ADL.class ) ).ENCARGADO_FLG;
  }


  /**  */
  public static void setENCARGADO_FLG  ( RallyApplication __app, String value )
  {
    ( ( TIENE_SERVICIOS_ADL ) __app.getADL ( TIENE_SERVICIOS_ADL.class ) ).ENCARGADO_FLG = value;
  }


  /**  */
  public static void setENCARGADO_FLG  ( RallyApplication __app, Object value )
  {
    ( ( TIENE_SERVICIOS_ADL ) __app.getADL ( TIENE_SERVICIOS_ADL.class ) ).ENCARGADO_FLG = ( String ) value;
  }



  /**  */
  public static String getRECLARETRO_FLG  ( RallyApplication __app )
  {
    return ( ( TIENE_SERVICIOS_ADL ) __app.getADL ( TIENE_SERVICIOS_ADL.class ) ).RECLARETRO_FLG;
  }


  /**  */
  public static void setRECLARETRO_FLG  ( RallyApplication __app, String value )
  {
    ( ( TIENE_SERVICIOS_ADL ) __app.getADL ( TIENE_SERVICIOS_ADL.class ) ).RECLARETRO_FLG = value;
  }


  /**  */
  public static void setRECLARETRO_FLG  ( RallyApplication __app, Object value )
  {
    ( ( TIENE_SERVICIOS_ADL ) __app.getADL ( TIENE_SERVICIOS_ADL.class ) ).RECLARETRO_FLG = ( String ) value;
  }



  /**  */
  public static String getCERRAD14_FLG  ( RallyApplication __app )
  {
    return ( ( TIENE_SERVICIOS_ADL ) __app.getADL ( TIENE_SERVICIOS_ADL.class ) ).CERRAD14_FLG;
  }


  /**  */
  public static void setCERRAD14_FLG  ( RallyApplication __app, String value )
  {
    ( ( TIENE_SERVICIOS_ADL ) __app.getADL ( TIENE_SERVICIOS_ADL.class ) ).CERRAD14_FLG = value;
  }


  /**  */
  public static void setCERRAD14_FLG  ( RallyApplication __app, Object value )
  {
    ( ( TIENE_SERVICIOS_ADL ) __app.getADL ( TIENE_SERVICIOS_ADL.class ) ).CERRAD14_FLG = ( String ) value;
  }



  /**  */
  public static String getCOD_STATUS_CLIENTE  ( RallyApplication __app )
  {
    return ( ( TIENE_SERVICIOS_ADL ) __app.getADL ( TIENE_SERVICIOS_ADL.class ) ).COD_STATUS_CLIENTE;
  }


  /**  */
  public static void setCOD_STATUS_CLIENTE  ( RallyApplication __app, String value )
  {
    ( ( TIENE_SERVICIOS_ADL ) __app.getADL ( TIENE_SERVICIOS_ADL.class ) ).COD_STATUS_CLIENTE = value;
  }


  /**  */
  public static void setCOD_STATUS_CLIENTE  ( RallyApplication __app, Object value )
  {
    ( ( TIENE_SERVICIOS_ADL ) __app.getADL ( TIENE_SERVICIOS_ADL.class ) ).COD_STATUS_CLIENTE = ( String ) value;
  }



  /**  */
  public static DataStore getTIENE_SERVICIO_ADL_DSD  ( RallyApplication __app )
  {
    return ( ( TIENE_SERVICIOS_ADL ) __app.getADL ( TIENE_SERVICIOS_ADL.class ) ).TIENE_SERVICIO_ADL_DSD;
  }


  /**  */
  public static void setTIENE_SERVICIO_ADL_DSD  ( RallyApplication __app, DataStore value )
  {
    ( ( TIENE_SERVICIOS_ADL ) __app.getADL ( TIENE_SERVICIOS_ADL.class ) ).TIENE_SERVICIO_ADL_DSD = value;
  }


  /**  */
  public static void setTIENE_SERVICIO_ADL_DSD  ( RallyApplication __app, Object value )
  {
    ( ( TIENE_SERVICIOS_ADL ) __app.getADL ( TIENE_SERVICIOS_ADL.class ) ).TIENE_SERVICIO_ADL_DSD = ( DataStore ) value;
  }



  /**  */
  public static DataStore getRECLA_RETRO_RO_DSD  ( RallyApplication __app )
  {
    return ( ( TIENE_SERVICIOS_ADL ) __app.getADL ( TIENE_SERVICIOS_ADL.class ) ).RECLA_RETRO_RO_DSD;
  }


  /**  */
  public static void setRECLA_RETRO_RO_DSD  ( RallyApplication __app, DataStore value )
  {
    ( ( TIENE_SERVICIOS_ADL ) __app.getADL ( TIENE_SERVICIOS_ADL.class ) ).RECLA_RETRO_RO_DSD = value;
  }


  /**  */
  public static void setRECLA_RETRO_RO_DSD  ( RallyApplication __app, Object value )
  {
    ( ( TIENE_SERVICIOS_ADL ) __app.getADL ( TIENE_SERVICIOS_ADL.class ) ).RECLA_RETRO_RO_DSD = ( DataStore ) value;
  }




  /**  */
  public static double getNUCLEO  ( RallyApplication __app )
  {
    return ( ( TIENE_SERVICIOS_ADL ) __app.getADL ( TIENE_SERVICIOS_ADL.class ) ).NUCLEO;
  }


  /**  */
  public static Double getNUCLEODouble ( RallyApplication __app )
  {
    return new Double ( ( ( TIENE_SERVICIOS_ADL ) __app.getADL ( TIENE_SERVICIOS_ADL.class ) ).NUCLEO );
  }


  /**  */
  public static void setNUCLEO  ( RallyApplication __app, double value )
  {
    ( ( TIENE_SERVICIOS_ADL ) __app.getADL ( TIENE_SERVICIOS_ADL.class ) ).NUCLEO = value;
  }


  /**  */
  public static void setNUCLEO  ( RallyApplication __app, Object value )
  {
    ( ( TIENE_SERVICIOS_ADL ) __app.getADL ( TIENE_SERVICIOS_ADL.class ) ).NUCLEO = ( ( Double ) value ).doubleValue ( );
  }


  /**  */
  public static double getSTATUS2  ( RallyApplication __app )
  {
    return ( ( TIENE_SERVICIOS_ADL ) __app.getADL ( TIENE_SERVICIOS_ADL.class ) ).STATUS2;
  }


  /**  */
  public static Double getSTATUS2Double ( RallyApplication __app )
  {
    return new Double ( ( ( TIENE_SERVICIOS_ADL ) __app.getADL ( TIENE_SERVICIOS_ADL.class ) ).STATUS2 );
  }


  /**  */
  public static void setSTATUS2  ( RallyApplication __app, double value )
  {
    ( ( TIENE_SERVICIOS_ADL ) __app.getADL ( TIENE_SERVICIOS_ADL.class ) ).STATUS2 = value;
  }


  /**  */
  public static void setSTATUS2  ( RallyApplication __app, Object value )
  {
    ( ( TIENE_SERVICIOS_ADL ) __app.getADL ( TIENE_SERVICIOS_ADL.class ) ).STATUS2 = ( ( Double ) value ).doubleValue ( );
  }


  /**  */
  public static double getCOUNTER  ( RallyApplication __app )
  {
    return ( ( TIENE_SERVICIOS_ADL ) __app.getADL ( TIENE_SERVICIOS_ADL.class ) ).COUNTER;
  }


  /**  */
  public static Double getCOUNTERDouble ( RallyApplication __app )
  {
    return new Double ( ( ( TIENE_SERVICIOS_ADL ) __app.getADL ( TIENE_SERVICIOS_ADL.class ) ).COUNTER );
  }


  /**  */
  public static void setCOUNTER  ( RallyApplication __app, double value )
  {
    ( ( TIENE_SERVICIOS_ADL ) __app.getADL ( TIENE_SERVICIOS_ADL.class ) ).COUNTER = value;
  }


  /**  */
  public static void setCOUNTER  ( RallyApplication __app, Object value )
  {
    ( ( TIENE_SERVICIOS_ADL ) __app.getADL ( TIENE_SERVICIOS_ADL.class ) ).COUNTER = ( ( Double ) value ).doubleValue ( );
  }


  /**  */
  public static double getCOUNTER2  ( RallyApplication __app )
  {
    return ( ( TIENE_SERVICIOS_ADL ) __app.getADL ( TIENE_SERVICIOS_ADL.class ) ).COUNTER2;
  }


  /**  */
  public static Double getCOUNTER2Double ( RallyApplication __app )
  {
    return new Double ( ( ( TIENE_SERVICIOS_ADL ) __app.getADL ( TIENE_SERVICIOS_ADL.class ) ).COUNTER2 );
  }


  /**  */
  public static void setCOUNTER2  ( RallyApplication __app, double value )
  {
    ( ( TIENE_SERVICIOS_ADL ) __app.getADL ( TIENE_SERVICIOS_ADL.class ) ).COUNTER2 = value;
  }


  /**  */
  public static void setCOUNTER2  ( RallyApplication __app, Object value )
  {
    ( ( TIENE_SERVICIOS_ADL ) __app.getADL ( TIENE_SERVICIOS_ADL.class ) ).COUNTER2 = ( ( Double ) value ).doubleValue ( );
  }


  /**  */
  public static double getRECLARETRO_OCI  ( RallyApplication __app )
  {
    return ( ( TIENE_SERVICIOS_ADL ) __app.getADL ( TIENE_SERVICIOS_ADL.class ) ).RECLARETRO_OCI;
  }


  /**  */
  public static Double getRECLARETRO_OCIDouble ( RallyApplication __app )
  {
    return new Double ( ( ( TIENE_SERVICIOS_ADL ) __app.getADL ( TIENE_SERVICIOS_ADL.class ) ).RECLARETRO_OCI );
  }


  /**  */
  public static void setRECLARETRO_OCI  ( RallyApplication __app, double value )
  {
    ( ( TIENE_SERVICIOS_ADL ) __app.getADL ( TIENE_SERVICIOS_ADL.class ) ).RECLARETRO_OCI = value;
  }


  /**  */
  public static void setRECLARETRO_OCI  ( RallyApplication __app, Object value )
  {
    ( ( TIENE_SERVICIOS_ADL ) __app.getADL ( TIENE_SERVICIOS_ADL.class ) ).RECLARETRO_OCI = ( ( Double ) value ).doubleValue ( );
  }


  /**  */
  public static double getRECLARETRO_OCI_STAT  ( RallyApplication __app )
  {
    return ( ( TIENE_SERVICIOS_ADL ) __app.getADL ( TIENE_SERVICIOS_ADL.class ) ).RECLARETRO_OCI_STAT;
  }


  /**  */
  public static Double getRECLARETRO_OCI_STATDouble ( RallyApplication __app )
  {
    return new Double ( ( ( TIENE_SERVICIOS_ADL ) __app.getADL ( TIENE_SERVICIOS_ADL.class ) ).RECLARETRO_OCI_STAT );
  }


  /**  */
  public static void setRECLARETRO_OCI_STAT  ( RallyApplication __app, double value )
  {
    ( ( TIENE_SERVICIOS_ADL ) __app.getADL ( TIENE_SERVICIOS_ADL.class ) ).RECLARETRO_OCI_STAT = value;
  }


  /**  */
  public static void setRECLARETRO_OCI_STAT  ( RallyApplication __app, Object value )
  {
    ( ( TIENE_SERVICIOS_ADL ) __app.getADL ( TIENE_SERVICIOS_ADL.class ) ).RECLARETRO_OCI_STAT = ( ( Double ) value ).doubleValue ( );
  }



  // -------------------------------------------------------------------
  // ----------   Methods   --------------------------------------------

  /**
   * 
   * @param __app
   * @return
   */
  public static TIENE_SERVICIOS_ADL get ( RallyApplication __app )
  {
    TIENE_SERVICIOS_ADL adl = new TIENE_SERVICIOS_ADL ( );
    __app.register ( adl, "TIENE_SERVICIOS_ADL" );
    __app.setADL ( TIENE_SERVICIOS_ADL.class, adl ); 
    adl.setApplication ( __app );
    return adl;
  }


  /**
   *
   * @param __app
   * @param ps
   *
   * @return
   */
  public static void exec ( RallyApplication __app, ParameterSet ps )
  {
    TIENE_SERVICIOS_ADL.get ( __app ).process ( ps );
  }


  /**
   *
   * @param __app
   *
   * @return
   */
  public static void exec ( RallyApplication __app )
  {
    ParameterSet ps = null;
    TIENE_SERVICIOS_ADL.exec ( __app, ps );
  }


  /**
   * Overrides the ancestor's method
   * 
   * @param __app
   */
  public void setApplication ( RallyApplication __app )
  {
    this.app = ( SAIC_DMQ_ORA_Application ) __app;
    if ( this.app != null )
    {
      this.dm = ( RallyDataManager ) this.app.getDataManager ( );
    }
  }


  /**
   * Overrides the ancestor's method
   * 
   * @param parms
   */
  public void execute ( ParameterSet parms )
  {
    this.process ( parms );
  }




  /**
   *
   */
  protected void doReturn ( )
  {
    this.unregister ( );
  }


  /**
   *
   */
  public void unregister ( )
  {
    this.app.unregister ( this );
    IRegisteredObject rObj = this.app.get ( "TIENE_SERVICIOS_ADL" );
    if ( rObj != null && rObj instanceof TIENE_SERVICIOS_ADL )
    {
      this.app.setADL ( TIENE_SERVICIOS_ADL.class, ( TIENE_SERVICIOS_ADL ) rObj );
    }
  }


  /**
   * Overrides the ancestor's method
   * 
   * @param ps
   */
  protected void process ( ParameterSet ps )
  {
    Debug.println ( Debug.TRACE, "TIENE_SERVICIOS_ADL Step " + this.currentStep );
    super.process ( ps );
    switch ( this.currentStep ) 
    {
      case 0:  { this.currentStep ++; this.step0 ( this.keyParms ); break; }
      case 1:  { this.currentStep ++; this.step1 ( this.keyParms ); break; }
      case 2:  { this.currentStep ++; this.step2 ( this.keyParms ); break; }
      default: 
      { 
        this.currentStep = 0;
        Debug.println ( Debug.TRACE, "TIENE_SERVICIOS_ADL ended" );
        this.unregister ( );
        break;
      }
    }
    if ( this.currentStep > 0 ) this.app.goOn ( );
  }



  /**
   *
   */
  protected void step0 ( ParameterSet ps )
  {

    COUNTER = 0;
    COUNTER2 = 0;
    ACTIVOS_FLG = "N";
    ENCARGADO_FLG = "N";
    CERRAD14_FLG = "N";
    RECLARETRO_FLG = "N";
    COD_STATUS_CLIENTE = " ";
    this.app.ANSWER_GBL = "N";
    this.app.RETURN_TO_FLAG_GBL = 25;
    TIENE_SERVICIO_ADL_DSD = this.dm.create ( "TIENE_SERVICIO_ADL_DSD" );
    NUCLEO = TIENE_SERVICIO_ADL_DSD.getId ( );
    STATUS2 = RallyDataStoreException.getDefault ( );
    RECLA_RETRO_RO_DSD = this.dm.create ( "RECLA_RETRO_RO_DSD" );
    RECLARETRO_OCI = RECLA_RETRO_RO_DSD.getId ( );
    RECLARETRO_OCI_STAT = RallyDataStoreException.getDefault ( );

    STATUS2  = this.dm.reset ( NUCLEO );

    this.dm.setField ( this.dm.get ( "TIENE_SERVICIO_ADL_DSD" ), "SEGURO_SOCIAL_BENEFICIARIO", this.app.form ( "SOLIC_SERV_COMP_FAMILIAR_FR" ).getDoubleItem ( "SEGURO_SOCIAL_CLIENTE" ));
    this.dm.setField ( this.dm.get ( "TIENE_SERVICIO_ADL_DSD" ), "RMO_OFICINA", this.app.RMO_GBL );
    this.dm.setField ( this.dm.get ( "TIENE_SERVICIO_ADL_DSD" ), "RMO_OFICINA2", this.app.RMO_GBL );

    STATUS2  = this.dm.limitQueryFromBuffer ( NUCLEO );
    STATUS2  = this.dm.retrieve ( NUCLEO );

    STATUS2  = this.dm.firstRow ( NUCLEO );

    while ( ( Compare.equals ( STATUS2, 0 ) ) && ( Compare.equals ( ACTIVOS_FLG, "N" ) )  ) 
    {
      COUNTER = MathService.plus ( COUNTER, 1  );
      if ( ( ( ! Compare.equals ( RallyStringService.subString ( this.dm.getFieldString ( this.dm.get ( "TIENE_SERVICIO_ADL_DSD" ), "COD_STATUS_SERVICIO" ), 0, 4 ), "CERR" ) ) && ( ! Compare.equals ( RallyStringService.subString ( this.dm.getFieldString ( this.dm.get ( "TIENE_SERVICIO_ADL_DSD" ), "COD_STATUS_SERVICIO" ), 0, 4 ), "RECH" ) )  ) || ( Compare.equals ( this.dm.getFieldString ( this.dm.get ( "TIENE_SERVICIO_ADL_DSD" ), "COD_STATUS_SERVICIO" ), "CERRAD14" ) ) || ( Compare.equals ( COD_STATUS_CLIENTE, "TRANSFER" ) ) ) 
      {
        ACTIVOS_FLG = "Y";
      }
      if ( Compare.equals ( this.dm.getFieldString ( this.dm.get ( "TIENE_SERVICIO_ADL_DSD" ), "COD_STATUS_SERVICIO" ), "CERRAD14" ) ) 
      {
        CERRAD14_FLG = "Y";
      }

      STATUS2  = this.dm.nextRow ( NUCLEO );

    }
    if ( Compare.equals ( ACTIVOS_FLG, "N" ) ) 
    {
      RECLARETRO_OCI_STAT  = this.dm.reset ( RECLARETRO_OCI );

      this.dm.setField ( this.dm.get ( "RECLA_RETRO_RO_DSD" ), "SEGURO_SOCIAL_JEFE_SERV", this.app.SSN_GBL );

      RECLARETRO_OCI_STAT  = this.dm.limitQueryFromBuffer ( RECLARETRO_OCI );
      RECLARETRO_OCI_STAT  = this.dm.retrieve ( RECLARETRO_OCI );

      RECLARETRO_OCI_STAT  = this.dm.firstRow ( RECLARETRO_OCI );

      while ( ( Compare.equals ( RECLARETRO_OCI_STAT, 0 ) ) && ( Compare.equals ( ACTIVOS_FLG, "N" ) )   )
      {
        if ( ( ( Compare.equals ( this.dm.getFieldString ( this.dm.get ( "RECLA_RETRO_RO_DSD" ), "ACCION" ), "RECL" ) ) || ( Compare.equals ( this.dm.getFieldString ( this.dm.get ( "RECLA_RETRO_RO_DSD" ), "ACCION" ), "RETR" ) ) || ( Compare.equals ( this.dm.getFieldString ( this.dm.get ( "RECLA_RETRO_RO_DSD" ), "ACCION" ), "RREC" ) ) || ( Compare.equals ( this.dm.getFieldString ( this.dm.get ( "RECLA_RETRO_RO_DSD" ), "ACCION" ), "RRET" ) ) ) && ! ( ( Compare.equals ( this.dm.getFieldString ( this.dm.get ( "RECLA_RETRO_RO_DSD" ), "STATUS" ), "SALDADA" ) ) || ( Compare.equals ( this.dm.getFieldString ( this.dm.get ( "RECLA_RETRO_RO_DSD" ), "STATUS" ), "PAGADO" ) ) || ( Compare.equals ( this.dm.getFieldString ( this.dm.get ( "RECLA_RETRO_RO_DSD" ), "STATUS" ), "SALDRETR" ) ) || ( Compare.equals ( this.dm.getFieldString ( this.dm.get ( "RECLA_RETRO_RO_DSD" ), "STATUS" ), "NOPRODT" ) ) || ( Compare.equals ( this.dm.getFieldString ( this.dm.get ( "RECLA_RETRO_RO_DSD" ), "STATUS" ), "NPPRODT" ) ) || ( Compare.equals ( this.dm.getFieldString ( this.dm.get ( "RECLA_RETRO_RO_DSD" ), "STATUS" ), "NOPROCRE" ) ) || ( Compare.equals ( this.dm.getFieldString ( this.dm.get ( "RECLA_RETRO_RO_DSD" ), "STATUS" ), "NOPROC10" ) ) || ( Compare.equals ( this.dm.getFieldString ( this.dm.get ( "RECLA_RETRO_RO_DSD" ), "STATUS" ), "COMPRECL" ) ) || ( Compare.equals ( this.dm.getFieldString ( this.dm.get ( "RECLA_RETRO_RO_DSD" ), "STATUS" ), "DESESTIM" ) ) )  ) 
        {
          RECLARETRO_FLG = "Y";
          ACTIVOS_FLG = "Y";
        }

        RECLARETRO_OCI_STAT  = this.dm.nextRow ( RECLARETRO_OCI );

      }
    }
    if ( Compare.equals ( ACTIVOS_FLG, "N" ) ) 
    {
      SOLIC_SERV_COMP_FAM_BEF_DELETE_ADL.setTIENE_SERVICIO ( this.app, "F" );
      this.doReturn ( );
      return; 
    }
    else
    {
      SOLIC_SERV_COMP_FAM_BEF_DELETE_ADL.setTIENE_SERVICIO ( this.app, "T" );
      if ( Compare.equals ( COD_STATUS_CLIENTE, "TRANSFER" ) ) 
      {
        this.app.setError ( 0, 2775 );
      }
      else if ( Compare.equals ( RECLARETRO_FLG, "Y" )  )
      {
        this._condition0 = true;
      }
      else
      {
        this._condition0 = false;
      }
      if ( this._condition0 )
      {
        IRegisteredObject iro = null;
        iro = this.app.get ( "SERVICIOS_CLIENTE_PKT" );
        if ( iro != null )
        {
          this.app.unregister ( iro, false );
        }
        iro = this.app.get ( "SERVICIOS_CLIENTE_FRM" );
        if ( iro != null )
        {
          this.app.unregister ( iro, false );
        }
        this.app.setError ( 1, 2777 );
        DESEA_MIEMBRO_RECLARETRO_MENU.exec ( this.app );
        return;
      }
    }

  }


  /**
   *
   */
  protected void step1 ( ParameterSet ps )
  {
    if ( Compare.equals ( ACTIVOS_FLG, "N" ) ) 
    {
    }
    else
    {
      if ( Compare.equals ( COD_STATUS_CLIENTE, "TRANSFER" ) ) 
      {
      }
      else if ( this._condition0 )    //      else if ( Compare.equals ( RECLARETRO_FLG, "Y" )  )
      {
        if ( Compare.equals ( this.app.ANSWER_GBL, "Y" ) ) 
        {
          SOLIC_SERV_COMP_FAM_BEF_DELETE_ADL.setTIENE_SERVICIO ( this.app, "F" );
        }
        else
        {
          SOLIC_SERV_COMP_FAM_BEF_DELETE_ADL.setTIENE_SERVICIO ( this.app, "T" );
        }
      }
      else if ( Compare.equals ( CERRAD14_FLG, "Y" ) ) 
      {
        this._condition1 = true;
      }
      else
      {
        this._condition1 = false;
      }
      if ( this._condition1 )
      {
        IRegisteredObject iro = null;
        iro = this.app.get ( "SERVICIOS_CLIENTE_PKT" );
        if ( iro != null )
        {
          this.app.unregister ( iro, false );
        }
        iro = this.app.get ( "SERVICIOS_CLIENTE_FRM" );
        if ( iro != null )
        {
          this.app.unregister ( iro, false );
        }
        this.app.setError ( 2, 2778 );
        DESEA_MIEMBRO_CERRAD14_MENU.exec ( this.app );
        return;
      }
    }

  }


  /**
   *
   */
  protected void step2 ( ParameterSet ps )
  {
    if ( Compare.equals ( ACTIVOS_FLG, "N" ) ) 
    {
    }
    else
    {
      if ( Compare.equals ( COD_STATUS_CLIENTE, "TRANSFER" ) ) 
      {
      }
      else if ( this._condition0 )    //      else if ( Compare.equals ( RECLARETRO_FLG, "Y" )  )
      {
      }
      else if ( this._condition1 )    //      else if ( Compare.equals ( CERRAD14_FLG, "Y" ) ) 
      {
        if ( Compare.equals ( this.app.ANSWER_GBL, "Y" ) ) 
        {
          SOLIC_SERV_COMP_FAM_BEF_DELETE_ADL.setTIENE_SERVICIO ( this.app, "F" );
        }
        else
        {
          SOLIC_SERV_COMP_FAM_BEF_DELETE_ADL.setTIENE_SERVICIO ( this.app, "T" );
        }
      }
      else
      {
        this.app.setError ( 3, 2755 );
      }
      this.doReturn ( );
      return; 
    }
    STATUS2  = this.dm.dbClose ( NUCLEO );

    RECLARETRO_OCI_STAT  = this.dm.dbClose ( RECLARETRO_OCI );

  }
}



/* ---------------------------------------------------------------------


     
PROCEDURE TIENE_SERVICIOS_ADL;
VAR

        nucleo                  :       number;
        status2                 :       number;
        counter                 :       number;
        counter2                :       number;
        activos_flg             :       char(1);
        encargado_flg           :       char(1);
        reclaretro_OCI          :       number;
        reclaretro_oci_stat     :       number;
        RECLARETRO_FLG          :       CHAR(1);
        cerrad14_flg            :       char(1);
        cod_status_cliente      :       char(10);

BEGIN
SET_TRACE();
counter := 0;
counter2 := 0;
activos_flg := 'N';
encargado_flg := 'N';
cerrad14_flg := 'N';
RECLARETRO_FLG := 'N';
cod_status_cliente := ' ';
ANSWER_GBL:='N';
RETURN_TO_FLAG_GBL := 25;
{ VERIFICACION DE SERVICIOS ACTIVOS PARA UN CLIENTE }

db_open(TIENE_servicio_adl_dsd,nucleo,status2);
db_open(RECLA_RETRO_RO_DSD,reclaretro_oci,reclaretro_oci_stat);

db_reset(nucleo,status2);
tiene_servicio_adl_dsd.SEGURO_SOCIAL_BENEFICIARIO := 
SOLIC_SERV_COMP_FAMILIAR_FR.SEGURO_SOCIAL_CLIENTE;
TIENE_SERVICIO_ADL_DSD.RMO_OFICINA:=RMO_GBL;
TIENE_SERVICIO_ADL_DSD.RMO_OFICINA2:=RMO_GBL;

debug_log(to_char(tiene_servicio_adl_dsd.SEGURO_SOCIAL_BENEFICIARIO));

db_query(nucleo,status2);

db_get_first(nucleo,status2);

    while((status2 = 0) and (activos_flg ='N')) do
        begin
        counter := counter + 1;
        if ((substr(tiene_servicio_adl_dsd.COD_STATUS_SERVICIO,0,4)<> 'CERR')
         and  (substr(tiene_servicio_adl_dsd.COD_STATUS_SERVICIO,0,4)<> 'RECH'))
         or (tiene_servicio_adl_dsd.COD_STATUS_SERVICIO = 'CERRAD14')
         or (cod_status_cliente = 'TRANSFER')
        Then activos_flg := 'Y';
        if (tiene_servicio_adl_dsd.COD_STATUS_SERVICIO = 'CERRAD14')
        then cerrad14_flg := 'Y'; 
         
         debug_log(to_char(counter));
         debug_log(activos_flg);
        db_get_next(nucleo,status2);
        end;{whilein-end}

         debug_log(to_char(counter));
         debug_log(activos_flg);

{ VERIFICAR SI EXISTE CLIENTE COMO ENCARGADO DE SERVICIO }
{
db_reset(nucleo,status2);
tiene_servicio_adl_dsd.SEGURO_SOCIAL_JEFE_SERV :=
SOLIC_SERV_COMP_FAMILIAR_FR.SEGURO_SOCIAL_CLIENTE;
TIENE_SERVICIO_ADL_DSD.RMO_OFICINA:=RMO_GBL;
TIENE_SERVICIO_ADL_DSD.RMO_OFICINA2:=RMO_GBL;

db_query(nucleo,status2);

db_get_first(nucleo,status2);

    while((status2 = 0) and (encargado_flg ='N')) do
        begin
             counter2 := counter2 + 1;
             if ((substr(tiene_servicio_adl_dsd.COD_STATUS_SERVICIO,0,4)<> 'CERR
') or
                (substr(tiene_servicio_adl_dsd.COD_STATUS_SERVICIO,0,4)<> 'RECH'
)) 
                or (tiene_servicio_adl_dsd.COD_STATUS_SERVICIO = 'CERRAD14')
                or (cod_status_cliente = 'TRANSFER')
             Then encargado_flg := 'Y';
             if (tiene_servicio_adl_dsd.COD_STATUS_SERVICIO = 'CERRAD14')
             then cerrad14_flg := 'Y'; 
              db_get_next(nucleo,status2);
        end;
}


if (activos_flg = 'N')  then
    begin
        DB_RESET(reclaretro_oci,reclaretro_oci_stat);
        RECLA_RETRO_RO_DSD.SEGURO_SOCIAL_JEFE_serv:=ssn_gbl;
        DB_QUERY(reclaretro_oci,reclaretro_oci_stat);
        DB_GET_FIRST(reclaretro_oci,reclaretro_oci_stat);
        WHILE  (reclaretro_oci_stat = 0)
         AND (activos_flg = 'N') DO
        BEGIN
          IF ((RECLA_RETRO_RO_DSD.ACCION = 'RECL') OR
              (RECLA_RETRO_RO_DSD.ACCION ='RETR') OR
              (RECLA_RETRO_RO_DSD.ACCION = 'RREC') OR
              (RECLA_RETRO_RO_DSD.ACCION = 'RRET')) 
             AND NOT
              ((RECLA_RETRO_RO_DSD.STATUS = 'SALDADA') OR
               (RECLA_RETRO_RO_DSD.STATUS = 'PAGADO') OR
               (RECLA_RETRO_RO_DSD.STATUS = 'SALDRETR') OR 
               (RECLA_RETRO_RO_DSD.STATUS = 'NOPRODT') OR
               (RECLA_RETRO_RO_DSD.STATUS = 'NPPRODT') OR
               (RECLA_RETRO_RO_DSD.STATUS = 'NOPROCRE') OR
               (RECLA_RETRO_RO_DSD.STATUS = 'NOPROC10') OR
               (RECLA_RETRO_RO_DSD.STATUS = 'COMPRECL') OR             
               (RECLA_RETRO_RO_DSD.STATUS = 'DESESTIM'))                  
           THEN
             begin
                     RECLARETRO_FLG := 'Y';
                     activos_flg := 'Y';
             end;
          DB_GET_NEXT(reclaretro_oci,reclaretro_oci_stat);
        END;
    END;



if (activos_flg = 'N') then
begin
SOLIC_SERV_COMP_FAM_BEF_DELETE_ADL.TIENE_SERVICIO := 'F';
RETURN;
END;
ELSE begin
SOLIC_SERV_COMP_FAM_BEF_DELETE_ADL.TIENE_SERVICIO := 'T';

IF (cod_status_cliente ='TRANSFER') THEN                
           ERROR(2775);
ELSE
         IF RECLARETRO_FLG = 'Y' THEN
           begin
            ERROR(2777);
            CALL DESEA_MIEMBRO_RECLARETRO_MENU;
            IF ANSWER_GBL = 'Y' THEN
                    SOLIC_SERV_COMP_FAM_BEF_DELETE_ADL.TIENE_SERVICIO := 'F';
            ELSE
                    SOLIC_SERV_COMP_FAM_BEF_DELETE_ADL.TIENE_SERVICIO := 'T';
           end;
          ELSE
             IF ( cerrad14_flg = 'Y')  THEN
                begin
                    ERROR (2778);
                    CALL DESEA_MIEMBRO_CERRAD14_MENU;
                    IF ANSWER_GBL = 'Y' THEN
                           SOLIC_SERV_COMP_FAM_BEF_DELETE_ADL.TIENE_SERVICIO := 
'F';
                    ELSE
                           SOLIC_SERV_COMP_FAM_BEF_DELETE_ADL.TIENE_SERVICIO := 
'T';
                end;
             ELSE
                  ERROR(2755);                           

return;
end;
                 
db_close(nucleo,status2);
db_close(reclaretro_oci,reclaretro_oci_stat);


SET_NOTRACE();
END;
    

    



--------------------------------------------------------------------- */
