package gov.dlf.logic;


import net.maintrend.interlink.*;
import net.maintrend.rallyengine.*;



/**
 * 
 *
 * Generated by Rally-to-Java Convertor. MainTrend Ltd.
 */
public class PLAN_TRABAJA_ALIST 
     extends RallyEngineObject 
{
  // -------------------------------------------------------------------
  // ----------   Class Attributes   -----------------------------------

  /**  */
  protected static PLAN_TRABAJA_ALIST actionList = null;



  // -------------------------------------------------------------------
  // ----------   Constructors   ---------------------------------------

  /**
   *
   */
  public PLAN_TRABAJA_ALIST ( )
  {
  }



  // -------------------------------------------------------------------
  // ----------   Methods   --------------------------------------------

  /**
   * 
   * @param __app
   * @return
   */
  public static PLAN_TRABAJA_ALIST get ( RallyApplication __app )
  {
    actionList = new PLAN_TRABAJA_ALIST ( );
    __app.register ( actionList, "PLAN_TRABAJA_ALIST" );
    actionList.setApplication ( __app );
    return actionList;
  }


  /**
   *
   * @param __app
   * @param ps
   *
   * @return
   */
  public static void exec ( RallyApplication __app, ParameterSet ps )
  {
    PLAN_TRABAJA_ALIST.get ( __app ).execute ( ps );
    __app.unregister ( actionList );
  }


  /**
   *
   * @param __app
   *
   * @return
   */
  public static void exec ( RallyApplication __app )
  {
    ParameterSet ps = null;
    PLAN_TRABAJA_ALIST.exec ( __app, ps );
  }



  // -------------------------------------------------------------------
  // ----------   IRegisteredObject implementation   -------------------

  /**
   *
   */
  @Override
public void execute ( ParameterSet param )
  {
    FormSheet sheet = this.app.formSheet ( "CONTROL_PLAN_RPT_PKT" );
    String html = this.app.getPrintHtml ( sheet.getModel ( ) );
    this.app.unregister ( sheet );
    this.app.registerClientContent ( html, "printStr" );
  }
}
