package gov.dlf.logic;


import gov.dlf.facade.*;
import net.maintrend.appmanager.*;
import net.maintrend.interlink.*;
import net.maintrend.interfaces.*;
import net.maintrend.rallyengine.*;
import net.maintrend.util.*;



/**
 * 
 *
 * Generated by Rally-to-Java Convertor. MainTrend Ltd.
 */
public class REPORT_9_4_PPKT10 
  implements IRegisteredObject 
{
  // -------------------------------------------------------------------
  // ----------   Instance Attributes   --------------------------------

  /**  */
  public ParameterSet parms;
  /**  */
  public SAIC_DMQ_ORA_Application app;



  // -------------------------------------------------------------------
  // ----------   Constructor   ----------------------------------------

  /**
   *
   */
  public REPORT_9_4_PPKT10 ( )
  {
    this.parms = new ParameterSet ( );
  }



  // -------------------------------------------------------------------
  // ----------   Class Methods   --------------------------------------

  /**
   *
   */
  public static REPORT_9_4_PPKT10 get ( RallyApplication __app )
  {
    REPORT_9_4_PPKT10 pp = ( REPORT_9_4_PPKT10 ) __app.getNewInstance ( "REPORT_9_4_PPKT10" );
    return pp;
  }


  /**
   * 
   * @param __app
   * @return
   */
  public static boolean exec ( RallyApplication __app )
  {
    REPORT_9_4_PPKT10 pp = ( REPORT_9_4_PPKT10 ) __app.getNewInstance ( "REPORT_9_4_PPKT10" );
    pp.execute ( __app, null );
    return true;
  }


  /**
   * 
   * @param __app
   * @return
   */
  public static boolean exec ( RallyApplication __app, ParameterSet ps )
  {
    return REPORT_9_4_PPKT10.exec ( __app );
  }



  // -------------------------------------------------------------------
  // ----------   IRegisteredObject implementation   -------------------

  /**
   * 
   * @param rApp
   */
  @Override
public void setApplication ( Application rApp )
  {
    if ( rApp != null ) this.app = ( SAIC_DMQ_ORA_Application ) rApp;
  }


  /**
   * 
   * @return
   */
  @Override
public boolean isSelfClosing ( )
  {
    return true;
  }


  /**
   *
   */
  @Override
public ParameterSet getParameters ( )
  {
    return this.parms;
  }


  /**
   *
   */
  @Override
public void setParameters ( ParameterSet value )
  {
    this.parms = value;
  }


  /**
   *
   */
  @Override
public void execute ( ParameterSet ps )
  {
    Debug.println ( Debug.TRACE, "REPORT_9_4_PPKT10" );
    this.prepareParms ( );
    ACTUALIZA_NOTIFICACIONES_ADL.exec ( this.app, this.parms );
    this.returnParms  ( );
    this.app.unregister ( this, false );
  }


  /**
   * Occurs just after removing this object from the application registry
   */
  @Override
public void halt ( )
  {
  }



  // -------------------------------------------------------------------
  // ----------   Methods   --------------------------------------------

  /**
   *
   */
  protected void returnParms ( )
  {
    this.app.form ( "REPORT_9_4_FR" ).setValue ( "COD_REV", this.parms.getString ( 0 ) );
    this.app.form ( "REPORT_9_4_FR" ).setValue ( "NO_REVIS", this.parms.getString ( 1 ) );
  }


  /**
   *
   */
  protected void prepareParms ( )
  {
    this.parms.reset ( );
    this.parms.set ( this.app.form ( "REPORT_9_4_FR" ).getValue ( "COD_REV" ) );
    this.parms.set ( this.app.form ( "REPORT_9_4_FR" ).getValue ( "NO_REVIS" ) );
  }


  /**
   *
   */
  public void execute ( RallyApplication __app, ParameterSet ps )
  {
    this.app = ( SAIC_DMQ_ORA_Application ) __app;
    this.execute ( ps );
  }
}
