package gov.dlf.logic;


import gov.dlf.facade.*;
import gov.dlf.presentation.*;


import net.maintrend.interfaces.*;
import net.maintrend.interlink.*;
import net.maintrend.rallyengine.*;
import net.maintrend.util.*;



/**
 * __Comment
 *
 * Generated by Rally-to-Java Convertor. MainTrend Ltd.
 */
public class SEL_ACCION_FRAUDE_ADL
     extends ADL
{
  // -------------------------------------------------------------------
  // ----------   Class Attributes   -----------------------------------

  /**  */
  public static boolean staticCall = false;



  // -------------------------------------------------------------------
  // ----------   Instance Attributes   --------------------------------

  /**  */
  public SAIC_DMQ_ORA_Application app;
  /**  */
  public RallyDataManager dm = null;



  // -------------------------------------------------------------------
  // ----------   Instance Condition Attributes   ----------------------

 

  // -------------------------------------------------------------------
  // ----------   Instance Export Attributes   -------------------------





  // -------------------------------------------------------------------
  // ----------   Instance Attributes' Access Methods   ----------------
    




  // -------------------------------------------------------------------
  // ----------   Methods   --------------------------------------------

  /**
   * 
   * @param __app
   * @return
   */
  public static SEL_ACCION_FRAUDE_ADL get ( RallyApplication __app )
  {
    SEL_ACCION_FRAUDE_ADL adl = new SEL_ACCION_FRAUDE_ADL ( );
    __app.register ( adl, "SEL_ACCION_FRAUDE_ADL" );
    __app.setADL ( SEL_ACCION_FRAUDE_ADL.class, adl ); 
    adl.setApplication ( __app );
    return adl;
  }


  /**
   *
   * @param __app
   * @param ps
   *
   * @return
   */
  public static void exec ( RallyApplication __app, ParameterSet ps )
  {
    SEL_ACCION_FRAUDE_ADL.get ( __app ).process ( ps );
  }


  /**
   *
   * @param __app
   *
   * @return
   */
  public static void exec ( RallyApplication __app )
  {
    ParameterSet ps = null;
    SEL_ACCION_FRAUDE_ADL.exec ( __app, ps );
  }


  /**
   * Overrides the ancestor's method
   * 
   * @param __app
   */
  @Override
public void setApplication ( RallyApplication __app )
  {
    this.app = ( SAIC_DMQ_ORA_Application ) __app;
    if ( this.app != null )
    {
      this.dm = ( RallyDataManager ) this.app.getDataManager ( );
    }
  }


  /**
   * Overrides the ancestor's method
   * 
   * @param parms
   */
  @Override
public void execute ( ParameterSet parms )
  {
    this.process ( parms );
  }




  /**
   *
   */
  protected void doReturn ( )
  {
    this.unregister ( );
  }


  /**
   *
   */
  public void unregister ( )
  {
    this.app.unregister ( this );
    IRegisteredObject rObj = this.app.get ( "SEL_ACCION_FRAUDE_ADL" );
    if ( rObj != null && rObj instanceof SEL_ACCION_FRAUDE_ADL )
    {
      this.app.setADL ( SEL_ACCION_FRAUDE_ADL.class, ( SEL_ACCION_FRAUDE_ADL ) rObj );
    }
  }


  /**
   * Overrides the ancestor's method
   * 
   * @param ps
   */
  @Override
protected void process ( ParameterSet ps )
  {
    Debug.println ( Debug.TRACE, "SEL_ACCION_FRAUDE_ADL Step " + this.currentStep );
    super.process ( ps );
    switch ( this.currentStep ) 
    {
      case 0:  { this.currentStep ++; this.step0 ( this.keyParms ); break; }
      default: 
      { 
        this.currentStep = 0;
        Debug.println ( Debug.TRACE, "SEL_ACCION_FRAUDE_ADL ended" );
        this.unregister ( );
        break;
      }
    }
    if ( this.currentStep > 0 ) this.app.goOn ( );
  }



  /**
   *
   */
  protected void step0 ( ParameterSet ps )
  {

    this.app.SS_JEFE_FAMILIA_GBL = this.app.form ( "LISTA_ACCION_TOMADA_FRAUDE_FRM" ).getDoubleItem ( "SS_JEFE_FAMILIA" );
    this.app.SS_JEFE_SERVICIO_GBL = this.app.form ( "LISTA_ACCION_TOMADA_FRAUDE_FRM" ).getDoubleItem ( "SS_JEFE_SERVICIO" );
    this.app.COD_SERV_GBL = this.app.form ( "LISTA_ACCION_TOMADA_FRAUDE_FRM" ).getStringItem ( "COD_SERV" );
    this.app.FECHA_IDENTIFICADO_GBL = this.app.form ( "LISTA_ACCION_TOMADA_FRAUDE_FRM" ).getDateItem ( "FECHA_REFERIDO" );
    ACCION_TOMADA_FRAUDE_PKT.exec ( this.app );
    return;

  }
}



/* ---------------------------------------------------------------------


     
PROCEDURE SEL_ACCION_FRAUDE_ADL;

BEGIN
SET_TRACE();

        SS_JEFE_FAMILIA_GBL := LISTA_ACCION_TOMADA_FRAUDE_FRM.SS_JEFE_FAMILIA;
        SS_JEFE_SERVICIO_GBL := LISTA_ACCION_TOMADA_FRAUDE_FRM.SS_JEFE_SERVICIO;
        COD_SERV_GBL := LISTA_ACCION_TOMADA_FRAUDE_FRM.COD_SERV;
        FECHA_IDENTIFICADO_GBL := LISTA_ACCION_TOMADA_FRAUDE_FRM.FECHA_REFERIDO;
        CALL ACCION_TOMADA_FRAUDE_PKT;

SET_NOTRACE();
END;
    



--------------------------------------------------------------------- */
