package gov.dlf.logic;


import gov.dlf.facade.*;
import gov.dlf.presentation.*;


import net.maintrend.datamanager.*;
import net.maintrend.interfaces.*;
import net.maintrend.interlink.*;
import net.maintrend.rallyengine.*;
import net.maintrend.util.*;



/**
 * __Comment
 *
 * Generated by Rally-to-Java Convertor. MainTrend Ltd.
 */
public class ELIMINAR_SERVICIO_ADL
     extends ADL
{
  // -------------------------------------------------------------------
  // ----------   Class Attributes   -----------------------------------

  /**  */
  public static boolean staticCall = false;



  // -------------------------------------------------------------------
  // ----------   Instance Attributes   --------------------------------

  /**  */
  public SAIC_DMQ_ORA_Application app;
  /**  */
  public RallyDataManager dm = null;



  // -------------------------------------------------------------------
  // ----------   Instance Condition Attributes   ----------------------

 

  // -------------------------------------------------------------------
  // ----------   Instance Export Attributes   -------------------------

  public double SERV_ID = 0;

  public double OPEN_ID = 0;

  public double STATUS_ID = 0;

  public double EMERG_ID = 0;

  public double EMERG_CODE = 0;

  public double SSN_JEFE_FAM = 0;

  public double SSN_JEFE_SERV = 0;

  public double RECLARETRO_OCI = 0;

  public double RECLARETRO_OCI_STAT = 0;



  public String COD_SERV = null;

  public DataStore RECLA_RETRO_RO_DSD = null;

  public DataStore TECNICO_RO_DSD = null;

  public DataStore SERVICIOS2_DSD = null;

  public DataStore SERVICIOS_EMERGENCIA2_DSD = null;



  // -------------------------------------------------------------------
  // ----------   Instance Attributes' Access Methods   ----------------

  
  /**  */
  public static void setSERV_ID  ( RallyApplication __app, Parameter value )
  {
    ( ( ELIMINAR_SERVICIO_ADL ) __app.getADL ( ELIMINAR_SERVICIO_ADL.class ) ).SERV_ID = value.getDouble ( );
  }  

  
  /**  */
  public static void setOPEN_ID  ( RallyApplication __app, Parameter value )
  {
    ( ( ELIMINAR_SERVICIO_ADL ) __app.getADL ( ELIMINAR_SERVICIO_ADL.class ) ).OPEN_ID = value.getDouble ( );
  }  

  
  /**  */
  public static void setSTATUS_ID  ( RallyApplication __app, Parameter value )
  {
    ( ( ELIMINAR_SERVICIO_ADL ) __app.getADL ( ELIMINAR_SERVICIO_ADL.class ) ).STATUS_ID = value.getDouble ( );
  }  

  
  /**  */
  public static void setEMERG_ID  ( RallyApplication __app, Parameter value )
  {
    ( ( ELIMINAR_SERVICIO_ADL ) __app.getADL ( ELIMINAR_SERVICIO_ADL.class ) ).EMERG_ID = value.getDouble ( );
  }  

  
  /**  */
  public static void setEMERG_CODE  ( RallyApplication __app, Parameter value )
  {
    ( ( ELIMINAR_SERVICIO_ADL ) __app.getADL ( ELIMINAR_SERVICIO_ADL.class ) ).EMERG_CODE = value.getDouble ( );
  }  

  
  /**  */
  public static void setSSN_JEFE_FAM  ( RallyApplication __app, Parameter value )
  {
    ( ( ELIMINAR_SERVICIO_ADL ) __app.getADL ( ELIMINAR_SERVICIO_ADL.class ) ).SSN_JEFE_FAM = value.getDouble ( );
  }  

  
  /**  */
  public static void setSSN_JEFE_SERV  ( RallyApplication __app, Parameter value )
  {
    ( ( ELIMINAR_SERVICIO_ADL ) __app.getADL ( ELIMINAR_SERVICIO_ADL.class ) ).SSN_JEFE_SERV = value.getDouble ( );
  }  

  
  /**  */
  public static void setCOD_SERV  ( RallyApplication __app, Parameter value )
  {
    ( ( ELIMINAR_SERVICIO_ADL ) __app.getADL ( ELIMINAR_SERVICIO_ADL.class ) ).COD_SERV = value.getString ( );
  }  

  
  /**  */
  public static void setRECLARETRO_OCI  ( RallyApplication __app, Parameter value )
  {
    ( ( ELIMINAR_SERVICIO_ADL ) __app.getADL ( ELIMINAR_SERVICIO_ADL.class ) ).RECLARETRO_OCI = value.getDouble ( );
  }  

  
  /**  */
  public static void setRECLARETRO_OCI_STAT  ( RallyApplication __app, Parameter value )
  {
    ( ( ELIMINAR_SERVICIO_ADL ) __app.getADL ( ELIMINAR_SERVICIO_ADL.class ) ).RECLARETRO_OCI_STAT = value.getDouble ( );
  }  
    


  /**  */
  public static String getCOD_SERV  ( RallyApplication __app )
  {
    return ( ( ELIMINAR_SERVICIO_ADL ) __app.getADL ( ELIMINAR_SERVICIO_ADL.class ) ).COD_SERV;
  }


  /**  */
  public static void setCOD_SERV  ( RallyApplication __app, String value )
  {
    ( ( ELIMINAR_SERVICIO_ADL ) __app.getADL ( ELIMINAR_SERVICIO_ADL.class ) ).COD_SERV = value;
  }


  /**  */
  public static void setCOD_SERV  ( RallyApplication __app, Object value )
  {
    ( ( ELIMINAR_SERVICIO_ADL ) __app.getADL ( ELIMINAR_SERVICIO_ADL.class ) ).COD_SERV = ( String ) value;
  }



  /**  */
  public static DataStore getRECLA_RETRO_RO_DSD  ( RallyApplication __app )
  {
    return ( ( ELIMINAR_SERVICIO_ADL ) __app.getADL ( ELIMINAR_SERVICIO_ADL.class ) ).RECLA_RETRO_RO_DSD;
  }


  /**  */
  public static void setRECLA_RETRO_RO_DSD  ( RallyApplication __app, DataStore value )
  {
    ( ( ELIMINAR_SERVICIO_ADL ) __app.getADL ( ELIMINAR_SERVICIO_ADL.class ) ).RECLA_RETRO_RO_DSD = value;
  }


  /**  */
  public static void setRECLA_RETRO_RO_DSD  ( RallyApplication __app, Object value )
  {
    ( ( ELIMINAR_SERVICIO_ADL ) __app.getADL ( ELIMINAR_SERVICIO_ADL.class ) ).RECLA_RETRO_RO_DSD = ( DataStore ) value;
  }



  /**  */
  public static DataStore getTECNICO_RO_DSD  ( RallyApplication __app )
  {
    return ( ( ELIMINAR_SERVICIO_ADL ) __app.getADL ( ELIMINAR_SERVICIO_ADL.class ) ).TECNICO_RO_DSD;
  }


  /**  */
  public static void setTECNICO_RO_DSD  ( RallyApplication __app, DataStore value )
  {
    ( ( ELIMINAR_SERVICIO_ADL ) __app.getADL ( ELIMINAR_SERVICIO_ADL.class ) ).TECNICO_RO_DSD = value;
  }


  /**  */
  public static void setTECNICO_RO_DSD  ( RallyApplication __app, Object value )
  {
    ( ( ELIMINAR_SERVICIO_ADL ) __app.getADL ( ELIMINAR_SERVICIO_ADL.class ) ).TECNICO_RO_DSD = ( DataStore ) value;
  }



  /**  */
  public static DataStore getSERVICIOS2_DSD  ( RallyApplication __app )
  {
    return ( ( ELIMINAR_SERVICIO_ADL ) __app.getADL ( ELIMINAR_SERVICIO_ADL.class ) ).SERVICIOS2_DSD;
  }


  /**  */
  public static void setSERVICIOS2_DSD  ( RallyApplication __app, DataStore value )
  {
    ( ( ELIMINAR_SERVICIO_ADL ) __app.getADL ( ELIMINAR_SERVICIO_ADL.class ) ).SERVICIOS2_DSD = value;
  }


  /**  */
  public static void setSERVICIOS2_DSD  ( RallyApplication __app, Object value )
  {
    ( ( ELIMINAR_SERVICIO_ADL ) __app.getADL ( ELIMINAR_SERVICIO_ADL.class ) ).SERVICIOS2_DSD = ( DataStore ) value;
  }



  /**  */
  public static DataStore getSERVICIOS_EMERGENCIA2_DSD  ( RallyApplication __app )
  {
    return ( ( ELIMINAR_SERVICIO_ADL ) __app.getADL ( ELIMINAR_SERVICIO_ADL.class ) ).SERVICIOS_EMERGENCIA2_DSD;
  }


  /**  */
  public static void setSERVICIOS_EMERGENCIA2_DSD  ( RallyApplication __app, DataStore value )
  {
    ( ( ELIMINAR_SERVICIO_ADL ) __app.getADL ( ELIMINAR_SERVICIO_ADL.class ) ).SERVICIOS_EMERGENCIA2_DSD = value;
  }


  /**  */
  public static void setSERVICIOS_EMERGENCIA2_DSD  ( RallyApplication __app, Object value )
  {
    ( ( ELIMINAR_SERVICIO_ADL ) __app.getADL ( ELIMINAR_SERVICIO_ADL.class ) ).SERVICIOS_EMERGENCIA2_DSD = ( DataStore ) value;
  }




  /**  */
  public static double getSERV_ID  ( RallyApplication __app )
  {
    return ( ( ELIMINAR_SERVICIO_ADL ) __app.getADL ( ELIMINAR_SERVICIO_ADL.class ) ).SERV_ID;
  }


  /**  */
  public static Double getSERV_IDDouble ( RallyApplication __app )
  {
    return new Double ( ( ( ELIMINAR_SERVICIO_ADL ) __app.getADL ( ELIMINAR_SERVICIO_ADL.class ) ).SERV_ID );
  }


  /**  */
  public static void setSERV_ID  ( RallyApplication __app, double value )
  {
    ( ( ELIMINAR_SERVICIO_ADL ) __app.getADL ( ELIMINAR_SERVICIO_ADL.class ) ).SERV_ID = value;
  }


  /**  */
  public static void setSERV_ID  ( RallyApplication __app, Object value )
  {
    ( ( ELIMINAR_SERVICIO_ADL ) __app.getADL ( ELIMINAR_SERVICIO_ADL.class ) ).SERV_ID = ( ( Double ) value ).doubleValue ( );
  }


  /**  */
  public static double getOPEN_ID  ( RallyApplication __app )
  {
    return ( ( ELIMINAR_SERVICIO_ADL ) __app.getADL ( ELIMINAR_SERVICIO_ADL.class ) ).OPEN_ID;
  }


  /**  */
  public static Double getOPEN_IDDouble ( RallyApplication __app )
  {
    return new Double ( ( ( ELIMINAR_SERVICIO_ADL ) __app.getADL ( ELIMINAR_SERVICIO_ADL.class ) ).OPEN_ID );
  }


  /**  */
  public static void setOPEN_ID  ( RallyApplication __app, double value )
  {
    ( ( ELIMINAR_SERVICIO_ADL ) __app.getADL ( ELIMINAR_SERVICIO_ADL.class ) ).OPEN_ID = value;
  }


  /**  */
  public static void setOPEN_ID  ( RallyApplication __app, Object value )
  {
    ( ( ELIMINAR_SERVICIO_ADL ) __app.getADL ( ELIMINAR_SERVICIO_ADL.class ) ).OPEN_ID = ( ( Double ) value ).doubleValue ( );
  }


  /**  */
  public static double getSTATUS_ID  ( RallyApplication __app )
  {
    return ( ( ELIMINAR_SERVICIO_ADL ) __app.getADL ( ELIMINAR_SERVICIO_ADL.class ) ).STATUS_ID;
  }


  /**  */
  public static Double getSTATUS_IDDouble ( RallyApplication __app )
  {
    return new Double ( ( ( ELIMINAR_SERVICIO_ADL ) __app.getADL ( ELIMINAR_SERVICIO_ADL.class ) ).STATUS_ID );
  }


  /**  */
  public static void setSTATUS_ID  ( RallyApplication __app, double value )
  {
    ( ( ELIMINAR_SERVICIO_ADL ) __app.getADL ( ELIMINAR_SERVICIO_ADL.class ) ).STATUS_ID = value;
  }


  /**  */
  public static void setSTATUS_ID  ( RallyApplication __app, Object value )
  {
    ( ( ELIMINAR_SERVICIO_ADL ) __app.getADL ( ELIMINAR_SERVICIO_ADL.class ) ).STATUS_ID = ( ( Double ) value ).doubleValue ( );
  }


  /**  */
  public static double getEMERG_ID  ( RallyApplication __app )
  {
    return ( ( ELIMINAR_SERVICIO_ADL ) __app.getADL ( ELIMINAR_SERVICIO_ADL.class ) ).EMERG_ID;
  }


  /**  */
  public static Double getEMERG_IDDouble ( RallyApplication __app )
  {
    return new Double ( ( ( ELIMINAR_SERVICIO_ADL ) __app.getADL ( ELIMINAR_SERVICIO_ADL.class ) ).EMERG_ID );
  }


  /**  */
  public static void setEMERG_ID  ( RallyApplication __app, double value )
  {
    ( ( ELIMINAR_SERVICIO_ADL ) __app.getADL ( ELIMINAR_SERVICIO_ADL.class ) ).EMERG_ID = value;
  }


  /**  */
  public static void setEMERG_ID  ( RallyApplication __app, Object value )
  {
    ( ( ELIMINAR_SERVICIO_ADL ) __app.getADL ( ELIMINAR_SERVICIO_ADL.class ) ).EMERG_ID = ( ( Double ) value ).doubleValue ( );
  }


  /**  */
  public static double getEMERG_CODE  ( RallyApplication __app )
  {
    return ( ( ELIMINAR_SERVICIO_ADL ) __app.getADL ( ELIMINAR_SERVICIO_ADL.class ) ).EMERG_CODE;
  }


  /**  */
  public static Double getEMERG_CODEDouble ( RallyApplication __app )
  {
    return new Double ( ( ( ELIMINAR_SERVICIO_ADL ) __app.getADL ( ELIMINAR_SERVICIO_ADL.class ) ).EMERG_CODE );
  }


  /**  */
  public static void setEMERG_CODE  ( RallyApplication __app, double value )
  {
    ( ( ELIMINAR_SERVICIO_ADL ) __app.getADL ( ELIMINAR_SERVICIO_ADL.class ) ).EMERG_CODE = value;
  }


  /**  */
  public static void setEMERG_CODE  ( RallyApplication __app, Object value )
  {
    ( ( ELIMINAR_SERVICIO_ADL ) __app.getADL ( ELIMINAR_SERVICIO_ADL.class ) ).EMERG_CODE = ( ( Double ) value ).doubleValue ( );
  }


  /**  */
  public static double getSSN_JEFE_FAM  ( RallyApplication __app )
  {
    return ( ( ELIMINAR_SERVICIO_ADL ) __app.getADL ( ELIMINAR_SERVICIO_ADL.class ) ).SSN_JEFE_FAM;
  }


  /**  */
  public static Double getSSN_JEFE_FAMDouble ( RallyApplication __app )
  {
    return new Double ( ( ( ELIMINAR_SERVICIO_ADL ) __app.getADL ( ELIMINAR_SERVICIO_ADL.class ) ).SSN_JEFE_FAM );
  }


  /**  */
  public static void setSSN_JEFE_FAM  ( RallyApplication __app, double value )
  {
    ( ( ELIMINAR_SERVICIO_ADL ) __app.getADL ( ELIMINAR_SERVICIO_ADL.class ) ).SSN_JEFE_FAM = value;
  }


  /**  */
  public static void setSSN_JEFE_FAM  ( RallyApplication __app, Object value )
  {
    ( ( ELIMINAR_SERVICIO_ADL ) __app.getADL ( ELIMINAR_SERVICIO_ADL.class ) ).SSN_JEFE_FAM = ( ( Double ) value ).doubleValue ( );
  }


  /**  */
  public static double getSSN_JEFE_SERV  ( RallyApplication __app )
  {
    return ( ( ELIMINAR_SERVICIO_ADL ) __app.getADL ( ELIMINAR_SERVICIO_ADL.class ) ).SSN_JEFE_SERV;
  }


  /**  */
  public static Double getSSN_JEFE_SERVDouble ( RallyApplication __app )
  {
    return new Double ( ( ( ELIMINAR_SERVICIO_ADL ) __app.getADL ( ELIMINAR_SERVICIO_ADL.class ) ).SSN_JEFE_SERV );
  }


  /**  */
  public static void setSSN_JEFE_SERV  ( RallyApplication __app, double value )
  {
    ( ( ELIMINAR_SERVICIO_ADL ) __app.getADL ( ELIMINAR_SERVICIO_ADL.class ) ).SSN_JEFE_SERV = value;
  }


  /**  */
  public static void setSSN_JEFE_SERV  ( RallyApplication __app, Object value )
  {
    ( ( ELIMINAR_SERVICIO_ADL ) __app.getADL ( ELIMINAR_SERVICIO_ADL.class ) ).SSN_JEFE_SERV = ( ( Double ) value ).doubleValue ( );
  }


  /**  */
  public static double getRECLARETRO_OCI  ( RallyApplication __app )
  {
    return ( ( ELIMINAR_SERVICIO_ADL ) __app.getADL ( ELIMINAR_SERVICIO_ADL.class ) ).RECLARETRO_OCI;
  }


  /**  */
  public static Double getRECLARETRO_OCIDouble ( RallyApplication __app )
  {
    return new Double ( ( ( ELIMINAR_SERVICIO_ADL ) __app.getADL ( ELIMINAR_SERVICIO_ADL.class ) ).RECLARETRO_OCI );
  }


  /**  */
  public static void setRECLARETRO_OCI  ( RallyApplication __app, double value )
  {
    ( ( ELIMINAR_SERVICIO_ADL ) __app.getADL ( ELIMINAR_SERVICIO_ADL.class ) ).RECLARETRO_OCI = value;
  }


  /**  */
  public static void setRECLARETRO_OCI  ( RallyApplication __app, Object value )
  {
    ( ( ELIMINAR_SERVICIO_ADL ) __app.getADL ( ELIMINAR_SERVICIO_ADL.class ) ).RECLARETRO_OCI = ( ( Double ) value ).doubleValue ( );
  }


  /**  */
  public static double getRECLARETRO_OCI_STAT  ( RallyApplication __app )
  {
    return ( ( ELIMINAR_SERVICIO_ADL ) __app.getADL ( ELIMINAR_SERVICIO_ADL.class ) ).RECLARETRO_OCI_STAT;
  }


  /**  */
  public static Double getRECLARETRO_OCI_STATDouble ( RallyApplication __app )
  {
    return new Double ( ( ( ELIMINAR_SERVICIO_ADL ) __app.getADL ( ELIMINAR_SERVICIO_ADL.class ) ).RECLARETRO_OCI_STAT );
  }


  /**  */
  public static void setRECLARETRO_OCI_STAT  ( RallyApplication __app, double value )
  {
    ( ( ELIMINAR_SERVICIO_ADL ) __app.getADL ( ELIMINAR_SERVICIO_ADL.class ) ).RECLARETRO_OCI_STAT = value;
  }


  /**  */
  public static void setRECLARETRO_OCI_STAT  ( RallyApplication __app, Object value )
  {
    ( ( ELIMINAR_SERVICIO_ADL ) __app.getADL ( ELIMINAR_SERVICIO_ADL.class ) ).RECLARETRO_OCI_STAT = ( ( Double ) value ).doubleValue ( );
  }



  // -------------------------------------------------------------------
  // ----------   Methods   --------------------------------------------

  /**
   * 
   * @param __app
   * @return
   */
  public static ELIMINAR_SERVICIO_ADL get ( RallyApplication __app )
  {
    ELIMINAR_SERVICIO_ADL adl = new ELIMINAR_SERVICIO_ADL ( );
    __app.register ( adl, "ELIMINAR_SERVICIO_ADL" );
    __app.setADL ( ELIMINAR_SERVICIO_ADL.class, adl ); 
    adl.setApplication ( __app );
    return adl;
  }


  /**
   *
   * @param __app
   * @param ps
   *
   * @return
   */
  public static void exec ( RallyApplication __app, ParameterSet ps )
  {
    ELIMINAR_SERVICIO_ADL.get ( __app ).process ( ps );
  }


  /**
   *
   * @param __app
   *
   * @return
   */
  public static void exec ( RallyApplication __app )
  {
    ParameterSet ps = null;
    ELIMINAR_SERVICIO_ADL.exec ( __app, ps );
  }


  /**
   * Overrides the ancestor's method
   * 
   * @param __app
   */
  @Override
public void setApplication ( RallyApplication __app )
  {
    this.app = ( SAIC_DMQ_ORA_Application ) __app;
    if ( this.app != null )
    {
      this.dm = ( RallyDataManager ) this.app.getDataManager ( );
    }
  }


  /**
   * Overrides the ancestor's method
   * 
   * @param parms
   */
  @Override
public void execute ( ParameterSet parms )
  {
    this.process ( parms );
  }




  /**
   *
   */
  protected void doReturn ( )
  {
    this.unregister ( );
  }


  /**
   *
   */
  public void unregister ( )
  {
    this.app.unregister ( this );
    IRegisteredObject rObj = this.app.get ( "ELIMINAR_SERVICIO_ADL" );
    if ( rObj != null && rObj instanceof ELIMINAR_SERVICIO_ADL )
    {
      this.app.setADL ( ELIMINAR_SERVICIO_ADL.class, ( ELIMINAR_SERVICIO_ADL ) rObj );
    }
  }


  /**
   * Overrides the ancestor's method
   * 
   * @param ps
   */
  @Override
protected void process ( ParameterSet ps )
  {
    Debug.println ( Debug.TRACE, "ELIMINAR_SERVICIO_ADL Step " + this.currentStep );
    super.process ( ps );
    switch ( this.currentStep ) 
    {
      case 0:  { this.currentStep ++; this.step0 ( this.keyParms ); break; }
      case 1:  { this.currentStep ++; this.step1 ( this.keyParms ); break; }
      case 2:  { this.currentStep ++; this.step2 ( this.keyParms ); break; }
      default: 
      { 
        this.currentStep = 0;
        Debug.println ( Debug.TRACE, "ELIMINAR_SERVICIO_ADL ended" );
        this.unregister ( );
        break;
      }
    }
    if ( this.currentStep > 0 ) this.app.goOn ( );
  }



  /**
   *
   */
  protected void step0 ( ParameterSet ps )
  {

    this.app.COD_ACCESS_GBL = "ESER";
    SECURITY_ADL.exec ( this.app );
    return;

  }


  /**
   *
   */
  protected void step1 ( ParameterSet ps )
  {

    if ( Compare.equals ( this.app.ACCESS_STATUS_GBL, "FAILURE" ) ) 
    {
      this.app.setError ( 0, 1006 );
      this.doReturn ( );
      return; 
    }
    if ( ( ! Compare.equals ( this.app.form ( "PRE_MENU_MANT_SERV_FR" ).getStringItem ( "COD_STATUS_SERVICIO" ), "PENDELEG" ) ) && ( ! Compare.equals ( this.app.form ( "PRE_MENU_MANT_SERV_FR" ).getStringItem ( "COD_STATUS_SERVICIO" ), "PENDCERT" ) )  && ( ! Compare.equals ( this.app.form ( "PRE_MENU_MANT_SERV_FR" ).getStringItem ( "COD_STATUS_SERVICIO" ), "PENDAUTO" ) )  ) 
    {
      this.app.setError ( 1, 4001 );
      this.doReturn ( );
      return; 
    }
    RECLA_RETRO_RO_DSD = this.dm.create ( "RECLA_RETRO_RO_DSD" );
    RECLARETRO_OCI = RECLA_RETRO_RO_DSD.getId ( );
    RECLARETRO_OCI_STAT = RallyDataStoreException.getDefault ( );

    RECLARETRO_OCI_STAT  = this.dm.reset ( RECLARETRO_OCI );

    this.dm.setField ( this.dm.get ( "RECLA_RETRO_RO_DSD" ), "SEGURO_SOCIAL_JEFE_SERV", this.app.form ( "SERV_FAM_FRM" ).getDoubleItem ( "SEGURO_SOCIAL_JEFE_SERV" ));
    this.dm.setField ( this.dm.get ( "RECLA_RETRO_RO_DSD" ), "COD_SERVICIO", this.app.form ( "SERV_FAM_FRM" ).getStringItem ( "COD_SERVICIO" ));

    RECLARETRO_OCI_STAT  = this.dm.limitQueryFromBuffer ( RECLARETRO_OCI );
    RECLARETRO_OCI_STAT  = this.dm.retrieve ( RECLARETRO_OCI );

    RECLARETRO_OCI_STAT  = this.dm.firstRow ( RECLARETRO_OCI );

    if ( Compare.equals ( RECLARETRO_OCI_STAT, 0 ) ) 
    {
      this.app.setError ( 2, 4011 );
      this.doReturn ( );
      return; 
    }
    RECLARETRO_OCI_STAT  = this.dm.dbClose ( RECLARETRO_OCI );

    TECNICO_RO_DSD = this.dm.create ( "TECNICO_RO_DSD" );
    OPEN_ID = TECNICO_RO_DSD.getId ( );
    STATUS_ID = RallyDataStoreException.getDefault ( );

    STATUS_ID  = this.dm.reset ( OPEN_ID );

    this.dm.setField ( this.dm.get ( "TECNICO_RO_DSD" ), "ID_SUPERVISOR", this.app.ID_TECNICO_GBL );

    STATUS_ID  = this.dm.limitQueryFromBuffer ( OPEN_ID );
    STATUS_ID  = this.dm.retrieve ( OPEN_ID );

    STATUS_ID  = this.dm.firstRow ( OPEN_ID );

    if ( ! Compare.equals ( STATUS_ID, 0 ) ) 
    {
      STATUS_ID  = this.dm.dbClose ( OPEN_ID );

      this.app.setError ( 3, 4005 );
      this.doReturn ( );
      return; 
    }
    STATUS_ID  = this.dm.dbClose ( OPEN_ID );

    if ( Compare.equals ( this.app.RUTINA_GBL, "MC" ) ) 
    {
      MANTENIMIENTO_DE_CASOS_ADL.setCOMPLETION_STATUS ( this.app, "SUCCESS" );
    }
    else if ( Compare.equals ( this.app.RUTINA_GBL, "AC" )  )
    {
      APERTURA_DE_CASO_ADL.setCOMPLETION_STATUS ( this.app, "SUCCESS" );
    }
    this.app.MANT_ACCION_SERV_GBL = "ES";
    QFECHAS_SERVICIO_PKT.exec ( this.app );
    return;

  }


  /**
   *
   */
  protected void step2 ( ParameterSet ps )
  {
    if ( Compare.equals ( this.app.RUTINA_GBL, "MC" ) ) 
    {
      if ( Compare.equals ( MANTENIMIENTO_DE_CASOS_ADL.getCOMPLETION_STATUS ( this.app ), "FAILURE" ) ) 
      {
        this.doReturn ( );
        return;
      }
    }
    else
    {
      if ( Compare.equals ( this.app.RUTINA_GBL, "AC" ) ) 
      {
        if ( Compare.equals ( APERTURA_DE_CASO_ADL.getCOMPLETION_STATUS ( this.app ), "FAILURE" ) ) 
        {
          this.doReturn ( );
          return;
        }
      }
    }
    OPEN_ID = TruncService.setNull ( OPEN_ID  );
    SSN_JEFE_FAM = this.app.form ( "SERV_FAM_FRM" ).getDoubleItem ( "SEGURO_SOCIAL_JEFE_FAM" );
    SSN_JEFE_SERV = this.app.form ( "SERV_FAM_FRM" ).getDoubleItem ( "SEGURO_SOCIAL_JEFE_SERV" );
    COD_SERV = this.app.form ( "SERV_FAM_FRM" ).getStringItem ( "COD_SERVICIO" );
    SERVICIOS2_DSD = this.dm.create ( "SERVICIOS2_DSD" );
    OPEN_ID = SERVICIOS2_DSD.getId ( );
    STATUS_ID = RallyDataStoreException.getDefault ( );

    STATUS_ID  = this.dm.reset ( OPEN_ID );

    this.dm.setField ( this.dm.get ( "SERVICIOS2_DSD" ), "SEGURO_SOCIAL_JEFE_FAM", SSN_JEFE_FAM );
    this.dm.setField ( this.dm.get ( "SERVICIOS2_DSD" ), "SEGURO_SOCIAL_JEFE_SERV", SSN_JEFE_SERV );
    this.dm.setField ( this.dm.get ( "SERVICIOS2_DSD" ), "COD_SERVICIO", COD_SERV );
    this.dm.setField ( this.dm.get ( "SERVICIOS2_DSD" ), "RMO_OFICINA", this.app.RMO_GBL );

    STATUS_ID  = this.dm.limitQueryFromBuffer ( OPEN_ID );
    STATUS_ID  = this.dm.retrieve ( OPEN_ID );

    STATUS_ID  = this.dm.firstRow ( OPEN_ID );

    boolean tempBool = this.dm.getLogEnabled ( );          
    this.dm.setLogEnabled ( false );
    
    STATUS_ID  = this.dm.delete ( OPEN_ID );
    
    if ( ! Compare.equals ( STATUS_ID, 0 ) ) 
    {
      this.app.setError ( 4, STATUS_ID );
    }

    this.dm.update ( SERVICIOS2_DSD );
    
    this.dm.setLogEnabled ( tempBool );
    
    STATUS_ID  = this.dm.dbCommit ( );
    if ( ! Compare.equals ( STATUS_ID, 0 ) ) 
    {
      this.app.setError ( 5, STATUS_ID );
    }
    STATUS_ID  = this.dm.dbClose ( OPEN_ID );

    OPEN_ID = TruncService.setNull ( OPEN_ID  );
    SERVICIOS_EMERGENCIA2_DSD = this.dm.create ( "SERVICIOS_EMERGENCIA2_DSD" );
    EMERG_ID = SERVICIOS_EMERGENCIA2_DSD.getId ( );
    EMERG_CODE = RallyDataStoreException.getDefault ( );

    EMERG_CODE  = this.dm.reset ( EMERG_ID );

    this.dm.setField ( this.dm.get ( "SERVICIOS_EMERGENCIA2_DSD" ), "SEGURO_SOCIAL_JEFE_FAM", SSN_JEFE_FAM );
    this.dm.setField ( this.dm.get ( "SERVICIOS_EMERGENCIA2_DSD" ), "SEGURO_SOCIAL_JEFE_SERV", SSN_JEFE_SERV );
    this.dm.setField ( this.dm.get ( "SERVICIOS_EMERGENCIA2_DSD" ), "COD_SERVICIO", COD_SERV );
    this.dm.setField ( this.dm.get ( "SERVICIOS_EMERGENCIA2_DSD" ), "RMO_OFICINA", this.app.RMO_GBL );

    EMERG_CODE  = this.dm.limitQueryFromBuffer ( EMERG_ID );
    EMERG_CODE  = this.dm.retrieve ( EMERG_ID );

    EMERG_CODE  = this.dm.firstRow ( EMERG_ID );

    EMERG_CODE  = this.dm.delete ( EMERG_ID );
    this.dm.update ( SERVICIOS_EMERGENCIA2_DSD );

    EMERG_CODE  = this.dm.dbCommit ( );
    EMERG_CODE  = this.dm.dbClose ( EMERG_ID );

  }
}



/* ---------------------------------------------------------------------


     
PROCEDURE ELIMINAR_SERVICIO_ADL;

VAR

SERV_ID:        NUMBER;
OPEN_ID:        NUMBER(9,0);
STATUS_ID:      NUMBER(9,0);
EMERG_ID:       NUMBER(9,0);
EMERG_CODE:     NUMBER(9,0);

SSN_JEFE_FAM:   NUMBER(9,0);
SSN_JEFE_SERV:  NUMBER(9,0);
COD_SERV:       CHAR(5);

reclaretro_OCI:      number;
reclaretro_oci_stat: number;

BEGIN

SET_TRACE();
cod_acceSs_gbl := 'ESER';
CALL SECURITY_ADL;
IF ACCESS_STATUS_GBL = 'FAILURE' 
   THEN BEGIN
        ERROR(1006);
        RETURN;
        END;
{ modificacion hecha para impedir la eliminacion de servicios activos, accneg,
  pendrevi, pendauto, cerrado o rechazados}
if (PRE_MENU_MANT_SERV_FR.COD_STATUS_SERVICIO <> 'PENDELEG') AND
   (PRE_MENU_MANT_SERV_FR.COD_STATUS_SERVICIO <> 'PENDCERT') AND
   (PRE_MENU_MANT_SERV_FR.COD_STATUS_SERVICIO <> 'PENDAUTO')
   then begin
        error (4001);
        return;
        end;

{ modificación para impedir eliminar un servicio que tenga reclamación ó
  retroactivo }


DB_OPEN(RECLA_RETRO_RO_DSD,reclaretro_oci,reclaretro_oci_stat);
DB_RESET(reclaretro_oci,reclaretro_oci_stat);

RECLA_RETRO_RO_DSD.SEGURO_SOCIAL_JEFE_SERV:= SERV_FAM_FRM.SEGURO_SOCIAL_JEFE_SER
V;
RECLA_RETRO_RO_DSD.COD_SERVICIO:= SERV_FAM_FRM.COD_SERVICIO;
 
DB_QUERY(reclaretro_oci,reclaretro_oci_stat);
DB_GET_FIRST(reclaretro_oci,reclaretro_oci_stat);

IF reclaretro_oci_stat = 0    
   then begin
        error (4011);
        return;
        end;

DB_CLOSE(RECLARETRO_OCI,RECLARETRO_OCI_STAT);



DB_OPEN(TECNICO_RO_DSD,OPEN_ID,STATUS_ID);
DB_RESET(OPEN_ID,STATUS_ID);
TECNICO_RO_DSD.ID_SUPERVISOR:=ID_TECNICO_GBL;
DB_QUERY(OPEN_ID,STATUS_ID);
DB_GET_FIRST(OPEN_ID,STATUS_ID);


IF STATUS_ID<>0 
   THEN BEGIN
        DB_CLOSE(OPEN_ID,STATUS_ID);
        ERROR(4005);
        RETURN;
        END;


DB_CLOSE(OPEN_ID,STATUS_ID);



IF RUTINA_GBL='MC'
   THEN MANTENIMIENTO_DE_CASOS_ADL.COMPLETION_STATUS:='SUCCESS';
   ELSE IF RUTINA_GBL='AC'
        THEN APERTURA_DE_CASO_ADL.COMPLETION_STATUS:='SUCCESS';

MANT_ACCION_SERV_GBL:='ES';
CALL QFECHAS_SERVICIO_PKT;

IF RUTINA_GBL='MC'
   THEN BEGIN
        IF MANTENIMIENTO_DE_CASOS_ADL.COMPLETION_STATUS='FAILURE'
        THEN RETURN;
        END;
   ELSE BEGIN
        IF RUTINA_GBL='AC'
        THEN IF APERTURA_DE_CASO_ADL.COMPLETION_STATUS='FAILURE'
             THEN RETURN;
        END;


MAKE_NULL(OPEN_ID);


SSN_JEFE_FAM:=SERV_FAM_FRM.SEGURO_SOCIAL_JEFE_FAM;
SSN_JEFE_SERV:=SERV_FAM_FRM.SEGURO_SOCIAL_JEFE_SERV;
COD_SERV:=SERV_FAM_FRM.COD_SERVICIO;

DB_OPEN(SERVICIOS2_DSD,OPEN_ID,STATUS_ID);
DB_RESET(OPEN_ID,STATUS_ID);

SERVICIOS2_DSD.SEGURO_SOCIAL_JEFE_FAM:=SSN_JEFE_FAM;
SERVICIOS2_DSD.SEGURO_SOCIAL_JEFE_SERV:=SSN_JEFE_SERV;
SERVICIOS2_DSD.COD_SERVICIO:=COD_SERV;
SERVICIOS2_DSD.RMO_OFICINA := rmo_gbl;

DB_QUERY(OPEN_ID,STATUS_ID);
DB_GET_FIRST(OPEN_ID,STATUS_ID);

DB_DELETE(OPEN_ID,STATUS_ID);
IF STATUS_ID <> 0
THEN ERROR(STATUS_ID);
DB_COMMIT(STATUS_ID);
IF STATUS_ID <> 0
THEN ERROR(STATUS_ID);
DB_CLOSE (OPEN_ID, STATUS_ID);                                                  
                    
MAKE_NULL(OPEN_ID);

{CODIGO ANADIDO PARA BORRAR RECORDS DE LA TABLA SERVICIO_EMERGENCIA}

DB_OPEN(SERVICIOS_EMERGENCIA2_DSD,EMERG_ID,EMERG_CODE);
DB_RESET(EMERG_ID,EMERG_CODE);
SERVICIOS_EMERGENCIA2_DSD.SEGURO_SOCIAL_JEFE_FAM := SSN_JEFE_FAM;
SERVICIOS_EMERGENCIA2_DSD.SEGURO_SOCIAL_JEFE_SERV := SSN_JEFE_SERV;
SERVICIOS_EMERGENCIA2_DSD.COD_SERVICIO := COD_SERV;
SERVICIOS_EMERGENCIA2_DSD.RMO_OFICINA:= rmo_gbl;
DB_QUERY(EMERG_ID,EMERG_CODE);
DB_GET_FIRST(EMERG_ID,EMERG_CODE);
DB_DELETE(EMERG_ID,EMERG_CODE);
DB_COMMIT(EMERG_CODE);
DB_CLOSE(EMERG_ID,EMERG_CODE);
SET_NOTRACE();
END;
    



--------------------------------------------------------------------- */
