package gov.dlf.presentation;


import gov.dlf.facade.SAIC_DMQ_ORA_Application;
import gov.dlf.logic.CHECK_NUM_PADRE_MADRE_AUSENTE_MENORES_ADL;
import gov.dlf.logic.CHECK_PADRE_MADRE_AUSENTE_MENORES_PARK_CMD_ADL;
import gov.dlf.logic.PADRE_MADRE_AUSENTE_CLIENTE_MENORES_BV_ADL;
import gov.dlf.logic.SET_SSN_PADRE_AUSENTE_ADL;

import net.maintrend.appmanager.Application;
import net.maintrend.jdatapanel.JDataPanelGroupArguments;
import net.maintrend.jdatapanel.JDataPanelListener;
import net.maintrend.rallyengine.Form;
import net.maintrend.rallyengine.RallyApplication;
import net.maintrend.util.Debug;
import net.maintrend.util.ResourceUtil;



/**
 * __Comment
 *
 * Generated by Rally-to-Java Convertor. MainTrend Ltd.
 */
public class PADRE_MADRE_AUSENTE_CLIENTE_MENORES_FR
     extends Form
{
  // -------------------------------------------------------------------
  // ----------   Instance Attributes   --------------------------------

  /**  */
  public SAIC_DMQ_ORA_Application app;



  // -------------------------------------------------------------------
  // ----------   Constructors and supporting methods   ----------------

  /**
   *
   */
  public PADRE_MADRE_AUSENTE_CLIENTE_MENORES_FR ( )
  {
    super ( );
    this.setName ( "PADRE_MADRE_AUSENTE_CLIENTE_MENORES_FR" );

    Debug.println ( Debug.TRACE, "PADRE_MADRE_AUSENTE_CLIENTE_MENORES_FR - constructor" );

    this.setDefinitionPath ( "gov/dlf/presentation/PADRE_MADRE_AUSENTE_CLIENTE_MENORES_FR.jdp" );
    String definition = ResourceUtil.getResourceText ( this.definitionPath );
    this.setDefinition     ( definition );

    this.setHighLightSelected   ( false );
    this.compressFieldLocations ( false, true );  // Compresses only Y-locations

    this.setUpdateOnInstanceChange ( false );
  }


  /**
   * Overrides ancestor's script
   *
   * @param __app
   */
  public void setApplication ( Application __app )
  {
    this.app = ( SAIC_DMQ_ORA_Application ) __app;
    if ( this.app != null )
    {
      this.setDataManager ( this.app.getDataManager ( ) );
    }

    this.setArguments ( "NOMBRE_PADRE_AUSENTE", new PADRE_MADRE_AUSENTE_CLIENTE_MENORES_FR_NOMBRE_PADRE_AUSENTE_Arguments ( this ) );

    this.setObjectEvents ( );
  }


  /**
   * Overrides ancestor's method
   * 
   * @return
   */
  public RallyApplication getApplication ( )
  {
    return this.app;
  }



  // -------------------------------------------------------------------
  // ----------   Action Sites   ---------------------------------------

  /**
   *
   */
  public void setObjectEvents ( )
  {
    this.registerListener ( "SEGURO_SOCIAL_PADRE_AUSENTE", JDataPanelListener.BEFOREENTER, new JDataPanelListener ( )
    {
      public boolean eventFired ( String eventName )
      {
        app.errorFlag = true; CHECK_NUM_PADRE_MADRE_AUSENTE_MENORES_ADL.exec ( app ); return app.errorFlag;
      }
    } );
    this.registerListener ( "PARK", JDataPanelListener.BEFOREENTER, new JDataPanelListener ( )
    {
      public boolean eventFired ( String eventName )
      {
        app.errorFlag = true; CHECK_NUM_PADRE_MADRE_AUSENTE_MENORES_ADL.exec ( app ); return app.errorFlag;
      }
    } );
    this.registerListener ( "PARK", JDataPanelListener.BEFORELEAVE, new JDataPanelListener ( )
    {
      public boolean eventFired ( String eventName )
      {
        app.errorFlag = true; CHECK_PADRE_MADRE_AUSENTE_MENORES_PARK_CMD_ADL.exec ( app ); return app.errorFlag;
      }
    } );
/*
    this.registerListener ( "COD_TIPO_INGRESO", JDataPanelListener.BEFORELEAVE, new JDataPanelListener ( )
    {
      public boolean eventFired ( String eventName )
      {
        app.errorFlag = true; CHECK_FLAG_BILLETE_ADL.exec ( app ); return app.errorFlag;
      }
    } );
    this.registerListener ( "VLR_CANTIDAD_INGRESO", JDataPanelListener.BEFOREENTER, new JDataPanelListener ( )
    {
      public boolean eventFired ( String eventName )
      {
        app.errorFlag = true; BILLETES_ADL.exec ( app ); return app.errorFlag;
      }
    } );
    this.registerListener ( "FLG_FRECUENCIA", JDataPanelListener.AFTERVALUECHANGE, new JDataPanelListener ( )
    {
      public boolean eventFired ( String eventName )
      {
        app.errorFlag = true; VALIDAR_FRQ_INGRESO_ADL.exec ( app ); return app.errorFlag;
      }
    } );
    this.registerListener ( "FLG_FRECUENCIA", JDataPanelListener.VALIDATION, new JDataPanelListener ( )
    {
      public boolean eventFired ( String eventName )
      {
        app.errorFlag = true; VALIDAR_FRQ_INGRESO_ADL.exec ( app ); return app.errorFlag;
      }
    } );
*/
    this.registerListener ( "PARKING", JDataPanelListener.BEFOREENTER, new JDataPanelListener ( )
    {
      public boolean eventFired ( String eventName )
      {
        app.errorFlag = true; app.callCommand ( "FINISH ACTION" ); return app.errorFlag;
      }
    } );
    this.registerListener ( "INGRESO_CLIENTE", JDataPanelListener.BEFOREENTER, new JDataPanelListener ( )
    {
      public boolean eventFired ( String eventName )
      {
        app.errorFlag = true; PADRE_MADRE_AUSENTE_CLIENTE_MENORES_BV_ADL.exec ( app ); return app.errorFlag;
      }
    } );
    this.registerListener ( "INGRESO_CLIENTE", JDataPanelListener.BEFOREINSERT, new JDataPanelListener ( )
    {
      public boolean eventFired ( String eventName )
      {
        app.errorFlag = true; PADRE_MADRE_AUSENTE_CLIENTE_MENORES_BV_ADL.exec ( app ); return app.errorFlag;
      }
    } );
  }
}





/**
 *
 */
class PADRE_MADRE_AUSENTE_CLIENTE_MENORES_FR_NOMBRE_PADRE_AUSENTE_Arguments extends JDataPanelGroupArguments
{
  /**  */
  protected Form model;
  /**  */
  protected SAIC_DMQ_ORA_Application app = null;

  /**  */
  public PADRE_MADRE_AUSENTE_CLIENTE_MENORES_FR_NOMBRE_PADRE_AUSENTE_Arguments ( Form form )
  {
    this.model = form;

    this.setArgName ( "SSN_PADRE_AUSENTE_PAR" );
  }

  /**  */
  public Object getArgValue ( String argName )
  {
    if ( this.app == null ) this.app = ( SAIC_DMQ_ORA_Application ) this.model.getApplication ( );
    if ( argName == null )
    {
      return null;
    }
    else if ( argName.equals ( "SSN_PADRE_AUSENTE_PAR" ) )
    {
      SET_SSN_PADRE_AUSENTE_ADL.exec ( app );
      return this.app.getSS_PADRE_AUSENTE_GBL ( ); // Global Variable
    }
    return null;
  }
}






