package gov.dlf.logic;


import gov.dlf.external.*;
import gov.dlf.facade.*;
import gov.dlf.presentation.*;


import java.util.*;

import net.maintrend.appmanager.*;
import net.maintrend.datamanager.*;
import net.maintrend.interfaces.*;
import net.maintrend.interlink.*;
import net.maintrend.mdi.*;
import net.maintrend.rallyengine.*;
import net.maintrend.util.*;
import net.maintrend.util.format.*;



/**
 * __Comment
 *
 * Generated by Rally-to-Java Convertor. MainTrend Ltd.
 */
public class CONTACTO_PARK_CONF_BEF_ADL
     extends ADL
{
  // -------------------------------------------------------------------
  // ----------   Class Attributes   -----------------------------------

  /**  */
  public static boolean staticCall = false;



  // -------------------------------------------------------------------
  // ----------   Instance Attributes   --------------------------------

  /**  */
  public SAIC_DMQ_ORA_Application app;
  /**  */
  public RallyDataManager dm = null;



  // -------------------------------------------------------------------
  // ----------   Instance Condition Attributes   ----------------------
 
  public boolean _condition0 = false;
 
  public boolean _condition1 = false;

 

  // -------------------------------------------------------------------
  // ----------   Instance Export Attributes   -------------------------



  public String NULL_CHAR = null;



  // -------------------------------------------------------------------
  // ----------   Instance Attributes' Access Methods   ----------------

  
  /**  */
  public static void setNULL_CHAR  ( RallyApplication __app, Parameter value )
  {
    ( ( CONTACTO_PARK_CONF_BEF_ADL ) __app.getADL ( CONTACTO_PARK_CONF_BEF_ADL.class ) ).NULL_CHAR = value.getString ( );
  }  
    


  /**  */
  public static String getNULL_CHAR  ( RallyApplication __app )
  {
    return ( ( CONTACTO_PARK_CONF_BEF_ADL ) __app.getADL ( CONTACTO_PARK_CONF_BEF_ADL.class ) ).NULL_CHAR;
  }


  /**  */
  public static void setNULL_CHAR  ( RallyApplication __app, String value )
  {
    ( ( CONTACTO_PARK_CONF_BEF_ADL ) __app.getADL ( CONTACTO_PARK_CONF_BEF_ADL.class ) ).NULL_CHAR = value;
  }


  /**  */
  public static void setNULL_CHAR  ( RallyApplication __app, Object value )
  {
    ( ( CONTACTO_PARK_CONF_BEF_ADL ) __app.getADL ( CONTACTO_PARK_CONF_BEF_ADL.class ) ).NULL_CHAR = ( String ) value;
  }





  // -------------------------------------------------------------------
  // ----------   Methods   --------------------------------------------

  /**
   * 
   * @param __app
   * @return
   */
  public static CONTACTO_PARK_CONF_BEF_ADL get ( RallyApplication __app )
  {
    CONTACTO_PARK_CONF_BEF_ADL adl = new CONTACTO_PARK_CONF_BEF_ADL ( );
    __app.register ( adl, "CONTACTO_PARK_CONF_BEF_ADL" );
    __app.setADL ( CONTACTO_PARK_CONF_BEF_ADL.class, adl ); 
    adl.setApplication ( __app );
    return adl;
  }


  /**
   *
   * @param __app
   * @param ps
   *
   * @return
   */
  public static void exec ( RallyApplication __app, ParameterSet ps )
  {
    CONTACTO_PARK_CONF_BEF_ADL.get ( __app ).process ( ps );
  }


  /**
   *
   * @param __app
   *
   * @return
   */
  public static void exec ( RallyApplication __app )
  {
    ParameterSet ps = null;
    CONTACTO_PARK_CONF_BEF_ADL.exec ( __app, ps );
  }


  /**
   * Overrides the ancestor's method
   * 
   * @param __app
   */
  public void setApplication ( RallyApplication __app )
  {
    this.app = ( SAIC_DMQ_ORA_Application ) __app;
    if ( this.app != null )
    {
      this.dm = ( RallyDataManager ) this.app.getDataManager ( );
    }
  }


  /**
   * Overrides the ancestor's method
   * 
   * @param parms
   */
  public void execute ( ParameterSet parms )
  {
    this.process ( parms );
  }




  /**
   *
   */
  protected void doReturn ( )
  {
    this.unregister ( );
  }


  /**
   *
   */
  public void unregister ( )
  {
    this.app.unregister ( this );
    IRegisteredObject rObj = this.app.get ( "CONTACTO_PARK_CONF_BEF_ADL" );
    if ( rObj != null && rObj instanceof CONTACTO_PARK_CONF_BEF_ADL )
    {
      this.app.setADL ( CONTACTO_PARK_CONF_BEF_ADL.class, ( CONTACTO_PARK_CONF_BEF_ADL ) rObj );
    }
  }


  /**
   * Overrides the ancestor's method
   * 
   * @param ps
   */
  protected void process ( ParameterSet ps )
  {
    Debug.println ( Debug.TRACE, "CONTACTO_PARK_CONF_BEF_ADL Step " + this.currentStep );
    super.process ( ps );
    switch ( this.currentStep ) 
    {
      case 0:  { this.currentStep ++; this.step0 ( this.keyParms ); break; }
      case 1:  { this.currentStep ++; this.step1 ( this.keyParms ); break; }
      case 2:  { this.currentStep ++; this.step2 ( this.keyParms ); break; }
      case 3:  { this.currentStep ++; this.step3 ( this.keyParms ); break; }
      default: 
      { 
        this.currentStep = 0;
        Debug.println ( Debug.TRACE, "CONTACTO_PARK_CONF_BEF_ADL ended" );
        this.unregister ( );
        break;
      }
    }
    if ( this.currentStep > 0 ) this.app.goOn ( );
  }



  /**
   *
   */
  protected void step0 ( ParameterSet ps )
  {

    NULL_CHAR = TruncService.setNull ( NULL_CHAR  );
    if ( Compare.equals ( this.app.form ( "CALENDARIO_MAIN_FR" ).getStringItem ( "STS_ACTIVIDAD" ), NULL_CHAR ) ) 
    {
      this._condition0 = true;
    }
    else
    {
      this._condition0 = false;
    }
    if ( this._condition0 )
    {
      CONTACTO_CERRAR_MENU.exec ( this.app );
      return;
    }

  }


  /**
   *
   */
  protected void step1 ( ParameterSet ps )
  {
    if ( this._condition0 )    //    if ( Compare.equals ( this.app.form ( "CALENDARIO_MAIN_FR" ).getStringItem ( "STS_ACTIVIDAD" ), NULL_CHAR ) ) 
    {
      this.app.executeCommand ( RallyAppCommandFactory.EXITACTION );
      return;
    }

  }


  /**
   *
   */
  protected void step2 ( ParameterSet ps )
  {
    if ( this._condition0 )    //    if ( Compare.equals ( this.app.form ( "CALENDARIO_MAIN_FR" ).getStringItem ( "STS_ACTIVIDAD" ), NULL_CHAR ) ) 
    {
      return; 
    }
    if ( Compare.equals ( this.app.CONTACTO_CERRAR_MENU_GBL, "N" ) ) 
    {
      this._condition1 = true;
    }
    else
    {
      this._condition1 = false;
    }
    if ( this._condition1 )
    {
      this.app.executeCommand ( RallyAppCommandFactory.FHOME );
      return;
    }

  }


  /**
   *
   */
  protected void step3 ( ParameterSet ps )
  {
    if ( this._condition1 )    //    if ( Compare.equals ( this.app.CONTACTO_CERRAR_MENU_GBL, "N" ) ) 
    {
      return;
    }
    this.app.CONTACTO_CERRAR_MENU_GBL = " ";

  }
}



/* ---------------------------------------------------------------------


     
  PROCEDURE CONTACTO_PARK_CONF_BEF_ADL;

VAR
        NULL_CHAR       :       CHAR;

BEGIN
set_trace();
        MAKE_NULL (NULL_CHAR);
        IF (CALENDARIO_MAIN_FR.STS_ACTIVIDAD = NULL_CHAR) THEN
        BEGIN
                CALL CONTACTO_CERRAR_MENU;
                EXECUTE_CMD(EXITACTION);
        END;
  if (contacto_cerrar_menu_gbl ='N')then
           execute_cmd(fhome);
  contacto_cerrar_menu_gbl := ' ';
set_notrace();
END;    
    



--------------------------------------------------------------------- */
