package gov.dlf.presentation;


import gov.dlf.facade.*;
import gov.dlf.external.*;
import gov.dlf.logic.*;

import java.util.Date;


import net.maintrend.appmanager.*;
import net.maintrend.datamanager.*;
import net.maintrend.interfaces.*;
import net.maintrend.interlink.*;
import net.maintrend.jdatapanel.*;
import net.maintrend.jdatapanel.edit.*;
import net.maintrend.jdatapanel.commands.*;
import net.maintrend.mdi.*;
import net.maintrend.rallyengine.*;
import net.maintrend.util.*;



/**
 * __Comment
 *
 * Generated by Rally-to-Java Convertor. MainTrend Ltd.
 */
public class FECHAS_SERV_PROVEED_LOV_FR
     extends Form
{
  // -------------------------------------------------------------------
  // ----------   Instance Attributes   --------------------------------

  /**  */
  public SAIC_DMQ_ORA_Application app;



  // -------------------------------------------------------------------
  // ----------   Constructors and supporting methods   ----------------

  /**
   *
   */
  public FECHAS_SERV_PROVEED_LOV_FR ( )
  {
    super ( );
    this.setName ( "FECHAS_SERV_PROVEED_LOV_FR" );

    Debug.println ( Debug.TRACE, "FECHAS_SERV_PROVEED_LOV_FR - constructor" );

    this.setDefinitionPath ( "gov/dlf/presentation/FECHAS_SERV_PROVEED_LOV_FR.jdp" );
    String definition = ResourceUtil.getResourceText ( this.definitionPath );
    this.setDefinition     ( definition );

    this.setHighLightSelected   ( false );
    this.compressFieldLocations ( false, true );  // Compresses only Y-locations
  }
  
  
  /**
   * Overrides ancestor's script
   *
   * @param __app
   */
  public void setApplication ( Application __app )
  {
    this.app = ( SAIC_DMQ_ORA_Application ) __app;
    if ( this.app != null )
    {
      this.setDataManager ( this.app.getDataManager ( ) );
    }

    ICalculator           calculator;
    IBooleanValueProvider txtVisible;
    IBooleanValueProvider groupVisible;
    IObjectValueProvider  valueProvider;
    JDataPanelField       field;
    JDataPanelTextGroup   txtGroup;
    JDataPanelGroup       visGroup;

    this.setArguments ( "PROVEEDOR_GP", new FECHAS_SERV_PROVEED_LOV_FR_PROVEEDOR_GP_Arguments ( this ) );

    this.setObjectEvents ( );



  }


  /**
   * Overrides ancestor's method
   * 
   * @return
   */
  public RallyApplication getApplication ( )
  {
    return this.app;
  }



  // -------------------------------------------------------------------
  // ----------   Action Sites   ---------------------------------------

  /**
   *
   */
  public void setObjectEvents ( )
  {
  }
}





/**
 *
 */
class FECHAS_SERV_PROVEED_LOV_FR_PROVEEDOR_GP_Arguments extends JDataPanelGroupArguments
{
  /**  */
  protected Form model;
  /**  */
  protected SAIC_DMQ_ORA_Application app = null;

  /**  */
  public FECHAS_SERV_PROVEED_LOV_FR_PROVEEDOR_GP_Arguments ( Form form )
  {
    this.model = form;

    this.setArgName ( "PROVEEDOR_SERV_COD_PAR" );
    this.setArgName ( "PARAM_DISP" );
  }

  /**  */
  public Object getArgValue ( String argName )
  {
    if ( this.app == null ) this.app = ( SAIC_DMQ_ORA_Application ) this.model.getApplication ( );
    if ( argName == null )
    {
      return null;
    }
    else if ( argName.equals ( "PROVEEDOR_SERV_COD_PAR" ) )
    {
      return this.app.form ( "FECHAS_SERVICIO_FRM" ).getValue ( "COD_SERVICIO" );
    }
    else if ( argName.equals ( "PARAM_DISP" ) )
    {
      return this.app.form ( "FECHAS_SERVICIO_FRM" ).getValue ( "VLR_BENEFICIOS" );
    }
    return null;
  }
}






