package gov.dlf.logic;


import gov.dlf.facade.*;
import java.util.*;

import net.maintrend.interfaces.*;
import net.maintrend.interlink.*;
import net.maintrend.rallyengine.*;
import net.maintrend.util.*;
import net.maintrend.util.format.*;



/**
 * __Comment
 *
 * Generated by Rally-to-Java Convertor. MainTrend Ltd.
 */
public class CALENDARIO_MAIN_CONSOLIDAR_FECHAS_ADL
     extends ADL
{
  // -------------------------------------------------------------------
  // ----------   Class Attributes   -----------------------------------

  /**  */
  public static boolean staticCall = true;



  // -------------------------------------------------------------------
  // ----------   Instance Attributes   --------------------------------

  /**  */
  public SAIC_DMQ_ORA_Application app;
  /**  */
  public RallyDataManager dm = null;



  // -------------------------------------------------------------------
  // ----------   Instance Condition Attributes   ----------------------
 
  public boolean _condition0 = false;
 
  public boolean _condition1 = false;
 
  public boolean _condition2 = false;
 
  public boolean _condition3 = false;
 
  public boolean _condition4 = false;
 
  public boolean _condition5 = false;
 
  public boolean _condition6 = false;
 
  public boolean _condition7 = false;
 
  public boolean _condition8 = false;
 
  public boolean _condition9 = false;
 
  public boolean _condition10 = false;

 

  // -------------------------------------------------------------------
  // ----------   Instance Export Attributes   -------------------------

  public double DHM_OLD_HH = 0;

  public double DHM_OLD_MI = 0;

  public double DUR_OLD_HH = 0;

  public double DUR_OLD_MI = 0;

  public double DHM_NEW_HH = 0;

  public double DHM_NEW_MI = 0;

  public double DUR_NEW_HH = 0;

  public double DUR_NEW_MI = 0;

  public double TOTAL_MI = 0;

  public double TOTAL_HH = 0;

  public double RESTO_HH = 0;

  public double JEFE_SERVICIO = 0;

  public double COUNT_AUX = 0;



  public Date DHM_OLD = null;

  public Date DUR_OLD = null;

  public String DHM_OLD_CHAR = null;

  public String DUR_OLD_CHAR = null;

  public String DHM_OLD_FCH_CHAR = null;

  public Date DHM_OLD_MAIS_DUR_OLD = null;

  public Date DHM_NEW = null;

  public Date DUR_NEW = null;

  public String DHM_NEW_CHAR = null;

  public String DUR_NEW_CHAR = null;

  public String DHM_NEW_FCH_CHAR = null;

  public Date DHM_NEW_MAIS_DUR_NEW = null;

  public String TOTAL_HH_CHAR = null;

  public String TOTAL_MI_CHAR = null;

  public String COD_SERVICIO = null;

  public String COD_RAZON = null;



  // -------------------------------------------------------------------
  // ----------   Instance Attributes' Access Methods   ----------------

  
  /**  */
  public static void setDHM_OLD  ( RallyApplication __app, Parameter value )
  {
    ( ( CALENDARIO_MAIN_CONSOLIDAR_FECHAS_ADL ) __app.getADL ( CALENDARIO_MAIN_CONSOLIDAR_FECHAS_ADL.class ) ).DHM_OLD = value.getDate ( );
  }  

  
  /**  */
  public static void setDUR_OLD  ( RallyApplication __app, Parameter value )
  {
    ( ( CALENDARIO_MAIN_CONSOLIDAR_FECHAS_ADL ) __app.getADL ( CALENDARIO_MAIN_CONSOLIDAR_FECHAS_ADL.class ) ).DUR_OLD = value.getDate ( );
  }  

  
  /**  */
  public static void setDHM_OLD_CHAR  ( RallyApplication __app, Parameter value )
  {
    ( ( CALENDARIO_MAIN_CONSOLIDAR_FECHAS_ADL ) __app.getADL ( CALENDARIO_MAIN_CONSOLIDAR_FECHAS_ADL.class ) ).DHM_OLD_CHAR = value.getString ( );
  }  

  
  /**  */
  public static void setDUR_OLD_CHAR  ( RallyApplication __app, Parameter value )
  {
    ( ( CALENDARIO_MAIN_CONSOLIDAR_FECHAS_ADL ) __app.getADL ( CALENDARIO_MAIN_CONSOLIDAR_FECHAS_ADL.class ) ).DUR_OLD_CHAR = value.getString ( );
  }  

  
  /**  */
  public static void setDHM_OLD_FCH_CHAR  ( RallyApplication __app, Parameter value )
  {
    ( ( CALENDARIO_MAIN_CONSOLIDAR_FECHAS_ADL ) __app.getADL ( CALENDARIO_MAIN_CONSOLIDAR_FECHAS_ADL.class ) ).DHM_OLD_FCH_CHAR = value.getString ( );
  }  

  
  /**  */
  public static void setDHM_OLD_MAIS_DUR_OLD  ( RallyApplication __app, Parameter value )
  {
    ( ( CALENDARIO_MAIN_CONSOLIDAR_FECHAS_ADL ) __app.getADL ( CALENDARIO_MAIN_CONSOLIDAR_FECHAS_ADL.class ) ).DHM_OLD_MAIS_DUR_OLD = value.getDate ( );
  }  

  
  /**  */
  public static void setDHM_NEW  ( RallyApplication __app, Parameter value )
  {
    ( ( CALENDARIO_MAIN_CONSOLIDAR_FECHAS_ADL ) __app.getADL ( CALENDARIO_MAIN_CONSOLIDAR_FECHAS_ADL.class ) ).DHM_NEW = value.getDate ( );
  }  

  
  /**  */
  public static void setDUR_NEW  ( RallyApplication __app, Parameter value )
  {
    ( ( CALENDARIO_MAIN_CONSOLIDAR_FECHAS_ADL ) __app.getADL ( CALENDARIO_MAIN_CONSOLIDAR_FECHAS_ADL.class ) ).DUR_NEW = value.getDate ( );
  }  

  
  /**  */
  public static void setDHM_NEW_CHAR  ( RallyApplication __app, Parameter value )
  {
    ( ( CALENDARIO_MAIN_CONSOLIDAR_FECHAS_ADL ) __app.getADL ( CALENDARIO_MAIN_CONSOLIDAR_FECHAS_ADL.class ) ).DHM_NEW_CHAR = value.getString ( );
  }  

  
  /**  */
  public static void setDUR_NEW_CHAR  ( RallyApplication __app, Parameter value )
  {
    ( ( CALENDARIO_MAIN_CONSOLIDAR_FECHAS_ADL ) __app.getADL ( CALENDARIO_MAIN_CONSOLIDAR_FECHAS_ADL.class ) ).DUR_NEW_CHAR = value.getString ( );
  }  

  
  /**  */
  public static void setDHM_NEW_FCH_CHAR  ( RallyApplication __app, Parameter value )
  {
    ( ( CALENDARIO_MAIN_CONSOLIDAR_FECHAS_ADL ) __app.getADL ( CALENDARIO_MAIN_CONSOLIDAR_FECHAS_ADL.class ) ).DHM_NEW_FCH_CHAR = value.getString ( );
  }  

  
  /**  */
  public static void setDHM_NEW_MAIS_DUR_NEW  ( RallyApplication __app, Parameter value )
  {
    ( ( CALENDARIO_MAIN_CONSOLIDAR_FECHAS_ADL ) __app.getADL ( CALENDARIO_MAIN_CONSOLIDAR_FECHAS_ADL.class ) ).DHM_NEW_MAIS_DUR_NEW = value.getDate ( );
  }  

  
  /**  */
  public static void setDHM_OLD_HH  ( RallyApplication __app, Parameter value )
  {
    ( ( CALENDARIO_MAIN_CONSOLIDAR_FECHAS_ADL ) __app.getADL ( CALENDARIO_MAIN_CONSOLIDAR_FECHAS_ADL.class ) ).DHM_OLD_HH = value.getDouble ( );
  }  

  
  /**  */
  public static void setDHM_OLD_MI  ( RallyApplication __app, Parameter value )
  {
    ( ( CALENDARIO_MAIN_CONSOLIDAR_FECHAS_ADL ) __app.getADL ( CALENDARIO_MAIN_CONSOLIDAR_FECHAS_ADL.class ) ).DHM_OLD_MI = value.getDouble ( );
  }  

  
  /**  */
  public static void setDUR_OLD_HH  ( RallyApplication __app, Parameter value )
  {
    ( ( CALENDARIO_MAIN_CONSOLIDAR_FECHAS_ADL ) __app.getADL ( CALENDARIO_MAIN_CONSOLIDAR_FECHAS_ADL.class ) ).DUR_OLD_HH = value.getDouble ( );
  }  

  
  /**  */
  public static void setDUR_OLD_MI  ( RallyApplication __app, Parameter value )
  {
    ( ( CALENDARIO_MAIN_CONSOLIDAR_FECHAS_ADL ) __app.getADL ( CALENDARIO_MAIN_CONSOLIDAR_FECHAS_ADL.class ) ).DUR_OLD_MI = value.getDouble ( );
  }  

  
  /**  */
  public static void setDHM_NEW_HH  ( RallyApplication __app, Parameter value )
  {
    ( ( CALENDARIO_MAIN_CONSOLIDAR_FECHAS_ADL ) __app.getADL ( CALENDARIO_MAIN_CONSOLIDAR_FECHAS_ADL.class ) ).DHM_NEW_HH = value.getDouble ( );
  }  

  
  /**  */
  public static void setDHM_NEW_MI  ( RallyApplication __app, Parameter value )
  {
    ( ( CALENDARIO_MAIN_CONSOLIDAR_FECHAS_ADL ) __app.getADL ( CALENDARIO_MAIN_CONSOLIDAR_FECHAS_ADL.class ) ).DHM_NEW_MI = value.getDouble ( );
  }  

  
  /**  */
  public static void setDUR_NEW_HH  ( RallyApplication __app, Parameter value )
  {
    ( ( CALENDARIO_MAIN_CONSOLIDAR_FECHAS_ADL ) __app.getADL ( CALENDARIO_MAIN_CONSOLIDAR_FECHAS_ADL.class ) ).DUR_NEW_HH = value.getDouble ( );
  }  

  
  /**  */
  public static void setDUR_NEW_MI  ( RallyApplication __app, Parameter value )
  {
    ( ( CALENDARIO_MAIN_CONSOLIDAR_FECHAS_ADL ) __app.getADL ( CALENDARIO_MAIN_CONSOLIDAR_FECHAS_ADL.class ) ).DUR_NEW_MI = value.getDouble ( );
  }  

  
  /**  */
  public static void setTOTAL_MI  ( RallyApplication __app, Parameter value )
  {
    ( ( CALENDARIO_MAIN_CONSOLIDAR_FECHAS_ADL ) __app.getADL ( CALENDARIO_MAIN_CONSOLIDAR_FECHAS_ADL.class ) ).TOTAL_MI = value.getDouble ( );
  }  

  
  /**  */
  public static void setTOTAL_HH  ( RallyApplication __app, Parameter value )
  {
    ( ( CALENDARIO_MAIN_CONSOLIDAR_FECHAS_ADL ) __app.getADL ( CALENDARIO_MAIN_CONSOLIDAR_FECHAS_ADL.class ) ).TOTAL_HH = value.getDouble ( );
  }  

  
  /**  */
  public static void setRESTO_HH  ( RallyApplication __app, Parameter value )
  {
    ( ( CALENDARIO_MAIN_CONSOLIDAR_FECHAS_ADL ) __app.getADL ( CALENDARIO_MAIN_CONSOLIDAR_FECHAS_ADL.class ) ).RESTO_HH = value.getDouble ( );
  }  

  
  /**  */
  public static void setTOTAL_HH_CHAR  ( RallyApplication __app, Parameter value )
  {
    ( ( CALENDARIO_MAIN_CONSOLIDAR_FECHAS_ADL ) __app.getADL ( CALENDARIO_MAIN_CONSOLIDAR_FECHAS_ADL.class ) ).TOTAL_HH_CHAR = value.getString ( );
  }  

  
  /**  */
  public static void setTOTAL_MI_CHAR  ( RallyApplication __app, Parameter value )
  {
    ( ( CALENDARIO_MAIN_CONSOLIDAR_FECHAS_ADL ) __app.getADL ( CALENDARIO_MAIN_CONSOLIDAR_FECHAS_ADL.class ) ).TOTAL_MI_CHAR = value.getString ( );
  }  

  
  /**  */
  public static void setCOD_SERVICIO  ( RallyApplication __app, Parameter value )
  {
    ( ( CALENDARIO_MAIN_CONSOLIDAR_FECHAS_ADL ) __app.getADL ( CALENDARIO_MAIN_CONSOLIDAR_FECHAS_ADL.class ) ).COD_SERVICIO = value.getString ( );
  }  

  
  /**  */
  public static void setCOD_RAZON  ( RallyApplication __app, Parameter value )
  {
    ( ( CALENDARIO_MAIN_CONSOLIDAR_FECHAS_ADL ) __app.getADL ( CALENDARIO_MAIN_CONSOLIDAR_FECHAS_ADL.class ) ).COD_RAZON = value.getString ( );
  }  

  
  /**  */
  public static void setJEFE_SERVICIO  ( RallyApplication __app, Parameter value )
  {
    ( ( CALENDARIO_MAIN_CONSOLIDAR_FECHAS_ADL ) __app.getADL ( CALENDARIO_MAIN_CONSOLIDAR_FECHAS_ADL.class ) ).JEFE_SERVICIO = value.getDouble ( );
  }  

  
  /**  */
  public static void setCOUNT_AUX  ( RallyApplication __app, Parameter value )
  {
    ( ( CALENDARIO_MAIN_CONSOLIDAR_FECHAS_ADL ) __app.getADL ( CALENDARIO_MAIN_CONSOLIDAR_FECHAS_ADL.class ) ).COUNT_AUX = value.getDouble ( );
  }  
    


  /**  */
  public static Date getDHM_OLD  ( RallyApplication __app )
  {
    return ( ( CALENDARIO_MAIN_CONSOLIDAR_FECHAS_ADL ) __app.getADL ( CALENDARIO_MAIN_CONSOLIDAR_FECHAS_ADL.class ) ).DHM_OLD;
  }


  /**  */
  public static void setDHM_OLD  ( RallyApplication __app, Date value )
  {
    ( ( CALENDARIO_MAIN_CONSOLIDAR_FECHAS_ADL ) __app.getADL ( CALENDARIO_MAIN_CONSOLIDAR_FECHAS_ADL.class ) ).DHM_OLD = value;
  }


  /**  */
  public static void setDHM_OLD  ( RallyApplication __app, Object value )
  {
    ( ( CALENDARIO_MAIN_CONSOLIDAR_FECHAS_ADL ) __app.getADL ( CALENDARIO_MAIN_CONSOLIDAR_FECHAS_ADL.class ) ).DHM_OLD = ( Date ) value;
  }



  /**  */
  public static Date getDUR_OLD  ( RallyApplication __app )
  {
    return ( ( CALENDARIO_MAIN_CONSOLIDAR_FECHAS_ADL ) __app.getADL ( CALENDARIO_MAIN_CONSOLIDAR_FECHAS_ADL.class ) ).DUR_OLD;
  }


  /**  */
  public static void setDUR_OLD  ( RallyApplication __app, Date value )
  {
    ( ( CALENDARIO_MAIN_CONSOLIDAR_FECHAS_ADL ) __app.getADL ( CALENDARIO_MAIN_CONSOLIDAR_FECHAS_ADL.class ) ).DUR_OLD = value;
  }


  /**  */
  public static void setDUR_OLD  ( RallyApplication __app, Object value )
  {
    ( ( CALENDARIO_MAIN_CONSOLIDAR_FECHAS_ADL ) __app.getADL ( CALENDARIO_MAIN_CONSOLIDAR_FECHAS_ADL.class ) ).DUR_OLD = ( Date ) value;
  }



  /**  */
  public static String getDHM_OLD_CHAR  ( RallyApplication __app )
  {
    return ( ( CALENDARIO_MAIN_CONSOLIDAR_FECHAS_ADL ) __app.getADL ( CALENDARIO_MAIN_CONSOLIDAR_FECHAS_ADL.class ) ).DHM_OLD_CHAR;
  }


  /**  */
  public static void setDHM_OLD_CHAR  ( RallyApplication __app, String value )
  {
    ( ( CALENDARIO_MAIN_CONSOLIDAR_FECHAS_ADL ) __app.getADL ( CALENDARIO_MAIN_CONSOLIDAR_FECHAS_ADL.class ) ).DHM_OLD_CHAR = value;
  }


  /**  */
  public static void setDHM_OLD_CHAR  ( RallyApplication __app, Object value )
  {
    ( ( CALENDARIO_MAIN_CONSOLIDAR_FECHAS_ADL ) __app.getADL ( CALENDARIO_MAIN_CONSOLIDAR_FECHAS_ADL.class ) ).DHM_OLD_CHAR = ( String ) value;
  }



  /**  */
  public static String getDUR_OLD_CHAR  ( RallyApplication __app )
  {
    return ( ( CALENDARIO_MAIN_CONSOLIDAR_FECHAS_ADL ) __app.getADL ( CALENDARIO_MAIN_CONSOLIDAR_FECHAS_ADL.class ) ).DUR_OLD_CHAR;
  }


  /**  */
  public static void setDUR_OLD_CHAR  ( RallyApplication __app, String value )
  {
    ( ( CALENDARIO_MAIN_CONSOLIDAR_FECHAS_ADL ) __app.getADL ( CALENDARIO_MAIN_CONSOLIDAR_FECHAS_ADL.class ) ).DUR_OLD_CHAR = value;
  }


  /**  */
  public static void setDUR_OLD_CHAR  ( RallyApplication __app, Object value )
  {
    ( ( CALENDARIO_MAIN_CONSOLIDAR_FECHAS_ADL ) __app.getADL ( CALENDARIO_MAIN_CONSOLIDAR_FECHAS_ADL.class ) ).DUR_OLD_CHAR = ( String ) value;
  }



  /**  */
  public static String getDHM_OLD_FCH_CHAR  ( RallyApplication __app )
  {
    return ( ( CALENDARIO_MAIN_CONSOLIDAR_FECHAS_ADL ) __app.getADL ( CALENDARIO_MAIN_CONSOLIDAR_FECHAS_ADL.class ) ).DHM_OLD_FCH_CHAR;
  }


  /**  */
  public static void setDHM_OLD_FCH_CHAR  ( RallyApplication __app, String value )
  {
    ( ( CALENDARIO_MAIN_CONSOLIDAR_FECHAS_ADL ) __app.getADL ( CALENDARIO_MAIN_CONSOLIDAR_FECHAS_ADL.class ) ).DHM_OLD_FCH_CHAR = value;
  }


  /**  */
  public static void setDHM_OLD_FCH_CHAR  ( RallyApplication __app, Object value )
  {
    ( ( CALENDARIO_MAIN_CONSOLIDAR_FECHAS_ADL ) __app.getADL ( CALENDARIO_MAIN_CONSOLIDAR_FECHAS_ADL.class ) ).DHM_OLD_FCH_CHAR = ( String ) value;
  }



  /**  */
  public static Date getDHM_OLD_MAIS_DUR_OLD  ( RallyApplication __app )
  {
    return ( ( CALENDARIO_MAIN_CONSOLIDAR_FECHAS_ADL ) __app.getADL ( CALENDARIO_MAIN_CONSOLIDAR_FECHAS_ADL.class ) ).DHM_OLD_MAIS_DUR_OLD;
  }


  /**  */
  public static void setDHM_OLD_MAIS_DUR_OLD  ( RallyApplication __app, Date value )
  {
    ( ( CALENDARIO_MAIN_CONSOLIDAR_FECHAS_ADL ) __app.getADL ( CALENDARIO_MAIN_CONSOLIDAR_FECHAS_ADL.class ) ).DHM_OLD_MAIS_DUR_OLD = value;
  }


  /**  */
  public static void setDHM_OLD_MAIS_DUR_OLD  ( RallyApplication __app, Object value )
  {
    ( ( CALENDARIO_MAIN_CONSOLIDAR_FECHAS_ADL ) __app.getADL ( CALENDARIO_MAIN_CONSOLIDAR_FECHAS_ADL.class ) ).DHM_OLD_MAIS_DUR_OLD = ( Date ) value;
  }



  /**  */
  public static Date getDHM_NEW  ( RallyApplication __app )
  {
    return ( ( CALENDARIO_MAIN_CONSOLIDAR_FECHAS_ADL ) __app.getADL ( CALENDARIO_MAIN_CONSOLIDAR_FECHAS_ADL.class ) ).DHM_NEW;
  }


  /**  */
  public static void setDHM_NEW  ( RallyApplication __app, Date value )
  {
    ( ( CALENDARIO_MAIN_CONSOLIDAR_FECHAS_ADL ) __app.getADL ( CALENDARIO_MAIN_CONSOLIDAR_FECHAS_ADL.class ) ).DHM_NEW = value;
  }


  /**  */
  public static void setDHM_NEW  ( RallyApplication __app, Object value )
  {
    ( ( CALENDARIO_MAIN_CONSOLIDAR_FECHAS_ADL ) __app.getADL ( CALENDARIO_MAIN_CONSOLIDAR_FECHAS_ADL.class ) ).DHM_NEW = ( Date ) value;
  }



  /**  */
  public static Date getDUR_NEW  ( RallyApplication __app )
  {
    return ( ( CALENDARIO_MAIN_CONSOLIDAR_FECHAS_ADL ) __app.getADL ( CALENDARIO_MAIN_CONSOLIDAR_FECHAS_ADL.class ) ).DUR_NEW;
  }


  /**  */
  public static void setDUR_NEW  ( RallyApplication __app, Date value )
  {
    ( ( CALENDARIO_MAIN_CONSOLIDAR_FECHAS_ADL ) __app.getADL ( CALENDARIO_MAIN_CONSOLIDAR_FECHAS_ADL.class ) ).DUR_NEW = value;
  }


  /**  */
  public static void setDUR_NEW  ( RallyApplication __app, Object value )
  {
    ( ( CALENDARIO_MAIN_CONSOLIDAR_FECHAS_ADL ) __app.getADL ( CALENDARIO_MAIN_CONSOLIDAR_FECHAS_ADL.class ) ).DUR_NEW = ( Date ) value;
  }



  /**  */
  public static String getDHM_NEW_CHAR  ( RallyApplication __app )
  {
    return ( ( CALENDARIO_MAIN_CONSOLIDAR_FECHAS_ADL ) __app.getADL ( CALENDARIO_MAIN_CONSOLIDAR_FECHAS_ADL.class ) ).DHM_NEW_CHAR;
  }


  /**  */
  public static void setDHM_NEW_CHAR  ( RallyApplication __app, String value )
  {
    ( ( CALENDARIO_MAIN_CONSOLIDAR_FECHAS_ADL ) __app.getADL ( CALENDARIO_MAIN_CONSOLIDAR_FECHAS_ADL.class ) ).DHM_NEW_CHAR = value;
  }


  /**  */
  public static void setDHM_NEW_CHAR  ( RallyApplication __app, Object value )
  {
    ( ( CALENDARIO_MAIN_CONSOLIDAR_FECHAS_ADL ) __app.getADL ( CALENDARIO_MAIN_CONSOLIDAR_FECHAS_ADL.class ) ).DHM_NEW_CHAR = ( String ) value;
  }



  /**  */
  public static String getDUR_NEW_CHAR  ( RallyApplication __app )
  {
    return ( ( CALENDARIO_MAIN_CONSOLIDAR_FECHAS_ADL ) __app.getADL ( CALENDARIO_MAIN_CONSOLIDAR_FECHAS_ADL.class ) ).DUR_NEW_CHAR;
  }


  /**  */
  public static void setDUR_NEW_CHAR  ( RallyApplication __app, String value )
  {
    ( ( CALENDARIO_MAIN_CONSOLIDAR_FECHAS_ADL ) __app.getADL ( CALENDARIO_MAIN_CONSOLIDAR_FECHAS_ADL.class ) ).DUR_NEW_CHAR = value;
  }


  /**  */
  public static void setDUR_NEW_CHAR  ( RallyApplication __app, Object value )
  {
    ( ( CALENDARIO_MAIN_CONSOLIDAR_FECHAS_ADL ) __app.getADL ( CALENDARIO_MAIN_CONSOLIDAR_FECHAS_ADL.class ) ).DUR_NEW_CHAR = ( String ) value;
  }



  /**  */
  public static String getDHM_NEW_FCH_CHAR  ( RallyApplication __app )
  {
    return ( ( CALENDARIO_MAIN_CONSOLIDAR_FECHAS_ADL ) __app.getADL ( CALENDARIO_MAIN_CONSOLIDAR_FECHAS_ADL.class ) ).DHM_NEW_FCH_CHAR;
  }


  /**  */
  public static void setDHM_NEW_FCH_CHAR  ( RallyApplication __app, String value )
  {
    ( ( CALENDARIO_MAIN_CONSOLIDAR_FECHAS_ADL ) __app.getADL ( CALENDARIO_MAIN_CONSOLIDAR_FECHAS_ADL.class ) ).DHM_NEW_FCH_CHAR = value;
  }


  /**  */
  public static void setDHM_NEW_FCH_CHAR  ( RallyApplication __app, Object value )
  {
    ( ( CALENDARIO_MAIN_CONSOLIDAR_FECHAS_ADL ) __app.getADL ( CALENDARIO_MAIN_CONSOLIDAR_FECHAS_ADL.class ) ).DHM_NEW_FCH_CHAR = ( String ) value;
  }



  /**  */
  public static Date getDHM_NEW_MAIS_DUR_NEW  ( RallyApplication __app )
  {
    return ( ( CALENDARIO_MAIN_CONSOLIDAR_FECHAS_ADL ) __app.getADL ( CALENDARIO_MAIN_CONSOLIDAR_FECHAS_ADL.class ) ).DHM_NEW_MAIS_DUR_NEW;
  }


  /**  */
  public static void setDHM_NEW_MAIS_DUR_NEW  ( RallyApplication __app, Date value )
  {
    ( ( CALENDARIO_MAIN_CONSOLIDAR_FECHAS_ADL ) __app.getADL ( CALENDARIO_MAIN_CONSOLIDAR_FECHAS_ADL.class ) ).DHM_NEW_MAIS_DUR_NEW = value;
  }


  /**  */
  public static void setDHM_NEW_MAIS_DUR_NEW  ( RallyApplication __app, Object value )
  {
    ( ( CALENDARIO_MAIN_CONSOLIDAR_FECHAS_ADL ) __app.getADL ( CALENDARIO_MAIN_CONSOLIDAR_FECHAS_ADL.class ) ).DHM_NEW_MAIS_DUR_NEW = ( Date ) value;
  }



  /**  */
  public static String getTOTAL_HH_CHAR  ( RallyApplication __app )
  {
    return ( ( CALENDARIO_MAIN_CONSOLIDAR_FECHAS_ADL ) __app.getADL ( CALENDARIO_MAIN_CONSOLIDAR_FECHAS_ADL.class ) ).TOTAL_HH_CHAR;
  }


  /**  */
  public static void setTOTAL_HH_CHAR  ( RallyApplication __app, String value )
  {
    ( ( CALENDARIO_MAIN_CONSOLIDAR_FECHAS_ADL ) __app.getADL ( CALENDARIO_MAIN_CONSOLIDAR_FECHAS_ADL.class ) ).TOTAL_HH_CHAR = value;
  }


  /**  */
  public static void setTOTAL_HH_CHAR  ( RallyApplication __app, Object value )
  {
    ( ( CALENDARIO_MAIN_CONSOLIDAR_FECHAS_ADL ) __app.getADL ( CALENDARIO_MAIN_CONSOLIDAR_FECHAS_ADL.class ) ).TOTAL_HH_CHAR = ( String ) value;
  }



  /**  */
  public static String getTOTAL_MI_CHAR  ( RallyApplication __app )
  {
    return ( ( CALENDARIO_MAIN_CONSOLIDAR_FECHAS_ADL ) __app.getADL ( CALENDARIO_MAIN_CONSOLIDAR_FECHAS_ADL.class ) ).TOTAL_MI_CHAR;
  }


  /**  */
  public static void setTOTAL_MI_CHAR  ( RallyApplication __app, String value )
  {
    ( ( CALENDARIO_MAIN_CONSOLIDAR_FECHAS_ADL ) __app.getADL ( CALENDARIO_MAIN_CONSOLIDAR_FECHAS_ADL.class ) ).TOTAL_MI_CHAR = value;
  }


  /**  */
  public static void setTOTAL_MI_CHAR  ( RallyApplication __app, Object value )
  {
    ( ( CALENDARIO_MAIN_CONSOLIDAR_FECHAS_ADL ) __app.getADL ( CALENDARIO_MAIN_CONSOLIDAR_FECHAS_ADL.class ) ).TOTAL_MI_CHAR = ( String ) value;
  }



  /**  */
  public static String getCOD_SERVICIO  ( RallyApplication __app )
  {
    return ( ( CALENDARIO_MAIN_CONSOLIDAR_FECHAS_ADL ) __app.getADL ( CALENDARIO_MAIN_CONSOLIDAR_FECHAS_ADL.class ) ).COD_SERVICIO;
  }


  /**  */
  public static void setCOD_SERVICIO  ( RallyApplication __app, String value )
  {
    ( ( CALENDARIO_MAIN_CONSOLIDAR_FECHAS_ADL ) __app.getADL ( CALENDARIO_MAIN_CONSOLIDAR_FECHAS_ADL.class ) ).COD_SERVICIO = value;
  }


  /**  */
  public static void setCOD_SERVICIO  ( RallyApplication __app, Object value )
  {
    ( ( CALENDARIO_MAIN_CONSOLIDAR_FECHAS_ADL ) __app.getADL ( CALENDARIO_MAIN_CONSOLIDAR_FECHAS_ADL.class ) ).COD_SERVICIO = ( String ) value;
  }



  /**  */
  public static String getCOD_RAZON  ( RallyApplication __app )
  {
    return ( ( CALENDARIO_MAIN_CONSOLIDAR_FECHAS_ADL ) __app.getADL ( CALENDARIO_MAIN_CONSOLIDAR_FECHAS_ADL.class ) ).COD_RAZON;
  }


  /**  */
  public static void setCOD_RAZON  ( RallyApplication __app, String value )
  {
    ( ( CALENDARIO_MAIN_CONSOLIDAR_FECHAS_ADL ) __app.getADL ( CALENDARIO_MAIN_CONSOLIDAR_FECHAS_ADL.class ) ).COD_RAZON = value;
  }


  /**  */
  public static void setCOD_RAZON  ( RallyApplication __app, Object value )
  {
    ( ( CALENDARIO_MAIN_CONSOLIDAR_FECHAS_ADL ) __app.getADL ( CALENDARIO_MAIN_CONSOLIDAR_FECHAS_ADL.class ) ).COD_RAZON = ( String ) value;
  }




  /**  */
  public static double getDHM_OLD_HH  ( RallyApplication __app )
  {
    return ( ( CALENDARIO_MAIN_CONSOLIDAR_FECHAS_ADL ) __app.getADL ( CALENDARIO_MAIN_CONSOLIDAR_FECHAS_ADL.class ) ).DHM_OLD_HH;
  }


  /**  */
  public static Double getDHM_OLD_HHDouble ( RallyApplication __app )
  {
    return new Double ( ( ( CALENDARIO_MAIN_CONSOLIDAR_FECHAS_ADL ) __app.getADL ( CALENDARIO_MAIN_CONSOLIDAR_FECHAS_ADL.class ) ).DHM_OLD_HH );
  }


  /**  */
  public static void setDHM_OLD_HH  ( RallyApplication __app, double value )
  {
    ( ( CALENDARIO_MAIN_CONSOLIDAR_FECHAS_ADL ) __app.getADL ( CALENDARIO_MAIN_CONSOLIDAR_FECHAS_ADL.class ) ).DHM_OLD_HH = value;
  }


  /**  */
  public static void setDHM_OLD_HH  ( RallyApplication __app, Object value )
  {
    ( ( CALENDARIO_MAIN_CONSOLIDAR_FECHAS_ADL ) __app.getADL ( CALENDARIO_MAIN_CONSOLIDAR_FECHAS_ADL.class ) ).DHM_OLD_HH = ( ( Double ) value ).doubleValue ( );
  }


  /**  */
  public static double getDHM_OLD_MI  ( RallyApplication __app )
  {
    return ( ( CALENDARIO_MAIN_CONSOLIDAR_FECHAS_ADL ) __app.getADL ( CALENDARIO_MAIN_CONSOLIDAR_FECHAS_ADL.class ) ).DHM_OLD_MI;
  }


  /**  */
  public static Double getDHM_OLD_MIDouble ( RallyApplication __app )
  {
    return new Double ( ( ( CALENDARIO_MAIN_CONSOLIDAR_FECHAS_ADL ) __app.getADL ( CALENDARIO_MAIN_CONSOLIDAR_FECHAS_ADL.class ) ).DHM_OLD_MI );
  }


  /**  */
  public static void setDHM_OLD_MI  ( RallyApplication __app, double value )
  {
    ( ( CALENDARIO_MAIN_CONSOLIDAR_FECHAS_ADL ) __app.getADL ( CALENDARIO_MAIN_CONSOLIDAR_FECHAS_ADL.class ) ).DHM_OLD_MI = value;
  }


  /**  */
  public static void setDHM_OLD_MI  ( RallyApplication __app, Object value )
  {
    ( ( CALENDARIO_MAIN_CONSOLIDAR_FECHAS_ADL ) __app.getADL ( CALENDARIO_MAIN_CONSOLIDAR_FECHAS_ADL.class ) ).DHM_OLD_MI = ( ( Double ) value ).doubleValue ( );
  }


  /**  */
  public static double getDUR_OLD_HH  ( RallyApplication __app )
  {
    return ( ( CALENDARIO_MAIN_CONSOLIDAR_FECHAS_ADL ) __app.getADL ( CALENDARIO_MAIN_CONSOLIDAR_FECHAS_ADL.class ) ).DUR_OLD_HH;
  }


  /**  */
  public static Double getDUR_OLD_HHDouble ( RallyApplication __app )
  {
    return new Double ( ( ( CALENDARIO_MAIN_CONSOLIDAR_FECHAS_ADL ) __app.getADL ( CALENDARIO_MAIN_CONSOLIDAR_FECHAS_ADL.class ) ).DUR_OLD_HH );
  }


  /**  */
  public static void setDUR_OLD_HH  ( RallyApplication __app, double value )
  {
    ( ( CALENDARIO_MAIN_CONSOLIDAR_FECHAS_ADL ) __app.getADL ( CALENDARIO_MAIN_CONSOLIDAR_FECHAS_ADL.class ) ).DUR_OLD_HH = value;
  }


  /**  */
  public static void setDUR_OLD_HH  ( RallyApplication __app, Object value )
  {
    ( ( CALENDARIO_MAIN_CONSOLIDAR_FECHAS_ADL ) __app.getADL ( CALENDARIO_MAIN_CONSOLIDAR_FECHAS_ADL.class ) ).DUR_OLD_HH = ( ( Double ) value ).doubleValue ( );
  }


  /**  */
  public static double getDUR_OLD_MI  ( RallyApplication __app )
  {
    return ( ( CALENDARIO_MAIN_CONSOLIDAR_FECHAS_ADL ) __app.getADL ( CALENDARIO_MAIN_CONSOLIDAR_FECHAS_ADL.class ) ).DUR_OLD_MI;
  }


  /**  */
  public static Double getDUR_OLD_MIDouble ( RallyApplication __app )
  {
    return new Double ( ( ( CALENDARIO_MAIN_CONSOLIDAR_FECHAS_ADL ) __app.getADL ( CALENDARIO_MAIN_CONSOLIDAR_FECHAS_ADL.class ) ).DUR_OLD_MI );
  }


  /**  */
  public static void setDUR_OLD_MI  ( RallyApplication __app, double value )
  {
    ( ( CALENDARIO_MAIN_CONSOLIDAR_FECHAS_ADL ) __app.getADL ( CALENDARIO_MAIN_CONSOLIDAR_FECHAS_ADL.class ) ).DUR_OLD_MI = value;
  }


  /**  */
  public static void setDUR_OLD_MI  ( RallyApplication __app, Object value )
  {
    ( ( CALENDARIO_MAIN_CONSOLIDAR_FECHAS_ADL ) __app.getADL ( CALENDARIO_MAIN_CONSOLIDAR_FECHAS_ADL.class ) ).DUR_OLD_MI = ( ( Double ) value ).doubleValue ( );
  }


  /**  */
  public static double getDHM_NEW_HH  ( RallyApplication __app )
  {
    return ( ( CALENDARIO_MAIN_CONSOLIDAR_FECHAS_ADL ) __app.getADL ( CALENDARIO_MAIN_CONSOLIDAR_FECHAS_ADL.class ) ).DHM_NEW_HH;
  }


  /**  */
  public static Double getDHM_NEW_HHDouble ( RallyApplication __app )
  {
    return new Double ( ( ( CALENDARIO_MAIN_CONSOLIDAR_FECHAS_ADL ) __app.getADL ( CALENDARIO_MAIN_CONSOLIDAR_FECHAS_ADL.class ) ).DHM_NEW_HH );
  }


  /**  */
  public static void setDHM_NEW_HH  ( RallyApplication __app, double value )
  {
    ( ( CALENDARIO_MAIN_CONSOLIDAR_FECHAS_ADL ) __app.getADL ( CALENDARIO_MAIN_CONSOLIDAR_FECHAS_ADL.class ) ).DHM_NEW_HH = value;
  }


  /**  */
  public static void setDHM_NEW_HH  ( RallyApplication __app, Object value )
  {
    ( ( CALENDARIO_MAIN_CONSOLIDAR_FECHAS_ADL ) __app.getADL ( CALENDARIO_MAIN_CONSOLIDAR_FECHAS_ADL.class ) ).DHM_NEW_HH = ( ( Double ) value ).doubleValue ( );
  }


  /**  */
  public static double getDHM_NEW_MI  ( RallyApplication __app )
  {
    return ( ( CALENDARIO_MAIN_CONSOLIDAR_FECHAS_ADL ) __app.getADL ( CALENDARIO_MAIN_CONSOLIDAR_FECHAS_ADL.class ) ).DHM_NEW_MI;
  }


  /**  */
  public static Double getDHM_NEW_MIDouble ( RallyApplication __app )
  {
    return new Double ( ( ( CALENDARIO_MAIN_CONSOLIDAR_FECHAS_ADL ) __app.getADL ( CALENDARIO_MAIN_CONSOLIDAR_FECHAS_ADL.class ) ).DHM_NEW_MI );
  }


  /**  */
  public static void setDHM_NEW_MI  ( RallyApplication __app, double value )
  {
    ( ( CALENDARIO_MAIN_CONSOLIDAR_FECHAS_ADL ) __app.getADL ( CALENDARIO_MAIN_CONSOLIDAR_FECHAS_ADL.class ) ).DHM_NEW_MI = value;
  }


  /**  */
  public static void setDHM_NEW_MI  ( RallyApplication __app, Object value )
  {
    ( ( CALENDARIO_MAIN_CONSOLIDAR_FECHAS_ADL ) __app.getADL ( CALENDARIO_MAIN_CONSOLIDAR_FECHAS_ADL.class ) ).DHM_NEW_MI = ( ( Double ) value ).doubleValue ( );
  }


  /**  */
  public static double getDUR_NEW_HH  ( RallyApplication __app )
  {
    return ( ( CALENDARIO_MAIN_CONSOLIDAR_FECHAS_ADL ) __app.getADL ( CALENDARIO_MAIN_CONSOLIDAR_FECHAS_ADL.class ) ).DUR_NEW_HH;
  }


  /**  */
  public static Double getDUR_NEW_HHDouble ( RallyApplication __app )
  {
    return new Double ( ( ( CALENDARIO_MAIN_CONSOLIDAR_FECHAS_ADL ) __app.getADL ( CALENDARIO_MAIN_CONSOLIDAR_FECHAS_ADL.class ) ).DUR_NEW_HH );
  }


  /**  */
  public static void setDUR_NEW_HH  ( RallyApplication __app, double value )
  {
    ( ( CALENDARIO_MAIN_CONSOLIDAR_FECHAS_ADL ) __app.getADL ( CALENDARIO_MAIN_CONSOLIDAR_FECHAS_ADL.class ) ).DUR_NEW_HH = value;
  }


  /**  */
  public static void setDUR_NEW_HH  ( RallyApplication __app, Object value )
  {
    ( ( CALENDARIO_MAIN_CONSOLIDAR_FECHAS_ADL ) __app.getADL ( CALENDARIO_MAIN_CONSOLIDAR_FECHAS_ADL.class ) ).DUR_NEW_HH = ( ( Double ) value ).doubleValue ( );
  }


  /**  */
  public static double getDUR_NEW_MI  ( RallyApplication __app )
  {
    return ( ( CALENDARIO_MAIN_CONSOLIDAR_FECHAS_ADL ) __app.getADL ( CALENDARIO_MAIN_CONSOLIDAR_FECHAS_ADL.class ) ).DUR_NEW_MI;
  }


  /**  */
  public static Double getDUR_NEW_MIDouble ( RallyApplication __app )
  {
    return new Double ( ( ( CALENDARIO_MAIN_CONSOLIDAR_FECHAS_ADL ) __app.getADL ( CALENDARIO_MAIN_CONSOLIDAR_FECHAS_ADL.class ) ).DUR_NEW_MI );
  }


  /**  */
  public static void setDUR_NEW_MI  ( RallyApplication __app, double value )
  {
    ( ( CALENDARIO_MAIN_CONSOLIDAR_FECHAS_ADL ) __app.getADL ( CALENDARIO_MAIN_CONSOLIDAR_FECHAS_ADL.class ) ).DUR_NEW_MI = value;
  }


  /**  */
  public static void setDUR_NEW_MI  ( RallyApplication __app, Object value )
  {
    ( ( CALENDARIO_MAIN_CONSOLIDAR_FECHAS_ADL ) __app.getADL ( CALENDARIO_MAIN_CONSOLIDAR_FECHAS_ADL.class ) ).DUR_NEW_MI = ( ( Double ) value ).doubleValue ( );
  }


  /**  */
  public static double getTOTAL_MI  ( RallyApplication __app )
  {
    return ( ( CALENDARIO_MAIN_CONSOLIDAR_FECHAS_ADL ) __app.getADL ( CALENDARIO_MAIN_CONSOLIDAR_FECHAS_ADL.class ) ).TOTAL_MI;
  }


  /**  */
  public static Double getTOTAL_MIDouble ( RallyApplication __app )
  {
    return new Double ( ( ( CALENDARIO_MAIN_CONSOLIDAR_FECHAS_ADL ) __app.getADL ( CALENDARIO_MAIN_CONSOLIDAR_FECHAS_ADL.class ) ).TOTAL_MI );
  }


  /**  */
  public static void setTOTAL_MI  ( RallyApplication __app, double value )
  {
    ( ( CALENDARIO_MAIN_CONSOLIDAR_FECHAS_ADL ) __app.getADL ( CALENDARIO_MAIN_CONSOLIDAR_FECHAS_ADL.class ) ).TOTAL_MI = value;
  }


  /**  */
  public static void setTOTAL_MI  ( RallyApplication __app, Object value )
  {
    ( ( CALENDARIO_MAIN_CONSOLIDAR_FECHAS_ADL ) __app.getADL ( CALENDARIO_MAIN_CONSOLIDAR_FECHAS_ADL.class ) ).TOTAL_MI = ( ( Double ) value ).doubleValue ( );
  }


  /**  */
  public static double getTOTAL_HH  ( RallyApplication __app )
  {
    return ( ( CALENDARIO_MAIN_CONSOLIDAR_FECHAS_ADL ) __app.getADL ( CALENDARIO_MAIN_CONSOLIDAR_FECHAS_ADL.class ) ).TOTAL_HH;
  }


  /**  */
  public static Double getTOTAL_HHDouble ( RallyApplication __app )
  {
    return new Double ( ( ( CALENDARIO_MAIN_CONSOLIDAR_FECHAS_ADL ) __app.getADL ( CALENDARIO_MAIN_CONSOLIDAR_FECHAS_ADL.class ) ).TOTAL_HH );
  }


  /**  */
  public static void setTOTAL_HH  ( RallyApplication __app, double value )
  {
    ( ( CALENDARIO_MAIN_CONSOLIDAR_FECHAS_ADL ) __app.getADL ( CALENDARIO_MAIN_CONSOLIDAR_FECHAS_ADL.class ) ).TOTAL_HH = value;
  }


  /**  */
  public static void setTOTAL_HH  ( RallyApplication __app, Object value )
  {
    ( ( CALENDARIO_MAIN_CONSOLIDAR_FECHAS_ADL ) __app.getADL ( CALENDARIO_MAIN_CONSOLIDAR_FECHAS_ADL.class ) ).TOTAL_HH = ( ( Double ) value ).doubleValue ( );
  }


  /**  */
  public static double getRESTO_HH  ( RallyApplication __app )
  {
    return ( ( CALENDARIO_MAIN_CONSOLIDAR_FECHAS_ADL ) __app.getADL ( CALENDARIO_MAIN_CONSOLIDAR_FECHAS_ADL.class ) ).RESTO_HH;
  }


  /**  */
  public static Double getRESTO_HHDouble ( RallyApplication __app )
  {
    return new Double ( ( ( CALENDARIO_MAIN_CONSOLIDAR_FECHAS_ADL ) __app.getADL ( CALENDARIO_MAIN_CONSOLIDAR_FECHAS_ADL.class ) ).RESTO_HH );
  }


  /**  */
  public static void setRESTO_HH  ( RallyApplication __app, double value )
  {
    ( ( CALENDARIO_MAIN_CONSOLIDAR_FECHAS_ADL ) __app.getADL ( CALENDARIO_MAIN_CONSOLIDAR_FECHAS_ADL.class ) ).RESTO_HH = value;
  }


  /**  */
  public static void setRESTO_HH  ( RallyApplication __app, Object value )
  {
    ( ( CALENDARIO_MAIN_CONSOLIDAR_FECHAS_ADL ) __app.getADL ( CALENDARIO_MAIN_CONSOLIDAR_FECHAS_ADL.class ) ).RESTO_HH = ( ( Double ) value ).doubleValue ( );
  }


  /**  */
  public static double getJEFE_SERVICIO  ( RallyApplication __app )
  {
    return ( ( CALENDARIO_MAIN_CONSOLIDAR_FECHAS_ADL ) __app.getADL ( CALENDARIO_MAIN_CONSOLIDAR_FECHAS_ADL.class ) ).JEFE_SERVICIO;
  }


  /**  */
  public static Double getJEFE_SERVICIODouble ( RallyApplication __app )
  {
    return new Double ( ( ( CALENDARIO_MAIN_CONSOLIDAR_FECHAS_ADL ) __app.getADL ( CALENDARIO_MAIN_CONSOLIDAR_FECHAS_ADL.class ) ).JEFE_SERVICIO );
  }


  /**  */
  public static void setJEFE_SERVICIO  ( RallyApplication __app, double value )
  {
    ( ( CALENDARIO_MAIN_CONSOLIDAR_FECHAS_ADL ) __app.getADL ( CALENDARIO_MAIN_CONSOLIDAR_FECHAS_ADL.class ) ).JEFE_SERVICIO = value;
  }


  /**  */
  public static void setJEFE_SERVICIO  ( RallyApplication __app, Object value )
  {
    ( ( CALENDARIO_MAIN_CONSOLIDAR_FECHAS_ADL ) __app.getADL ( CALENDARIO_MAIN_CONSOLIDAR_FECHAS_ADL.class ) ).JEFE_SERVICIO = ( ( Double ) value ).doubleValue ( );
  }


  /**  */
  public static double getCOUNT_AUX  ( RallyApplication __app )
  {
    return ( ( CALENDARIO_MAIN_CONSOLIDAR_FECHAS_ADL ) __app.getADL ( CALENDARIO_MAIN_CONSOLIDAR_FECHAS_ADL.class ) ).COUNT_AUX;
  }


  /**  */
  public static Double getCOUNT_AUXDouble ( RallyApplication __app )
  {
    return new Double ( ( ( CALENDARIO_MAIN_CONSOLIDAR_FECHAS_ADL ) __app.getADL ( CALENDARIO_MAIN_CONSOLIDAR_FECHAS_ADL.class ) ).COUNT_AUX );
  }


  /**  */
  public static void setCOUNT_AUX  ( RallyApplication __app, double value )
  {
    ( ( CALENDARIO_MAIN_CONSOLIDAR_FECHAS_ADL ) __app.getADL ( CALENDARIO_MAIN_CONSOLIDAR_FECHAS_ADL.class ) ).COUNT_AUX = value;
  }


  /**  */
  public static void setCOUNT_AUX  ( RallyApplication __app, Object value )
  {
    ( ( CALENDARIO_MAIN_CONSOLIDAR_FECHAS_ADL ) __app.getADL ( CALENDARIO_MAIN_CONSOLIDAR_FECHAS_ADL.class ) ).COUNT_AUX = ( ( Double ) value ).doubleValue ( );
  }



  // -------------------------------------------------------------------
  // ----------   Methods   --------------------------------------------

  /**
   * 
   * @param __app
   * @return
   */
  public static CALENDARIO_MAIN_CONSOLIDAR_FECHAS_ADL get ( RallyApplication __app )
  {
    CALENDARIO_MAIN_CONSOLIDAR_FECHAS_ADL adl = new CALENDARIO_MAIN_CONSOLIDAR_FECHAS_ADL ( );
    __app.register ( adl, "CALENDARIO_MAIN_CONSOLIDAR_FECHAS_ADL" );
    __app.setADL ( CALENDARIO_MAIN_CONSOLIDAR_FECHAS_ADL.class, adl ); 
    adl.setApplication ( __app );
    return adl;
  }


  /**
   *
   * @param __app
   * @param ps
   *
   * @return
   */
  public static void exec ( RallyApplication __app, ParameterSet ps )
  {
    CALENDARIO_MAIN_CONSOLIDAR_FECHAS_ADL.get ( __app ).process ( ps );
  }


  /**
   *
   * @param __app
   *
   * @return
   */
  public static void exec ( RallyApplication __app )
  {
    ParameterSet ps = null;
    CALENDARIO_MAIN_CONSOLIDAR_FECHAS_ADL.exec ( __app, ps );
  }


  /**
   * Overrides the ancestor's method
   * 
   * @param __app
   */
  @Override
public void setApplication ( RallyApplication __app )
  {
    this.app = ( SAIC_DMQ_ORA_Application ) __app;
    if ( this.app != null )
    {
      this.dm = ( RallyDataManager ) this.app.getDataManager ( );
    }
  }


  /**
   * Overrides the ancestor's method
   * 
   * @param parms
   */
  @Override
public void execute ( ParameterSet parms )
  {
    this.process ( parms );
  }




  /**
   *
   */
  protected void doReturn ( )
  {
    this.unregister ( );
  }


  /**
   *
   */
  public void unregister ( )
  {
    this.app.unregister ( this );
    IRegisteredObject rObj = this.app.get ( "CALENDARIO_MAIN_CONSOLIDAR_FECHAS_ADL" );
    if ( rObj != null && rObj instanceof CALENDARIO_MAIN_CONSOLIDAR_FECHAS_ADL )
    {
      this.app.setADL ( CALENDARIO_MAIN_CONSOLIDAR_FECHAS_ADL.class, ( CALENDARIO_MAIN_CONSOLIDAR_FECHAS_ADL ) rObj );
    }
  }


  /**
   * Overrides the ancestor's method
   * 
   * @param ps
   */
  @Override
protected void process ( ParameterSet ps )
  {
    Debug.println ( Debug.TRACE, "CALENDARIO_MAIN_CONSOLIDAR_FECHAS_ADL Step " + this.currentStep );
    super.process ( ps );
    switch ( this.currentStep ) 
    {
      case 0:  { this.currentStep ++; this.step0 ( this.keyParms ); break; }
      case 1:  { this.currentStep ++; this.step1 ( this.keyParms ); break; }
      case 2:  { this.currentStep ++; this.step2 ( this.keyParms ); break; }
      case 3:  { this.currentStep ++; this.step3 ( this.keyParms ); break; }
      case 4:  { this.currentStep ++; this.step4 ( this.keyParms ); break; }
      case 5:  { this.currentStep ++; this.step5 ( this.keyParms ); break; }
      case 6:  { this.currentStep ++; this.step6 ( this.keyParms ); break; }
      case 7:  { this.currentStep ++; this.step7 ( this.keyParms ); break; }
      case 8:  { this.currentStep ++; this.step8 ( this.keyParms ); break; }
      case 9:  { this.currentStep ++; this.step9 ( this.keyParms ); break; }
      case 10:  { this.currentStep ++; this.step10 ( this.keyParms ); break; }
      case 11:  { this.currentStep ++; this.step11 ( this.keyParms ); break; }
      case 12:  { this.currentStep ++; this.step12 ( this.keyParms ); break; }
      case 13:  { this.currentStep ++; this.step13 ( this.keyParms ); break; }
      default: 
      { 
        this.currentStep = 0;
        Debug.println ( Debug.TRACE, "CALENDARIO_MAIN_CONSOLIDAR_FECHAS_ADL ended" );
        this.unregister ( );
        break;
      }
    }
    if ( this.currentStep > 0 ) this.app.goOn ( );
  }



  /**
   *
   */
  protected void step0 ( ParameterSet ps )
  {

    this.app.form ( "CALENDARIO_MAIN_FR" ).setItem ( "FLG_CONSOLIDAR", "T"  );
    this.app.callCommand ( RallyAppCommandFactory.FNEXT );
    return;

  }


  /**
   *
   */
  protected void step1 ( ParameterSet ps )
  {
    if ( ! Compare.equals ( this.app.form ( "CALENDARIO_MAIN_FR" ).getDoubleItem ( "NUMERO_REGISTRO" ), 1 ) ) 
    {
      this._condition0 = true;
    }
    else
    {
      this._condition0 = false;
    }
    if ( this._condition0 )
    {
      this.app.callCommand ( RallyAppCommandFactory.RHOME );
      return;
    }

  }


  /**
   *
   */
  protected void step2 ( ParameterSet ps )
  {
    COUNT_AUX = this.app.form ( "CALENDARIO_MAIN_FR" ).getDoubleItem ( "CONTADOR" );
    this.process ( ps );

  }


  /**
   *
   */
  protected void step3 ( ParameterSet ps )
  {

    if ( ! Compare.equals ( COUNT_AUX, 0 )  )
    {
      this._condition1 = true;
    }
    else
    {
      this._condition1 = false;
    }
    if ( this._condition1 )
    {
      if ( ( Compare.equals ( this.app.form ( "CALENDARIO_MAIN_FR" ).getStringItem ( "COD_SERVICIO" ), "GENN" ) ) || ( Compare.equals ( this.app.form ( "CALENDARIO_MAIN_FR" ).getStringItem ( "COD_SERVICIO" ), "GENS" ) ) || ( Compare.equals ( this.app.form ( "CALENDARIO_MAIN_FR" ).getStringItem ( "COD_SERVICIO" ), "DISP" ) ) ) 
      {
        this._condition2 = true;
      }
      else
      {
        this._condition2 = false;
      }
      if ( this._condition2 )
      {
        COD_SERVICIO = this.app.form ( "CALENDARIO_MAIN_FR" ).getStringItem ( "COD_SERVICIO" );
        COD_RAZON = this.app.form ( "CALENDARIO_MAIN_FR" ).getStringItem ( "COD_RAZON" );
        JEFE_SERVICIO = this.app.form ( "CALENDARIO_MAIN_FR" ).getDoubleItem ( "SEGURO_SOCIAL_JEFE_SERV" );
        DHM_OLD = this.app.form ( "CALENDARIO_MAIN_FR" ).getDateItem ( "FCH_ACTIVIDAD_HORA_MIN_CONTAC0" );
        DUR_OLD = this.app.form ( "CALENDARIO_MAIN_FR" ).getDateItem ( "DURACION_HORA_MIN_CONTACTO" );
        DHM_OLD_CHAR = StringService.toStringValue  ( DHM_OLD ,"ddMMyyyyHHmm" ,StringService.Language.SPANISH );
        DUR_OLD_CHAR = StringService.toStringValue  ( DUR_OLD ,"HHmm" ,StringService.Language.SPANISH );
        DHM_OLD_FCH_CHAR = RallyStringService.subString ( DHM_OLD_CHAR, 0, 8 );
        DHM_OLD_HH = FormattingFactory.parseStringToDouble ( RallyStringService.subString ( DHM_OLD_CHAR, 8, 2 ) );
        DHM_OLD_MI = FormattingFactory.parseStringToDouble ( RallyStringService.subString ( DHM_OLD_CHAR, 10, 2 ) );
        DUR_OLD_HH = FormattingFactory.parseStringToDouble ( RallyStringService.subString ( DUR_OLD_CHAR, 0, 2 ) );
        DUR_OLD_MI = FormattingFactory.parseStringToDouble ( RallyStringService.subString ( DUR_OLD_CHAR, 2, 2 ) );
        TOTAL_MI = MathService.plus ( DHM_OLD_MI, DUR_OLD_MI  );
        if ( Compare.ge ( TOTAL_MI, 60 ) ) 
        {
          TOTAL_MI = MathService.minus ( TOTAL_MI, 60  );
          RESTO_HH = 1;
        }
        TOTAL_HH = MathService.plus ( MathService.plus ( DHM_OLD_HH, DUR_OLD_HH  ), RESTO_HH  );
        if ( Compare.equals ( TOTAL_MI, 0 ) ) 
        {
          TOTAL_MI_CHAR = "00";
        }
        else
        {
          TOTAL_MI_CHAR = StringService.toStringValue  ( TOTAL_MI );
        }
        if ( Compare.le ( TOTAL_HH, 9 ) ) 
        {
          TOTAL_HH_CHAR = "0" + StringService.toStringValue  ( TOTAL_HH );
        }
        else
        {
          TOTAL_HH_CHAR = StringService.toStringValue  ( TOTAL_HH );
        }
        DHM_OLD_MAIS_DUR_OLD = RallySpanishDatesParser.parseDateString ( DHM_OLD_FCH_CHAR + TOTAL_HH_CHAR + TOTAL_MI_CHAR, "DDMMYYYYHH24MI" );
        if ( ! Compare.equals ( this.app.form ( "CALENDARIO_MAIN_FR" ).getDoubleItem ( "NUMERO_REGISTRO" ), this.app.form ( "CALENDARIO_MAIN_FR" ).getDoubleItem ( "CONTADOR" )) ) 
        {
          this._condition3 = true;
        }
        else
        {
          this._condition3 = false;
        }
        if ( this._condition3 )
        {
          this.app.callCommand ( RallyAppCommandFactory.RNEXT );
          return;
        }
      }
    }

  }


  /**
   *
   */
  protected void step4 ( ParameterSet ps )
  {
    if ( this._condition1 )    //    while ( ! Compare.equals ( COUNT_AUX, 0 )  )
    {
      if ( this._condition2 )    //      if ( ( Compare.equals ( this.app.form ( "CALENDARIO_MAIN_FR" ).getStringItem ( "COD_SERVICIO" ), "GENN" ) ) || ( Compare.equals ( this.app.form ( "CALENDARIO_MAIN_FR" ).getStringItem ( "COD_SERVICIO" ), "GENS" ) ) || ( Compare.equals ( this.app.form ( "CALENDARIO_MAIN_FR" ).getStringItem ( "COD_SERVICIO" ), "DISP" ) ) ) 
      {
        if ( this._condition3 )    //        if ( ! Compare.equals ( this.app.form ( "CALENDARIO_MAIN_FR" ).getDoubleItem ( "NUMERO_REGISTRO" ), this.app.form ( "CALENDARIO_MAIN_FR" ).getDoubleItem ( "CONTADOR" )) ) 
        {
          if ( ( Compare.equals ( this.app.form ( "CALENDARIO_MAIN_FR" ).getStringItem ( "COD_SERVICIO" ), COD_SERVICIO ) ) && ( Compare.equals ( this.app.form ( "CALENDARIO_MAIN_FR" ).getStringItem ( "COD_RAZON" ), COD_RAZON ) )  && ( Compare.equals ( JEFE_SERVICIO, this.app.form ( "CALENDARIO_MAIN_FR" ).getDoubleItem ( "SEGURO_SOCIAL_JEFE_SERV" )) )  && ( Compare.equals ( RallyStringService.subString ( StringService.toStringValue  ( this.app.form ( "CALENDARIO_MAIN_FR" ).getDateItem ( "FCH_ACTIVIDAD_HORA_MIN_CONTAC0" )), 0, 13 ), RallyStringService.subString ( StringService.toStringValue  ( DHM_OLD_MAIS_DUR_OLD ), 0, 13 ) ) )  ) 
          {
            this._condition4 = true;
          }
          else
          {
            this._condition4 = false;
          }
          if ( this._condition4 )
          {
            this.app.form ( "CALENDARIO_MAIN_FR" ).setItem ( "FCH_ACTIVIDAD_HORA_MIN_CONTAC0", DHM_OLD  );
            DUR_NEW = this.app.form ( "CALENDARIO_MAIN_FR" ).getDateItem ( "DURACION_HORA_MIN_CONTACTO" );
            DUR_NEW_CHAR = StringService.toStringValue  ( DUR_NEW ,"HHmm" ,StringService.Language.SPANISH );
            DUR_NEW_HH = FormattingFactory.parseStringToDouble ( RallyStringService.subString ( DUR_NEW_CHAR, 0, 2 ) );
            DUR_NEW_MI = FormattingFactory.parseStringToDouble ( RallyStringService.subString ( DUR_NEW_CHAR, 2, 2 ) );
            RESTO_HH = 0;
            TOTAL_MI = 0;
            TOTAL_MI = MathService.plus ( DUR_OLD_MI, DUR_NEW_MI  );
            if ( Compare.ge ( TOTAL_MI, 60 ) ) 
            {
              TOTAL_MI = MathService.minus ( TOTAL_MI, 60  );
              RESTO_HH = 1;
            }
            TOTAL_HH = MathService.plus ( MathService.plus ( DUR_OLD_HH, DUR_NEW_HH  ), RESTO_HH  );
            if ( Compare.equals ( TOTAL_MI, 0 ) ) 
            {
              TOTAL_MI_CHAR = "00";
            }
            else
            {
              TOTAL_MI_CHAR = StringService.toStringValue  ( TOTAL_MI );
            }
            if ( Compare.le ( TOTAL_HH, 9 ) ) 
            {
              TOTAL_HH_CHAR = "0" + StringService.toStringValue  ( TOTAL_HH );
            }
            else
            {
              TOTAL_HH_CHAR = StringService.toStringValue  ( TOTAL_HH );
            }
            this.app.form ( "CALENDARIO_MAIN_FR" ).setItem ( "DURACION_HORA_MIN_CONTACTO", RallySpanishDatesParser.parseDateString ( TOTAL_HH_CHAR + TOTAL_MI_CHAR, "HH24MI" )  );
            this.app.callCommand ( RallyAppCommandFactory.RPREV );
            return;
          }
        }
      }
    }

  }


  /**
   *
   */
  protected void step5 ( ParameterSet ps )
  {
    if ( this._condition1 )    //    while ( ! Compare.equals ( COUNT_AUX, 0 )  )
    {
      if ( this._condition2 )    //      if ( ( Compare.equals ( this.app.form ( "CALENDARIO_MAIN_FR" ).getStringItem ( "COD_SERVICIO" ), "GENN" ) ) || ( Compare.equals ( this.app.form ( "CALENDARIO_MAIN_FR" ).getStringItem ( "COD_SERVICIO" ), "GENS" ) ) || ( Compare.equals ( this.app.form ( "CALENDARIO_MAIN_FR" ).getStringItem ( "COD_SERVICIO" ), "DISP" ) ) ) 
      {
        if ( this._condition3 )    //        if ( ! Compare.equals ( this.app.form ( "CALENDARIO_MAIN_FR" ).getDoubleItem ( "NUMERO_REGISTRO" ), this.app.form ( "CALENDARIO_MAIN_FR" ).getDoubleItem ( "CONTADOR" )) ) 
        {
          if ( this._condition4 )    //          if ( ( Compare.equals ( this.app.form ( "CALENDARIO_MAIN_FR" ).getStringItem ( "COD_SERVICIO" ), COD_SERVICIO ) ) && ( Compare.equals ( this.app.form ( "CALENDARIO_MAIN_FR" ).getStringItem ( "COD_RAZON" ), COD_RAZON ) )  && ( Compare.equals ( JEFE_SERVICIO, this.app.form ( "CALENDARIO_MAIN_FR" ).getDoubleItem ( "SEGURO_SOCIAL_JEFE_SERV" )) )  && ( Compare.equals ( RallyStringService.subString ( StringService.toStringValue  ( this.app.form ( "CALENDARIO_MAIN_FR" ).getDateItem ( "FCH_ACTIVIDAD_HORA_MIN_CONTAC0" )), 0, 13 ), RallyStringService.subString ( StringService.toStringValue  ( DHM_OLD_MAIS_DUR_OLD ), 0, 13 ) ) )  ) 
          {
            this.app.form ( "CALENDARIO_MAIN_FR" ).setItem ( "MARKED_TO_DELETE", "T"  );
            this.app.callCommand ( RallyAppCommandFactory.RNEXT );
            return;
          }
        }
      }
    }

  }


  /**
   *
   */
  protected void step6 ( ParameterSet ps )
  {
    if ( this._condition1 )    //    while ( ! Compare.equals ( COUNT_AUX, 0 )  )
    {
      if ( this._condition2 )    //      if ( ( Compare.equals ( this.app.form ( "CALENDARIO_MAIN_FR" ).getStringItem ( "COD_SERVICIO" ), "GENN" ) ) || ( Compare.equals ( this.app.form ( "CALENDARIO_MAIN_FR" ).getStringItem ( "COD_SERVICIO" ), "GENS" ) ) || ( Compare.equals ( this.app.form ( "CALENDARIO_MAIN_FR" ).getStringItem ( "COD_SERVICIO" ), "DISP" ) ) ) 
      {
        if ( this._condition3 )    //        if ( ! Compare.equals ( this.app.form ( "CALENDARIO_MAIN_FR" ).getDoubleItem ( "NUMERO_REGISTRO" ), this.app.form ( "CALENDARIO_MAIN_FR" ).getDoubleItem ( "CONTADOR" )) ) 
        {
          if ( this._condition4 )    //          if ( ( Compare.equals ( this.app.form ( "CALENDARIO_MAIN_FR" ).getStringItem ( "COD_SERVICIO" ), COD_SERVICIO ) ) && ( Compare.equals ( this.app.form ( "CALENDARIO_MAIN_FR" ).getStringItem ( "COD_RAZON" ), COD_RAZON ) )  && ( Compare.equals ( JEFE_SERVICIO, this.app.form ( "CALENDARIO_MAIN_FR" ).getDoubleItem ( "SEGURO_SOCIAL_JEFE_SERV" )) )  && ( Compare.equals ( RallyStringService.subString ( StringService.toStringValue  ( this.app.form ( "CALENDARIO_MAIN_FR" ).getDateItem ( "FCH_ACTIVIDAD_HORA_MIN_CONTAC0" )), 0, 13 ), RallyStringService.subString ( StringService.toStringValue  ( DHM_OLD_MAIS_DUR_OLD ), 0, 13 ) ) )  ) 
          {
            COUNT_AUX = MathService.minus ( COUNT_AUX, 1  );
          }
          else
          {
            COUNT_AUX = MathService.minus ( COUNT_AUX, 1  );
          }
        }
        else
        {
          COUNT_AUX = MathService.minus ( COUNT_AUX, 1  );
          if ( ! Compare.equals ( COUNT_AUX, 0 ) ) 
          {
            this._condition5 = true;
          }
          else
          {
            this._condition5 = false;
          }
          if ( this._condition5 )
          {
            this.app.callCommand ( RallyAppCommandFactory.RNEXT );
            return;
          }
        }
      }
    }

  }


  /**
   *
   */
  protected void step7 ( ParameterSet ps )
  {
    if ( this._condition1 )    //    while ( ! Compare.equals ( COUNT_AUX, 0 )  )
    {
      if ( this._condition2 )    //      if ( ( Compare.equals ( this.app.form ( "CALENDARIO_MAIN_FR" ).getStringItem ( "COD_SERVICIO" ), "GENN" ) ) || ( Compare.equals ( this.app.form ( "CALENDARIO_MAIN_FR" ).getStringItem ( "COD_SERVICIO" ), "GENS" ) ) || ( Compare.equals ( this.app.form ( "CALENDARIO_MAIN_FR" ).getStringItem ( "COD_SERVICIO" ), "DISP" ) ) ) 
      {
        if ( this._condition3 )    //        if ( ! Compare.equals ( this.app.form ( "CALENDARIO_MAIN_FR" ).getDoubleItem ( "NUMERO_REGISTRO" ), this.app.form ( "CALENDARIO_MAIN_FR" ).getDoubleItem ( "CONTADOR" )) ) 
        {
        }
        else
        {
          if ( this._condition5 )    //          if ( ! Compare.equals ( COUNT_AUX, 0 ) ) 
          {
          }
        }
      }
      else
      {
        COUNT_AUX = MathService.minus ( COUNT_AUX, 1  );
        if ( ! Compare.equals ( COUNT_AUX, 0 ) ) 
        {
          this._condition6 = true;
        }
        else
        {
          this._condition6 = false;
        }
        if ( this._condition6 )
        {
          this.app.callCommand ( RallyAppCommandFactory.RNEXT );
          return;
        }
      }
    }

  }


  /**
   *
   */
  protected void step8 ( ParameterSet ps )
  {
    if ( this._condition1 )    //    while ( ! Compare.equals ( COUNT_AUX, 0 )  )
    {
      if ( this._condition2 )    //      if ( ( Compare.equals ( this.app.form ( "CALENDARIO_MAIN_FR" ).getStringItem ( "COD_SERVICIO" ), "GENN" ) ) || ( Compare.equals ( this.app.form ( "CALENDARIO_MAIN_FR" ).getStringItem ( "COD_SERVICIO" ), "GENS" ) ) || ( Compare.equals ( this.app.form ( "CALENDARIO_MAIN_FR" ).getStringItem ( "COD_SERVICIO" ), "DISP" ) ) ) 
      {
      }
      else
      {
        if ( this._condition6 )    //        if ( ! Compare.equals ( COUNT_AUX, 0 ) ) 
        {
        }
      }
      this.currentStep = 3;
      return;
    }

  }


  /**
   *
   */
  protected void step9 ( ParameterSet ps )
  {
    if ( ! Compare.equals ( this.app.form ( "CALENDARIO_MAIN_FR" ).getDoubleItem ( "CONTADOR" ), 1 ) ) 
    {
      this._condition7 = true;
    }
    else
    {
      this._condition7 = false;
    }
    if ( this._condition7 )
    {
      this.app.callCommand ( RallyAppCommandFactory.RHOME );
      return;
    }

  }


  /**
   *
   */
  protected void step10 ( ParameterSet ps )
  {
    COUNT_AUX = this.app.form ( "CALENDARIO_MAIN_FR" ).getDoubleItem ( "CONTADOR" );
    this.process ( ps );

  }


  /**
   *
   */
  protected void step11 ( ParameterSet ps )
  {

    if ( ! Compare.equals ( COUNT_AUX, 0 )  )
    {
      this._condition8 = true;
    }
    else
    {
      this._condition8 = false;
    }
    if ( this._condition8 )
    {
      if ( Compare.equals ( this.app.form ( "CALENDARIO_MAIN_FR" ).getStringItem ( "MARKED_TO_DELETE" ), "T" ) ) 
      {
        this._condition9 = true;
      }
      else
      {
        this._condition9 = false;
      }
      if ( this._condition9 )
      {
        this.app.callCommand ( RallyAppCommandFactory.DELREC );
        return;
      }
    }

  }


  /**
   *
   */
  protected void step12 ( ParameterSet ps )
  {
    if ( this._condition8 )    //    while ( ! Compare.equals ( COUNT_AUX, 0 )  )
    {
      if ( this._condition9 )    //      if ( Compare.equals ( this.app.form ( "CALENDARIO_MAIN_FR" ).getStringItem ( "MARKED_TO_DELETE" ), "T" ) ) 
      {
        COUNT_AUX = MathService.minus ( COUNT_AUX, 1  );
      }
      else
      {
        COUNT_AUX = MathService.minus ( COUNT_AUX, 1  );
        if ( ! Compare.equals ( COUNT_AUX, 0 ) ) 
        {
          this._condition10 = true;
        }
        else
        {
          this._condition10 = false;
        }
        if ( this._condition10 )
        {
          this.app.callCommand ( RallyAppCommandFactory.RNEXT );
          return;
        }
      }
    }

  }


  /**
   *
   */
  protected void step13 ( ParameterSet ps )
  {
    if ( this._condition8 )    //    while ( ! Compare.equals ( COUNT_AUX, 0 )  )
    {
      if ( this._condition9 )    //      if ( Compare.equals ( this.app.form ( "CALENDARIO_MAIN_FR" ).getStringItem ( "MARKED_TO_DELETE" ), "T" ) ) 
      {
      }
      else
      {
        if ( this._condition10 )    //        if ( ! Compare.equals ( COUNT_AUX, 0 ) ) 
        {
        }
      }
      this.currentStep = 11;
      return;
    }

  }
}



/* ---------------------------------------------------------------------


     
PROCEDURE CALENDARIO_MAIN_CONSOLIDAR_FECHAS_ADL;

VAR
        DHM_OLD                 :       DATE;
        DUR_OLD                 :       DATE;
        DHM_OLD_CHAR            :       CHAR(12);
        DUR_OLD_CHAR            :       CHAR(4);
        DHM_OLD_FCH_CHAR        :       CHAR(8);
        DHM_OLD_MAIS_DUR_OLD    :       DATE;

        DHM_NEW                 :       DATE;
        DUR_NEW                 :       DATE;
        DHM_NEW_CHAR            :       CHAR(12);
        DUR_NEW_CHAR            :       CHAR(4);
        DHM_NEW_FCH_CHAR        :       CHAR(8);
        DHM_NEW_MAIS_DUR_NEW    :       DATE;

        DHM_OLD_HH              :       NUMBER;
        DHM_OLD_MI              :       NUMBER;
        DUR_OLD_HH              :       NUMBER;
        DUR_OLD_MI              :       NUMBER;

        DHM_NEW_HH              :       NUMBER;
        DHM_NEW_MI              :       NUMBER;
        DUR_NEW_HH              :       NUMBER;
        DUR_NEW_MI              :       NUMBER;

        TOTAL_MI                :       NUMBER;
        TOTAL_HH                :       NUMBER;
        RESTO_HH                :       NUMBER;

        TOTAL_HH_CHAR           :       CHAR(2);
        TOTAL_MI_CHAR           :       CHAR(2);

        COD_SERVICIO            :       CHAR(5);
        COD_RAZON               :       CHAR(4);
        JEFE_SERVICIO           :       NUMBER(9,0);
        COUNT_AUX                       :       NUMBER(9,0);

BEGIN
SET_TRACE();
CALENDARIO_MAIN_FR.FLG_CONSOLIDAR := 'T';
CALL_CMD('NEXT FIELD');

DEBUG_LOG ('CALENDARIO_MAIN_FR.NUMERO_REGISTRO = '|| TO_CHAR(CALENDARIO_MAIN_FR.
NUMERO_REGISTRO));

        IF CALENDARIO_MAIN_FR.NUMERO_REGISTRO <> 1
        THEN CALL_CMD('FIRST RECORD');

DEBUG_LOG ('CALENDARIO_MAIN_FR.CONTADOR = '|| TO_CHAR(CALENDARIO_MAIN_FR.CONTADO
R));
COUNT_AUX:=CALENDARIO_MAIN_FR.CONTADOR;

WHILE COUNT_AUX <> 0 
DO BEGIN
DEBUG_LOG ('COUNT_AUX = '|| TO_CHAR(COUNT_AUX));
IF (CALENDARIO_MAIN_FR.COD_SERVICIO = 'GENN') OR
   (CALENDARIO_MAIN_FR.COD_SERVICIO = 'GENS') OR
   (CALENDARIO_MAIN_FR.COD_SERVICIO = 'DISP')
THEN BEGIN 
        COD_SERVICIO:=CALENDARIO_MAIN_FR.COD_SERVICIO;
        COD_RAZON:=CALENDARIO_MAIN_FR.COD_RAZON;
        JEFE_SERVICIO:=CALENDARIO_MAIN_FR.SEGURO_SOCIAL_JEFE_SERV;

        DHM_OLD:=CALENDARIO_MAIN_FR.FCH_ACTIVIDAD_HORA_MIN_CONTAC0;
        DUR_OLD:=CALENDARIO_MAIN_FR.DURACION_HORA_MIN_CONTACTO;
        DHM_OLD_CHAR:=TO_CHAR(DHM_OLD,'DDMMYYYYHH24MI');
        DUR_OLD_CHAR:=TO_CHAR(DUR_OLD,'HH24MI');
        DHM_OLD_FCH_CHAR:=SUBSTR(DHM_OLD_CHAR,0,8);
        DHM_OLD_HH:=TO_NUMBER(SUBSTR(DHM_OLD_CHAR,8,2));
        DHM_OLD_MI:=TO_NUMBER(SUBSTR(DHM_OLD_CHAR,10,2));
        DUR_OLD_HH:=TO_NUMBER(SUBSTR(DUR_OLD_CHAR,0,2));
        DUR_OLD_MI:=TO_NUMBER(SUBSTR(DUR_OLD_CHAR,2,2));

        {GENERAR DHM_OLD_MAIS_DUR_OLD}

        TOTAL_MI:=DHM_OLD_MI + DUR_OLD_MI;
        IF TOTAL_MI >= 60
        THEN BEGIN
                TOTAL_MI:=TOTAL_MI - 60;
                RESTO_HH:=1;
             END;

        TOTAL_HH:=DHM_OLD_HH + DUR_OLD_HH + RESTO_HH;

        IF TOTAL_MI = 0 
        THEN TOTAL_MI_CHAR:='00';
        ELSE TOTAL_MI_CHAR:=TO_CHAR(TOTAL_MI);
        
        IF TOTAL_HH <= 9 
        THEN TOTAL_HH_CHAR:='0'||TO_CHAR(TOTAL_HH);
        ELSE TOTAL_HH_CHAR:=TO_CHAR(TOTAL_HH);

        DHM_OLD_MAIS_DUR_OLD:= TO_DATE(DHM_OLD_FCH_CHAR||
                               TOTAL_HH_CHAR||
                               TOTAL_MI_CHAR,'DDMMYYYYHH24MI');

        IF (CALENDARIO_MAIN_FR.NUMERO_REGISTRO <> CALENDARIO_MAIN_FR.CONTADOR) 
        THEN BEGIN
                CALL_CMD('NEXT RECORD');
DEBUG_LOG('F-SERV '||COD_SERVICIO);
DEBUG_LOG('F-RAZON '||COD_RAZON);
DEBUG_LOG('F-FCH '||TO_CHAR(DHM_OLD_MAIS_DUR_OLD));
DEBUG_LOG('F-JEFES '||TO_CHAR(JEFE_SERVICIO));

DEBUG_LOG('S-SERV '||CALENDARIO_MAIN_FR.COD_SERVICIO);
DEBUG_LOG('S-RAZON '||CALENDARIO_MAIN_FR.COD_RAZON);
DEBUG_LOG('S-FCH '||TO_CHAR(CALENDARIO_MAIN_FR.FCH_ACTIVIDAD_HORA_MIN_CONTAC0))
;
DEBUG_LOG('S-JEFES '||TO_CHAR(CALENDARIO_MAIN_FR.SEGURO_SOCIAL_JEFE_SERV));

        IF (CALENDARIO_MAIN_FR.COD_SERVICIO = COD_SERVICIO) AND
           (CALENDARIO_MAIN_FR.COD_RAZON = COD_RAZON) AND
           (JEFE_SERVICIO=CALENDARIO_MAIN_FR.SEGURO_SOCIAL_JEFE_SERV) AND
    (SUBSTR(TO_CHAR(CALENDARIO_MAIN_FR.FCH_ACTIVIDAD_HORA_MIN_CONTAC0),0,13) =
       SUBSTR(TO_CHAR(DHM_OLD_MAIS_DUR_OLD),0,13))
                THEN BEGIN
                        CALENDARIO_MAIN_FR.FCH_ACTIVIDAD_HORA_MIN_CONTAC0:=
                        DHM_OLD;

                        DUR_NEW:=CALENDARIO_MAIN_FR.DURACION_HORA_MIN_CONTACTO;
                        DUR_NEW_CHAR:=TO_CHAR(DUR_NEW,'HH24MI');
                        DUR_NEW_HH:=TO_NUMBER(SUBSTR(DUR_NEW_CHAR,0,2));
                        DUR_NEW_MI:=TO_NUMBER(SUBSTR(DUR_NEW_CHAR,2,2));

                        {GENERAR DUR_OLD_MAIS_DUR_NEW}

                        RESTO_HH:=0;
                        TOTAL_MI:=0;

                        TOTAL_MI:=DUR_OLD_MI + DUR_NEW_MI;
                        IF TOTAL_MI >= 60
                        THEN BEGIN
                                TOTAL_MI:=TOTAL_MI - 60;
                                RESTO_HH:=1;
                             END;

                        TOTAL_HH:=DUR_OLD_HH + DUR_NEW_HH + RESTO_HH;

                        IF TOTAL_MI = 0 
                        THEN TOTAL_MI_CHAR:='00';
                        ELSE TOTAL_MI_CHAR:=TO_CHAR(TOTAL_MI);

                        IF TOTAL_HH <= 9 
                        THEN TOTAL_HH_CHAR:='0'||TO_CHAR(TOTAL_HH);
                        ELSE TOTAL_HH_CHAR:=TO_CHAR(TOTAL_HH);

                        CALENDARIO_MAIN_FR.DURACION_HORA_MIN_CONTACTO:=
                        TO_DATE(TOTAL_HH_CHAR||TOTAL_MI_CHAR,'HH24MI');
                
                        CALL_CMD('PREVIOUS RECORD');
                        CALENDARIO_MAIN_FR.MARKED_TO_DELETE:='T';
                        CALL_CMD('NEXT RECORD');

                        COUNT_AUX:=COUNT_AUX - 1;
DEBUG_LOG ('COUNT_AUX = '|| TO_CHAR(COUNT_AUX));

                     END;
                ELSE BEGIN
                        COUNT_AUX:=COUNT_AUX - 1;
DEBUG_LOG ('COUNT_AUX = '|| TO_CHAR(COUNT_AUX));
                     END;
             END;
        ELSE BEGIN
                COUNT_AUX:=COUNT_AUX - 1;
DEBUG_LOG ('COUNT_AUX = '|| TO_CHAR(COUNT_AUX));
                IF COUNT_AUX <> 0
                THEN BEGIN
                        CALL_CMD('NEXT RECORD');
                     END;
             END;
     END;
ELSE BEGIN
        COUNT_AUX:=COUNT_AUX - 1;
DEBUG_LOG ('COUNT_AUX = '|| TO_CHAR(COUNT_AUX));
        IF COUNT_AUX <> 0
        THEN BEGIN
                CALL_CMD('NEXT RECORD');
             END;
     END;

END; { ENDING THE WHILE }

{ DELETE RECORDS MARKED TO BE DELETED }

        IF CALENDARIO_MAIN_FR.CONTADOR <> 1
                THEN CALL_CMD('FIRST RECORD');

COUNT_AUX:=CALENDARIO_MAIN_FR.CONTADOR;
DEBUG_LOG ('COUNT_AUX = '|| TO_CHAR(COUNT_AUX));

WHILE COUNT_AUX <> 0
DO BEGIN
        IF CALENDARIO_MAIN_FR.MARKED_TO_DELETE = 'T'
        THEN BEGIN
DEBUG_LOG ('COUNT_AUX = '|| TO_CHAR(COUNT_AUX));
                CALL_CMD('DELETE RECORD');
DEBUG_LOG ('COUNT_AUX = '|| TO_CHAR(COUNT_AUX));
                COUNT_AUX:=COUNT_AUX - 1;                
             END;
        ELSE BEGIN
                COUNT_AUX:= COUNT_AUX - 1;
DEBUG_LOG ('COUNT_AUX = '|| TO_CHAR(COUNT_AUX));
                IF COUNT_AUX <> 0 
                THEN CALL_CMD('NEXT RECORD');
             END;
   END;
SET_NOTRACE();
END;
    



--------------------------------------------------------------------- */
