package gov.dlf.logic;


import gov.dlf.facade.*;
import net.maintrend.interfaces.*;
import net.maintrend.interlink.*;
import net.maintrend.rallyengine.*;
import net.maintrend.util.*;



/**
 * __Comment
 *
 * Generated by Rally-to-Java Convertor. MainTrend Ltd.
 */
public class SERVICIO_CLIENTE_BEF_FORM_ADL
     extends ADL
{
  // -------------------------------------------------------------------
  // ----------   Class Attributes   -----------------------------------

  /**  */
  public static boolean staticCall = true;



  // -------------------------------------------------------------------
  // ----------   Instance Attributes   --------------------------------

  /**  */
  public SAIC_DMQ_ORA_Application app;
  /**  */
  public RallyDataManager dm = null;



  // -------------------------------------------------------------------
  // ----------   Instance Condition Attributes   ----------------------
 
  public boolean _condition0 = false;

 

  // -------------------------------------------------------------------
  // ----------   Instance Export Attributes   -------------------------





  // -------------------------------------------------------------------
  // ----------   Instance Attributes' Access Methods   ----------------
    




  // -------------------------------------------------------------------
  // ----------   Methods   --------------------------------------------

  /**
   * 
   * @param __app
   * @return
   */
  public static SERVICIO_CLIENTE_BEF_FORM_ADL get ( RallyApplication __app )
  {
    SERVICIO_CLIENTE_BEF_FORM_ADL adl = new SERVICIO_CLIENTE_BEF_FORM_ADL ( );
    __app.register ( adl, "SERVICIO_CLIENTE_BEF_FORM_ADL" );
    __app.setADL ( SERVICIO_CLIENTE_BEF_FORM_ADL.class, adl ); 
    adl.setApplication ( __app );
    return adl;
  }


  /**
   *
   * @param __app
   * @param ps
   *
   * @return
   */
  public static void exec ( RallyApplication __app, ParameterSet ps )
  {
    SERVICIO_CLIENTE_BEF_FORM_ADL.get ( __app ).process ( ps );
  }


  /**
   *
   * @param __app
   *
   * @return
   */
  public static void exec ( RallyApplication __app )
  {
    ParameterSet ps = null;
    SERVICIO_CLIENTE_BEF_FORM_ADL.exec ( __app, ps );
  }


  /**
   * Overrides the ancestor's method
   * 
   * @param __app
   */
  @Override
public void setApplication ( RallyApplication __app )
  {
    this.app = ( SAIC_DMQ_ORA_Application ) __app;
    if ( this.app != null )
    {
      this.dm = ( RallyDataManager ) this.app.getDataManager ( );
    }
  }


  /**
   * Overrides the ancestor's method
   * 
   * @param parms
   */
  @Override
public void execute ( ParameterSet parms )
  {
    this.process ( parms );
  }




  /**
   *
   */
  protected void doReturn ( )
  {
    this.unregister ( );
  }


  /**
   *
   */
  public void unregister ( )
  {
    this.app.unregister ( this );
    IRegisteredObject rObj = this.app.get ( "SERVICIO_CLIENTE_BEF_FORM_ADL" );
    if ( rObj != null && rObj instanceof SERVICIO_CLIENTE_BEF_FORM_ADL )
    {
      this.app.setADL ( SERVICIO_CLIENTE_BEF_FORM_ADL.class, ( SERVICIO_CLIENTE_BEF_FORM_ADL ) rObj );
    }
  }


  /**
   * Overrides the ancestor's method
   * 
   * @param ps
   */
  @Override
protected void process ( ParameterSet ps )
  {
    Debug.println ( Debug.TRACE, "SERVICIO_CLIENTE_BEF_FORM_ADL Step " + this.currentStep );
    super.process ( ps );
    switch ( this.currentStep ) 
    {
      case 0:  { this.currentStep ++; this.step0 ( this.keyParms ); break; }
      case 1:  { this.currentStep ++; this.step1 ( this.keyParms ); break; }
      case 2:  { this.currentStep ++; this.step2 ( this.keyParms ); break; }
      default: 
      { 
        this.currentStep = 0;
        Debug.println ( Debug.TRACE, "SERVICIO_CLIENTE_BEF_FORM_ADL ended" );
        this.unregister ( );
        break;
      }
    }
    if ( this.currentStep > 0 ) this.app.goOn ( );
  }



  /**
   *
   */
  protected void step0 ( ParameterSet ps )
  {

    if ( Compare.equals ( this.app.form ( "SERVICIOS_CLIENTE_FRM" ).getDoubleItem ( "CONT_SERV" ), 0 ) ) 
    {
      this._condition0 = true;
    }
    else
    {
      this._condition0 = false;
    }
    if ( this._condition0 )
    {
      SOLIC_SERV_COMP_FAM_BEF_DELETE_ADL.setTIENE_SERVICIO ( this.app, "F" );
      this.app.callCommand ( RallyAppCommandFactory.IGNORE );
      return;
    }

  }


  /**
   *
   */
  protected void step1 ( ParameterSet ps )
  {
    if ( this._condition0 )    //    if ( Compare.equals ( this.app.form ( "SERVICIOS_CLIENTE_FRM" ).getDoubleItem ( "CONT_SERV" ), 0 ) ) 
    {
      this.app.executeCommand ( RallyAppCommandFactory.ABORTACTION );
      return;
    }

  }


  /**
   *
   */
  protected void step2 ( ParameterSet ps )
  {
    if ( this._condition0 )    //    if ( Compare.equals ( this.app.form ( "SERVICIOS_CLIENTE_FRM" ).getDoubleItem ( "CONT_SERV" ), 0 ) ) 
    {
      return; 
    }

  }
}



/* ---------------------------------------------------------------------


     
PROCEDURE SERVICIO_CLIENTE_BEF_FORM_ADL;

BEGIN
        IF (SERVICIOS_CLIENTE_FRM.CONT_SERV = 0) THEN
        BEGIN
                SOLIC_SERV_COMP_FAM_BEF_DELETE_ADL.TIENE_SERVICIO := 'F';
                CALL_CMD ('IGNORE');
                EXECUTE_CMD(ABORTACTION);
        END;
END;
    



--------------------------------------------------------------------- */
