package gov.dlf.logic;


import gov.dlf.facade.*;
import net.maintrend.interfaces.*;
import net.maintrend.interlink.*;
import net.maintrend.rallyengine.*;
import net.maintrend.util.*;



/**
 * __Comment
 *
 * Generated by Rally-to-Java Convertor. MainTrend Ltd.
 */
public class VERIFICAR_ACCION_TOMADA_EMERG_ADL
     extends ADL
{
  // -------------------------------------------------------------------
  // ----------   Class Attributes   -----------------------------------

  /**  */
  public static boolean staticCall = true;



  // -------------------------------------------------------------------
  // ----------   Instance Attributes   --------------------------------

  /**  */
  public SAIC_DMQ_ORA_Application app;
  /**  */
  public RallyDataManager dm = null;



  // -------------------------------------------------------------------
  // ----------   Instance Condition Attributes   ----------------------

 

  // -------------------------------------------------------------------
  // ----------   Instance Export Attributes   -------------------------

  public double KEY_PRESS = 0;





  // -------------------------------------------------------------------
  // ----------   Instance Attributes' Access Methods   ----------------

  
  /**  */
  public static void setKEY_PRESS  ( RallyApplication __app, Parameter value )
  {
    ( ( VERIFICAR_ACCION_TOMADA_EMERG_ADL ) __app.getADL ( VERIFICAR_ACCION_TOMADA_EMERG_ADL.class ) ).KEY_PRESS = value.getDouble ( );
  }  
    



  /**  */
  public static double getKEY_PRESS  ( RallyApplication __app )
  {
    return ( ( VERIFICAR_ACCION_TOMADA_EMERG_ADL ) __app.getADL ( VERIFICAR_ACCION_TOMADA_EMERG_ADL.class ) ).KEY_PRESS;
  }


  /**  */
  public static Double getKEY_PRESSDouble ( RallyApplication __app )
  {
    return new Double ( ( ( VERIFICAR_ACCION_TOMADA_EMERG_ADL ) __app.getADL ( VERIFICAR_ACCION_TOMADA_EMERG_ADL.class ) ).KEY_PRESS );
  }


  /**  */
  public static void setKEY_PRESS  ( RallyApplication __app, double value )
  {
    ( ( VERIFICAR_ACCION_TOMADA_EMERG_ADL ) __app.getADL ( VERIFICAR_ACCION_TOMADA_EMERG_ADL.class ) ).KEY_PRESS = value;
  }


  /**  */
  public static void setKEY_PRESS  ( RallyApplication __app, Object value )
  {
    ( ( VERIFICAR_ACCION_TOMADA_EMERG_ADL ) __app.getADL ( VERIFICAR_ACCION_TOMADA_EMERG_ADL.class ) ).KEY_PRESS = ( ( Double ) value ).doubleValue ( );
  }



  // -------------------------------------------------------------------
  // ----------   Methods   --------------------------------------------

  /**
   * 
   * @param __app
   * @return
   */
  public static VERIFICAR_ACCION_TOMADA_EMERG_ADL get ( RallyApplication __app )
  {
    VERIFICAR_ACCION_TOMADA_EMERG_ADL adl = new VERIFICAR_ACCION_TOMADA_EMERG_ADL ( );
    __app.register ( adl, "VERIFICAR_ACCION_TOMADA_EMERG_ADL" );
    __app.setADL ( VERIFICAR_ACCION_TOMADA_EMERG_ADL.class, adl ); 
    adl.setApplication ( __app );
    return adl;
  }


  /**
   *
   * @param __app
   * @param ps
   *
   * @return
   */
  public static void exec ( RallyApplication __app, ParameterSet ps )
  {
    VERIFICAR_ACCION_TOMADA_EMERG_ADL.get ( __app ).process ( ps );
  }


  /**
   *
   * @param __app
   *
   * @return
   */
  public static void exec ( RallyApplication __app )
  {
    ParameterSet ps = null;
    VERIFICAR_ACCION_TOMADA_EMERG_ADL.exec ( __app, ps );
  }


  /**
   * Overrides the ancestor's method
   * 
   * @param __app
   */
  @Override
public void setApplication ( RallyApplication __app )
  {
    this.app = ( SAIC_DMQ_ORA_Application ) __app;
    if ( this.app != null )
    {
      this.dm = ( RallyDataManager ) this.app.getDataManager ( );
    }
  }


  /**
   * Overrides the ancestor's method
   * 
   * @param parms
   */
  @Override
public void execute ( ParameterSet parms )
  {
    this.process ( parms );
  }




  /**
   *
   */
  protected void doReturn ( )
  {
    this.unregister ( );
  }


  /**
   *
   */
  public void unregister ( )
  {
    this.app.unregister ( this );
    IRegisteredObject rObj = this.app.get ( "VERIFICAR_ACCION_TOMADA_EMERG_ADL" );
    if ( rObj != null && rObj instanceof VERIFICAR_ACCION_TOMADA_EMERG_ADL )
    {
      this.app.setADL ( VERIFICAR_ACCION_TOMADA_EMERG_ADL.class, ( VERIFICAR_ACCION_TOMADA_EMERG_ADL ) rObj );
    }
  }


  /**
   * Overrides the ancestor's method
   * 
   * @param ps
   */
  @Override
protected void process ( ParameterSet ps )
  {
    Debug.println ( Debug.TRACE, "VERIFICAR_ACCION_TOMADA_EMERG_ADL Step " + this.currentStep );
    super.process ( ps );
    switch ( this.currentStep ) 
    {
      case 0:  { this.currentStep ++; this.step0 ( this.keyParms ); break; }
      default: 
      { 
        this.currentStep = 0;
        Debug.println ( Debug.TRACE, "VERIFICAR_ACCION_TOMADA_EMERG_ADL ended" );
        this.unregister ( );
        break;
      }
    }
    if ( this.currentStep > 0 ) this.app.goOn ( );
  }



  /**
   *
   */
  protected void step0 ( ParameterSet ps )
  {

    KEY_PRESS = RallyAppCommandFactory.translate ( this.app.getLastCommandName ( ) );
    if ( this.app.isCurrentField ( "INFORMACION_SERV_TANF_FR", "ACCION_TOMADA_AUTO" ) ) 
    {
      if ( ( ! Compare.equals ( ( ( this.app.form ( "INFORMACION_SERV_TANF_FR" ).getStringItem ( "ACCION_TOMADA_AUTO" )) ).toUpperCase ( ), "X" ) ) && ( ! Compare.equals ( ( ( this.app.form ( "INFORMACION_SERV_TANF_FR" ).getStringItem ( "ACCION_TOMADA_AUTO" )) ).toUpperCase ( ), "" ) )  ) 
      {
        this.app.form ( "INFORMACION_SERV_TANF_FR" ).setItem ( "ACCION_TOMADA_AUTO", ""  );
        this.app.errorFlag = false;
      }
      if ( Compare.equals ( ( ( this.app.form ( "INFORMACION_SERV_TANF_FR" ).getStringItem ( "ACCION_TOMADA_AUTO" )) ).toUpperCase ( ), "X" ) ) 
      {
        this.app.form ( "INFORMACION_SERV_TANF_FR" ).setItem ( "ACCION_TOMADA_DENE", ""  );
        this.app.form ( "INFORMACION_SERV_TANF_FR" ).setItem ( "ACCION_TOMADA_RETI", ""  );
        this.app.form ( "INFORMACION_SERV_TANF_FR" ).setItem ( "EMG_RAZON", ""  );
        this.app.form ( "INFORMACION_SERV_TANF_FR" ).setItem ( "EMEG_DESC_RAZON", ""  );
        this.app.form ( "INFORMACION_SERV_TANF_FR" ).setItem ( "EMG_ESPECIFIQUE_1", ""  );
        this.app.form ( "INFORMACION_SERV_TANF_FR" ).setItem ( "EMG_ESPECIFIQUE_2", ""  );
      }
    }
    else if ( this.app.isCurrentField ( "INFORMACION_SERV_TANF_FR", "ACCION_TOMADA_DENE" )  )
    {
      if ( ( ! Compare.equals ( ( ( this.app.form ( "INFORMACION_SERV_TANF_FR" ).getStringItem ( "ACCION_TOMADA_DENE" )) ).toUpperCase ( ), "X" ) ) && ( ! Compare.equals ( ( ( this.app.form ( "INFORMACION_SERV_TANF_FR" ).getStringItem ( "ACCION_TOMADA_DENE" )) ).toUpperCase ( ), "" ) )  ) 
      {
        this.app.form ( "INFORMACION_SERV_TANF_FR" ).setItem ( "ACCION_TOMADA_DENE", ""  );
        this.app.errorFlag = false;
      }
      if ( Compare.equals ( ( ( this.app.form ( "INFORMACION_SERV_TANF_FR" ).getStringItem ( "ACCION_TOMADA_DENE" )) ).toUpperCase ( ), "X" ) ) 
      {
        this.app.form ( "INFORMACION_SERV_TANF_FR" ).setItem ( "ACCION_TOMADA_AUTO", ""  );
        this.app.form ( "INFORMACION_SERV_TANF_FR" ).setItem ( "ACCION_TOMADA_RETI", ""  );
        this.app.form ( "INFORMACION_SERV_TANF_FR" ).setItem ( "VLR_BENEFICIOS", 0  );
        this.app.form ( "INFORMACION_SERV_TANF_FR" ).setItem ( "EMG_PAREO", ""  );
        this.app.form ( "INFORMACION_SERV_TANF_FR" ).setItem ( "EMG_ESPECIFIQUE_2", ""  );
      }
    }
    else if ( this.app.isCurrentField ( "INFORMACION_SERV_TANF_FR", "ACCION_TOMADA_RETI" )  )
    {
      if ( ( ! Compare.equals ( ( ( this.app.form ( "INFORMACION_SERV_TANF_FR" ).getStringItem ( "ACCION_TOMADA_RETI" )) ).toUpperCase ( ), "X" ) ) && ( ! Compare.equals ( ( ( this.app.form ( "INFORMACION_SERV_TANF_FR" ).getStringItem ( "ACCION_TOMADA_RETI" )) ).toUpperCase ( ), "" ) )  ) 
      {
        this.app.form ( "INFORMACION_SERV_TANF_FR" ).setItem ( "ACCION_TOMADA_RETI", ""  );
        this.app.errorFlag = false;
      }
      if ( Compare.equals ( ( ( this.app.form ( "INFORMACION_SERV_TANF_FR" ).getStringItem ( "ACCION_TOMADA_RETI" )) ).toUpperCase ( ), "X" ) ) 
      {
        this.app.form ( "INFORMACION_SERV_TANF_FR" ).setItem ( "ACCION_TOMADA_DENE", ""  );
        this.app.form ( "INFORMACION_SERV_TANF_FR" ).setItem ( "ACCION_TOMADA_AUTO", ""  );
        this.app.form ( "INFORMACION_SERV_TANF_FR" ).setItem ( "EMG_RAZON", ""  );
        this.app.form ( "INFORMACION_SERV_TANF_FR" ).setItem ( "EMEG_DESC_RAZON", ""  );
        this.app.form ( "INFORMACION_SERV_TANF_FR" ).setItem ( "EMG_ESPECIFIQUE_1", ""  );
        this.app.form ( "INFORMACION_SERV_TANF_FR" ).setItem ( "VLR_BENEFICIOS", 0  );
        this.app.form ( "INFORMACION_SERV_TANF_FR" ).setItem ( "EMG_PAREO", ""  );
      }
    }

  }
}



/* ---------------------------------------------------------------------


     
PROCEDURE VERIFICAR_ACCION_TOMADA_EMERG_ADL;
VAR
KEY_PRESS : NUMBER;

BEGIN
KEY_PRESS := GET_CMD();
        IF IS_CURRENT_FIELD(INFORMACION_SERV_TANF_FR.ACCION_TOMADA_AUTO)
        THEN
           BEGIN
            IF (UPCASE(INFORMACION_SERV_TANF_FR.ACCION_TOMADA_AUTO) <> 'X') and
               (UPCASE(INFORMACION_SERV_TANF_FR.ACCION_TOMADA_AUTO) <> '') 
            THEN BEGIN
                   INFORMACION_SERV_TANF_FR.ACCION_TOMADA_AUTO := '';
                   SET_FAILURE();
                 END;
            IF (UPCASE(INFORMACION_SERV_TANF_FR.ACCION_TOMADA_AUTO) = 'X') THEN
                BEGIN
                INFORMACION_SERV_TANF_FR.ACCION_TOMADA_DENE := '';
                INFORMACION_SERV_TANF_FR.ACCION_TOMADA_RETI := '';
                INFORMACION_SERV_TANF_FR.EMG_RAZON:= '';
                INFORMACION_SERV_TANF_FR.EMEG_DESC_RAZON:= '';
                INFORMACION_SERV_TANF_FR.EMG_ESPECIFIQUE_1 := '';
                INFORMACION_SERV_TANF_FR.EMG_ESPECIFIQUE_2 := '';
                END;
           END;
        ELSE IF IS_CURRENT_FIELD(INFORMACION_SERV_TANF_FR.ACCION_TOMADA_DENE)
             THEN
               BEGIN
                IF (UPCASE(INFORMACION_SERV_TANF_FR.ACCION_TOMADA_DENE) <> 'X') 
and
                   (UPCASE(INFORMACION_SERV_TANF_FR.ACCION_TOMADA_DENE) <> '') 
                THEN BEGIN
                       INFORMACION_SERV_TANF_FR.ACCION_TOMADA_DENE := '';
                       SET_FAILURE();
                     END;
                IF (UPCASE(INFORMACION_SERV_TANF_FR.ACCION_TOMADA_DENE) = 'X')
                THEN    BEGIN
                                INFORMACION_SERV_TANF_FR.ACCION_TOMADA_AUTO := '
';
                                INFORMACION_SERV_TANF_FR.ACCION_TOMADA_RETI := '
';
                                INFORMACION_SERV_TANF_FR.VLR_BENEFICIOS := 0;
                                INFORMACION_SERV_TANF_FR.EMG_PAREO := '';
                                INFORMACION_SERV_TANF_FR.EMG_ESPECIFIQUE_2 := ''
;
                        END;
               END;
             ELSE IF IS_CURRENT_FIELD(INFORMACION_SERV_TANF_FR.ACCION_TOMADA_RET
I)
                  THEN BEGIN
                      IF (UPCASE(INFORMACION_SERV_TANF_FR.ACCION_TOMADA_RETI) <>
 'X') AND
                         (UPCASE(INFORMACION_SERV_TANF_FR.ACCION_TOMADA_RETI) <>
 '') 
                        THEN BEGIN
                               INFORMACION_SERV_TANF_FR.ACCION_TOMADA_RETI := ''
;
                               SET_FAILURE();
                             END;
                      IF (UPCASE(INFORMACION_SERV_TANF_FR.ACCION_TOMADA_RETI) = 
'X') THEN
                        BEGIN
                                INFORMACION_SERV_TANF_FR.ACCION_TOMADA_DENE := '
';
                                INFORMACION_SERV_TANF_FR.ACCION_TOMADA_AUTO := '
';
                                INFORMACION_SERV_TANF_FR.EMG_RAZON:= '';
                                INFORMACION_SERV_TANF_FR.EMEG_DESC_RAZON:= '';
                                INFORMACION_SERV_TANF_FR.EMG_ESPECIFIQUE_1 := ''
;
                                INFORMACION_SERV_TANF_FR.VLR_BENEFICIOS := 0;
                                INFORMACION_SERV_TANF_FR.EMG_PAREO := '';
                        END;

                       END;
END;
    



--------------------------------------------------------------------- */
