package gov.dlf.facade;


import gov.dlf.external.*;
import gov.dlf.logic.*;
import gov.dlf.presentation.*;


import java.awt.event.ActionEvent;

import net.maintrend.appmanager.*;
import net.maintrend.interfaces.*;
import net.maintrend.interlink.*;
import net.maintrend.mdi.*;
import net.maintrend.rallyengine.*;
import net.maintrend.rallyengine.appcommands.*;
import net.maintrend.util.*;



/**
 * 
 *
 * Generated by Rally-to-Java Convertor. MainTrend Ltd.
 */
public class _MAIN_MENU_5
     extends MenuActions
{
  // -------------------------------------------------------------------
  // ----------   Constructor   ----------------------------------------

  /**
   *
   */
  public _MAIN_MENU_5 ( IExecutable actionExecutor )
  {
    super ( actionExecutor );
    this.initActions ( );
  }


  /**
   *
   */
  public void initActions ( )
  {
    MDIAction action;

    action = new MenuAction ( "SITUACION FAMILIAR" )
    {
      /**  */
      public static final long serialVersionUID = 0L;
      /**  */
      public void initAction ( )
      {
        super.initAction ( );
        this.actionCommand = "MAIN_MENU_1";
        this.actionType    = "Menu";
        this.actionCall    = "RETURN_TO";
      }

      /**  */
      public void actionPerformed ( ActionEvent e )
      {
        if ( executor != null )
        {
          Debug.println ( Debug.TRACE, "_MAIN_MENU_5 - action <SITUACION FAMILIAR> invoked." );
          //RETURN_TO MAIN_MENU_1 - Menu
          app.returnTo ( "MAIN_MENU_1" ); return;

        }
      }
    };
    this.add ( action );

    action = new MenuAction ( "RESUMEN DE SERVICOS A FAMILIAS" )
    {
      /**  */
      public static final long serialVersionUID = 0L;
      /**  */
      public void initAction ( )
      {
        super.initAction ( );
        this.actionCommand = "MAIN_MENU_1";
        this.actionType    = "Menu";
        this.actionCall    = "RETURN_TO";
      }

      /**  */
      public void actionPerformed ( ActionEvent e )
      {
        if ( executor != null )
        {
          Debug.println ( Debug.TRACE, "_MAIN_MENU_5 - action <RESUMEN DE SERVICOS A FAMILIAS> invoked." );
          //RETURN_TO MAIN_MENU_1 - Menu
          app.returnTo ( "MAIN_MENU_1" ); return;

        }
      }
    };
    this.add ( action );

    action = new MenuAction ( "NUMERO DE FAMILIAS RECIBIENDO SERVICIO" )
    {
      /**  */
      public static final long serialVersionUID = 0L;
      /**  */
      public void initAction ( )
      {
        super.initAction ( );
        this.actionCommand = "REPORT_5_3_ADL";
        this.actionType    = "ADL";
        this.actionCall    = "CALL";
      }

      /**  */
      public void actionPerformed ( ActionEvent e )
      {
        if ( executor != null )
        {
          Debug.println ( Debug.TRACE, "_MAIN_MENU_5 - action <NUMERO DE FAMILIAS RECIBIENDO SERVICIO> invoked." );
          //CALL REPORT_5_3_ADL - ADL
          REPORT_5_3_ADL.exec ( app );
        }
      }
    };
    this.add ( action );

    action = new MenuAction ( "INDIVIDUOS DADOS DE BAJA DE LA ESCUELA" )
    {
      /**  */
      public static final long serialVersionUID = 0L;
      /**  */
      public void initAction ( )
      {
        super.initAction ( );
        this.actionCommand = "MAIN_MENU_1";
        this.actionType    = "Menu";
        this.actionCall    = "RETURN_TO";
      }

      /**  */
      public void actionPerformed ( ActionEvent e )
      {
        if ( executor != null )
        {
          Debug.println ( Debug.TRACE, "_MAIN_MENU_5 - action <INDIVIDUOS DADOS DE BAJA DE LA ESCUELA> invoked." );
          //RETURN_TO MAIN_MENU_1 - Menu
          app.returnTo ( "MAIN_MENU_1" ); return;

        }
      }
    };
    this.add ( action );

    action = new MenuAction ( "COMPOSICION FAMILIAR INFORME." )
    {
      /**  */
      public static final long serialVersionUID = 0L;
      /**  */
      public void initAction ( )
      {
        super.initAction ( );
        this.actionCommand = "MAIN_MENU_1";
        this.actionType    = "Menu";
        this.actionCall    = "RETURN_TO";
      }

      /**  */
      public void actionPerformed ( ActionEvent e )
      {
        if ( executor != null )
        {
          Debug.println ( Debug.TRACE, "_MAIN_MENU_5 - action <COMPOSICION FAMILIAR INFORME.> invoked." );
          //RETURN_TO MAIN_MENU_1 - Menu
          app.returnTo ( "MAIN_MENU_1" ); return;

        }
      }
    };
    this.add ( action );

    action = new MenuAction ( "SALIR" )
    {
      /**  */
      public static final long serialVersionUID = 0L;
      /**  */
      public void initAction ( )
      {
        super.initAction ( );
        this.actionCommand = "FINISH ACTION";
        this.actionType    = "";
        this.actionCall    = "CALL_CMD";
      }

      /**  */
      public void actionPerformed ( ActionEvent e )
      {
        if ( executor != null )
        {
          Debug.println ( Debug.TRACE, "_MAIN_MENU_5 - action <SALIR> invoked." );
          //CALL_CMD FINISH ACTION - 
          app.callCommand ( "FINISH ACTION" );
        }
      }
    };
    this.add ( action );
  }
}
